function carianalisispasien()
{
	$("#frmcarianalisispasien").ajaxForm(frmcarianalisispasien_opt);
}
var frmcarianalisispasien_opt = {
		target : '#tableview',
		url: '<?php echo $this->basePath; ?>/pasien/analisispasien/analisispasienlist',
		type: 'post', 
		resetForm: false
};
function analisispasienlist()
{
	t_awal = document.getElementById('t_awal').value;
	t_akhir = document.getElementById('t_akhir').value;
	var param = {t_awal:t_awal,t_akhir:t_akhir};
	var url = '<?php echo $this->basePath; ?>/pasien/analisispasien/analisispasienlist';
	jQuery.get(url, param, function(data) {
		$("div#tableview").html(data);
	});
}

function analisispasienForm(jenisForm, id)
{
	t_awal = document.getElementById('t_awal').value;
	t_akhir = document.getElementById('t_akhir').value;
	var url = '<?php echo $this->basePath; ?>/pasien/analisispasien/analisispasiendata';
	var param = { jenisForm:jenisForm,id:id,t_awal:t_awal,t_akhir:t_akhir};
	jQuery.get(url, param, function(data) {
		jQuery("div#tableview").html(data);
		jQuery("#frmtambahanalisispasien").ajaxForm(tambahAnalisispasien_opt);
		jQuery("#frmubahanalisispasien").ajaxForm(ubahAnalisispasien_opt);
	});
}

var tambahAnalisispasien_opt = {
	target : '#tableview',
	url: '<?php echo $this->basePath; ?>/pasien/analisispasien/analisispasien',
	beforeSubmit : function() {
		
		if (document.getElementById('kode_pasien').value == ''){
			alert('Kode/Nama Pasien harus Diisi');
			return false;
		}

		if (document.getElementById('n_nama').value == ''){
			alert('Kode/Nama Pasien harus Diisi');
			return false;
		}


		/*if (document.getElementById('gender').value == '-'){
			alert('Jenis Kelamin harus Dipilih');
			return false;
		}

		if (document.getElementById('t_lahir').value == ''){
			alert('Tempat/Tgl Lahir harus Diisi');
			return false;
		}

		if (document.getElementById('d_medrec').value == ''){
			alert('Tempat/Tgl Lahir harus Diisi');
			return false;
		}

		if (document.getElementById('t_badan').value == ''){
			alert('Alamat harus Diisi');
			return false;
		}
		
		if (document.getElementById('b_badan').value == ''){
			alert('Telp/HP Diisi');
			return false;
		}
		if (document.getElementById('n_tensi').value == ''){
			alert('Telp/HP Diisi');
			return false;
		}

		if (document.getElementById('n_diagnosis').value == ''){
			alert('Bidang Studi harus Diisi');
			return false;
		}*/
	answer = confirm('Apakah data anda masukan sudah benar?.\n\'OK\' Jika benar, \'Cancel\' jika tidak.' );

	//alert(answer);
	if(answer !=0) { 
		return true;
	}
	else{
		return false;
	}
		
	},
	success: function(){
	doCount(5);
	
	},
	type: 'post', 
	resetForm: false
};

var ubahAnalisispasien_opt = {
	target : '#tableview',
	url: '<?php echo $this->basePath; ?>/pasien/analisispasien/analisispasienupdate',
	beforeSubmit : function() {

		/*if (document.getElementById('gender').value == '-'){
			alert('Jenis Kelamin harus Dipilih');
			return false;
		}

		if (document.getElementById('t_lahir').value == ''){
			alert('Tempat/Tgl Lahir harus Diisi');
			return false;
		}

		if (document.getElementById('d_medrec').value == ''){
			alert('Tempat/Tgl Lahir harus Diisi');
			return false;
		}

		if (document.getElementById('t_badan').value == ''){
			alert('Alamat harus Diisi');
			return false;
		}
		
		if (document.getElementById('b_badan').value == ''){
			alert('Telp/HP Diisi');
			return false;
		}
		if (document.getElementById('n_tensi').value == ''){
			alert('Telp/HP Diisi');
			return false;
		}

		if (document.getElementById('n_diagnosis').value == ''){
			alert('Bidang Studi harus Diisi');
			return false;
		}*/
	answer = confirm('Apakah data anda masukan sudah benar?.\n\'OK\' Jika benar, \'Cancel\' jika tidak.' );
	if(answer !=0) { 
		return true;
	}
	else{
		return false;
	}

	},
	success: function(){
	doCount(5);
	jQuery("#frmubahanalisispasien").ajaxForm(ubahAnalisispasien_opt);
	},
	type: 'post', 
	resetForm: false
};


function analisispasienHapus(param1, param2, n_nama)
{ 
	t_awal = document.getElementById('t_awal').value;
	t_akhir = document.getElementById('t_akhir').value;
	
	if(ConfirmDelete(param1,n_nama))
	{	
		handler = '<?php echo $this->basePath; ?>/pasien/analisispasien/analisispasienhapus';
		var opt = {id : param2,t_awal:t_awal,t_akhir:t_akhir};
		jQuery.get(handler,opt,function(data) {
				$("#tableview").html(data);
				doCount(5);
			 });
	}
}

function cetak(d_medrec)
{
	if(d_medrec == '' || d_medrec == '-' || d_medrec == '--'){alert('Tanngal harus Ada');return false;}

	var url = '<?php echo $this->basePath; ?>/pasien/analisispasien/cetakrekappdf?&d_medrec='+d_medrec;
	swin = window.open(url,'win','scrollbars,width=600,height=400,top=80,left=140,status=yes,toolbar=no,menubar=yes,location=no');
	swin.focus();
}

function cetakrekap(t_awal,t_akhir)
{
	if(t_awal == '' || t_awal == '-' || t_awal == '--'){alert('Periode Tanggal harus diisi');return false;}
	if(t_akhir == '' || t_akhir == '-' || t_akhir == '--'){alert('Periode Tanggal harus diisi');return false;}

	var url = '<?php echo $this->basePath; ?>/pasien/analisispasien/rekappdf?&t_awal='+t_awal+'&t_akhir='+t_akhir;
	swin = window.open(url,'win','scrollbars,width=600,height=400,top=80,left=140,status=yes,toolbar=no,menubar=yes,location=no');
	swin.focus();
}



function BukaWindows(){
	var w = 0; 
	var h = 0;
	w = screen.availWidth;
	h = screen.availHeight;
	var popW = 800, popH = 600;
	var leftc = (w-popW)/2;
	var topc = (h-popH)/2;
	var selectWindow = window.open(url,'Selection', 'left=' + leftc + ',top=' + topc + ', width='+popW+',height='+popH+',resizable=0,scrollbars=yes');
}

function CariPengadaan()
{
	document.getElementById('n_pengadaan').readOnly = true;
	id_pengadaan = document.getElementById('id_pengadaan').value;

	url = "<?php echo $this->basePath; ?>/adm/analisispasien/n_namapengadaan?id_pengadaan="+id_pengadaan;
	BukaWindows();
}


function tambahKepada()
{
	var table = document.getElementById('kepada'); 
	var rowCount = (table.rows.length);  
	var idRow = (rowCount)*1;
	var row = table.insertRow(rowCount);
	row.className = "event";	
	
	var cell0 = row.insertCell(0);  
	var num = (rowCount)*1+1;
	cell0.innerHTML = num+".";
	
	var cell1 = row.insertCell(1);  
	cell1.innerHTML = "<input type=\"text\" size = \"120\" maxlength = \"150\" name=\"n_nama_"+idRow+"\" id=\"n_nama_"+idRow+"\" value=\"\" > <input type=\"button\" value=\"Cari\" onclick=\"showDialog('dosen','"+idRow+"');\" >";
	
	var cell2 = row.insertCell(2);  
	var rowDelete = (idRow*1)+1;
	cell2.innerHTML = "<input type=\"hidden\" name=\"id_pegawai_"+idRow+"\" id=\"id_pegawai_"+idRow+"\" value=\"\" ><input type=\"hidden\" name=\"id_pembimbing_"+idRow+"\" id=\"id_pembimbing_"+idRow+"\" value=\"\"><img src=\"/images/cross.png\" title=\"Hapus Data\" onclick=\"deleteRow('kepada', this);getjumlahx();\"><a name=\"baris_"+idRow+"\"/>";
	
	document.getElementById('jumlahItem').value = (rowCount*1)+1;

}

function deleteRow(tableID, r) {
	var i=r.parentNode.parentNode.rowIndex;
	document.getElementById(tableID).deleteRow(i);
	var table = document.getElementById(tableID); 
	var rowCount = table.rows.length;  
	var idRow = rowCount*1;
	document.getElementById("jumlahItem").value = idRow;
	
}
function deleteRow2(param,id_item,no_item)
{ 
	if(ConfirmDelete(param, no_item))
	{	
		handler = '<?php echo $this->basePath; ?>/pasien/analisispasien/analisispasienhapus';
		//var opt = {id_item:id_item,tahun:tahun,cabang:cabang,kategoriCari:kategoriCari,carii:carii};
		jQuery.get(handler,function(data) {
				$("#tableview").html(data);
				doCount(5);
			 });
	}
}

function getKab(){
	var url = '<?php echo $this->basePath; ?>/pasien/analisispasien/get-kab';
	var propinsi = document.getElementById('c_propinsi').value;
	var param = {propinsi:propinsi};	
	$.getJSON(url,param,function(data){
		$('#kota').find('option').remove().end();
		
		$('#kota').attr('disabled',false).end();
		$('.someElement').attr('disabled', '');
		$('#kota').append($('<option>').text("--Pilih--").attr('value', "-"));
		$.each(data, function(i, value) {
				$('#kota').append($('<option>').text(value.n_kab).attr('value', value.id_kab));
		  });
	});
}



function dosenlist(jum) {
  var url        = '<?php echo $this->basePath; ?>/pasien/analisispasien/dosenlist';
  var param      = {jum:jum};
  jQuery.get(url,param,function(data) {   
    $("#dialog-browse").html(data);
    $("#dialog-browse").dialog("open");
  }); 
}

function cariDosen(jum)  {
  $("#frmCariDosen").ajaxForm(frmCariDosen_opt);
}

var frmCariDosen_opt = {
    target : '#dialog-browse',
    url: '<?php echo $this->basePath; ?>/pasien/analisispasien/dosenlist',
    type: 'get', 
    resetForm: false
};

function closeDialogDosen(id_pegawai,nama,jum) {  
  $("#dialog-browse").dialog("close");
  $("#id_pegawai_"+jum).val(id_pegawai);
  $("#n_nama_"+jum).val(nama);
}




function pasienlist() {
    var url        = '<?php echo $this->basePath; ?>/pasien/analisispasien/pasienlist';
    jQuery.get(url,function(data) {   
    $("#dialog-browse").html(data);
    $("#dialog-browse").dialog("open");
  }); 
}

function cariPasien()  {
  $("#frmCariPasien").ajaxForm(frmCariPasien_opt);
}

var frmCariPasien_opt = {
    target : '#dialog-browse',
    url: '<?php echo $this->basePath; ?>/pasien/analisispasien/pasienlist',
    type: 'get', 
    resetForm: false
};

function closeDialogPasien(kode_pasien,n_pasien) {  
  $("#dialog-browse").dialog("close");
  $("#kode_pasien").val(kode_pasien);
  $("#n_nama").val(n_pasien);
}




