<?
require_once 'Zend/View.php';
require_once 'share/format_date.php'; 
require_once 'share/format_page.php';
require_once "share/share_message.php";
require_once "share/oa_dec_cur_conv.php";

$ctrlFrm = new Zend_View();
$pesan = new share_message();
$halaman = new format_page();
$dec_cur = new oa_dec_cur_conv();
$format_date = new format_date();


$currentPage = $this->currentPage;
$numToDisplay = $this->numToDisplay;

?>
<div class="navlink">
<a href="#" onclick="open_url_to_home('<?php echo $this->basePath; ?>/home/index/depan','<?php echo $this->basePath; ?>/home/index/main');">Halaman Utama</a>
>>  Laporan Pasien
</div>
<div class="panel">
	<div class="inner">
		<span class="corners-top"><span></span></span>
		<h2 class="title">LAPORAN PASIEN</h2>
			<form method="post" id="frmcarianalisispasien" name="frmcarianalisispasien">
<table width="100%" border="0" cellpadding="0" cellspacing="1" class="std">
	<tr>
	<td align="left" width="180"> Periode Tanggal :</td>
	<td>
	<input type="text" id="t_awal" name="t_awal" value="<? echo $this->t_awal; ?>" />
	s/d 
	<input type="text" id="t_akhir" name="t_akhir" value="<? echo $this->t_akhir; ?>" />
	<?
	$atribSubmit = array("onclick"=>"javascript:carianalisispasien();");
	echo $ctrlFrm->formSubmit('cari', 'Search', $atribSubmit)."&nbsp;";
	?>
	</td>
	</tr>
</table>
				
	</form>
<fieldset class="fields"> 
<? 
$status = $this->hasil;
$proses = $this->proses;
$pesan->show_message($proses, $k_analisispasien, "$status" ); 
?>
<div onClick="cetakrekap('<? echo $this->t_awal; ?>','<? echo $this->t_akhir; ?>');" class="pdf" title="Rekap Data"></div>

<table id="sorter" class="sortable" cellspacing="1" cellpadding="2" border="0" align="center">
				<th >No</th>
				<th >Tanggal</th> 
				<th >Jumlah Pasien</th> 
				<th colspan="2" class="nosort">FUNGSI</th>
				
				<?
				if (count($this->analisispasienList) == 0){ 
				?>
					<tr class="event2"><td colspan="5"><font color="red">Data Tidak Ditemukan</font></td></tr>
				<?} else {
						
						
						foreach ($this->analisispasienList as $key => $val): 
						if ($key%2==0) { ?>
							<tr class="event">
						<? } else if ($key%2==1) { ?>
							<tr class="event2">
						<? } 
						$id		= $this->escape($val['id']); 
						$jum_pasien	= $this->escape($val['jum_pasien']); 
						$d_medrec	= $this->escape($val['d_medrec']);
						
						$noUrut = (($currentPage -1)* $numToDisplay) + $key +1;
						echo $ctrlFrm->formHidden('id', $id, null);
						
						?>
<td align="center"><? echo $noUrut;?></td>
<td class="clcenter"><? echo $format_date->convertTglMachineToHuman($d_medrec);?></td>
<td align="center"><? echo $jum_pasien;?></td>
<td><div onClick="analisispasienForm('update','<? echo $d_medrec;?>');" class="edit" title="Ubah Data"></div></td>
<td><div onClick="cetak('<? echo $d_medrec;?>');" class="pdf" title="Cetak Data"></div>
						</td>
						
					
						</tr>
					<?
					endforeach;
				}
				?>
			</table>

			<?	
			$totalData = $this->totAnalisispasienList;
			$modul = $this->basePath."/pasien/analisispasien/analisispasienlist";
			$param1 = $this->t_awal;$param2 = $this->t_akhir;$param3 = $this->bulan;$param4 = $this->jenis;$param5 = $this->status;
			echo $halaman->showPage($totalData, $numToDisplay, $currentPage, 'tableview', $modul, $param1, $param2, $param3, $param4);		
			
			?>
		</fieldset>		 
		
		<span class="corners-bottom"><span></span></span>
	</div>
</div>
<script type="text/javascript">
var sorter=new table.sorter("sorter");
sorter.init("sorter",0);

$(function() {
		$("#t_awal").datepicker();
		$("#t_akhir").datepicker();
	});

</script>