<?php 
	require_once 'share/format_page.php';
	$halaman = new format_page();
        require_once "share/share_message.php";
	$pesan = new share_message();
	$ctrlFrm = new Zend_View(); 
	$currentPage = $this->currentPage;
	$numToDisplay = $this->numToDisplay;
?>
<div class="contentdata"  ><!--start contentdata-->
			<div class="ct-welcome">
			<div class="hd">Pendaftaran</div>		   
			<div class="bd">
<div style="padding-top:10px;">
<form method="post" id="frmtambahrekanan" name="frmtambahrekanan">
<?
$status = $this->hasil;
$proses = $this->proses;
$keterangan = $this->keterangan;
$pesan->show_message($proses, $keterangan, $status ); 
?>

<TABLE>
<TR>
	<TD>email</TD>
	<TD>:</TD>
	<TD><input type="text" name="userid" id="userid" value ="" size="55" maxlength="50" ></TD>
</TR>
<TR>
	<TD>Pertanyaan Rahasia</TD>
	<TD>:</TD>
	<TD><?
								$idx_pilihanList['-'] = '--Pilih--';
								$jmlidx_pilihanList = count($this->pertanyaanList);
								for ($i = 0; $i < $jmlidx_pilihanList; $i++) {
									$idx_pilihanList[$this->pertanyaanList[$i]-> id] = (string)$this->pertanyaanList[$i]->n_pertanyaan;			 
								}
								$idx_pilihanAtrib = array("id"=>"pertanyaan", "tabindex"=>"17" );
								echo $ctrlFrm->formSelect("pertanyaan", trim($idx_pilihan), $idx_pilihanAtrib, $idx_pilihanList);
							?></TD>
</TR>
<TR>
	<TD>Jawaban Rahasia</TD>
	<TD>:</TD>
	<TD><input type="text" name="jawab" id="jawab" value ="" size="55" maxlength="50"></TD>
</TR>
</TABLE>


		 
		
		<?
	         $atribSubmit = array("onclick"=>"javascript:daftarrekanan();");
	         echo $ctrlFrm->formSubmit('cari', 'Daftar', $atribSubmit)."&nbsp;";
		?>
	</form>
		
	
<script type="text/javascript">
	var sorter = new table.sorter("sorter");
	sorter.init("sorter",0);
</script>
</div>
</div>
			<div class="ft"></div>
			</div>
		</div><!--end contentdata-->