<? require("header.phtml");
require_once 'Zend/View.php';
$ctrlFrm = new Zend_View();
require_once 'share/Portalconf.php'; 
require_once "share/share_message.php";
$pesan = new share_message();

?>
<body>

<div id="halutama">
<div id="container"><!--start container-->  
<? 

//require("menu_info.phtml");

?>

		<div id="header" class="clear">
        
		</div>

<a name="top"></a>
<?require("msg_login_home.phtml");?><?//require("runningtext.phtml");?>
		<?//require("msg_login_home.phtml");?>	
		
		<div id="content" class="clearfix">
			<div id="main">
				<div id="tableview">
				<!--div class="navlink">Halaman Utama</div><span id="breadcrumbs"></span-->
					<div class="leftbox"  id="leftbox"><!--start leftmenu-->

<!--div class="ct-menu">
<div class="hd"></div>
<div class="bd">
Medical Record
</div>
<div class="ft"></div>		   
</div--> 


<div id="featureBalloonPos">
<div id="featureBalloonTop"></div>
<div id="featureBalloonContent"></div>
</div>


						<div class="ct-menu">
							<div class="hd">Login</div>
								<div class="bd">

	<?
	/*$status = $this->hasil;
	$proses = $this->proses;
	$keterangan = $this->keterangan;
	$pesan->show_message($proses, $keterangan, "$status" ); 
	*/?>

	
	
									<?// if ($this->pesanKesalahan) {?> 
		<!--p class="message"><font color="red"><font size="3"><b><? //echo $this->pesanKesalahan;?><b><br /></font></font></p-->
	<?//}?>
	<form name="loginform" id="loginform" action="<? echo $this->basePath;?>/home/index/main" method="post">
			<p>
				<label>Nama Pengguna<br />
				<input type="text" name="log" id="user_login" class="input" value="" size="40" maxlength="40" tabindex="10" /></label>
			</p>
			<p>
				<label>Kata Sandi<br />
				<input type="password" name="pwd" id="user_pass" class="input" value="" size="30" maxlength="30" tabindex="20" /></label>
			</p>
		
		<p class="submit">
				<input type="submit" name="submit" id="submit" value="Login" tabindex="100" /> &nbsp;&nbsp;&nbsp;&nbsp;<a href="#" onclick="lupa();">Lupa Password?</a>
			
		</p>
	</form>
								</div>
								
						       <div class="ft"></div>		   
					       </div> 
				               <div id="featureBalloonPos">
					           <div id="featureBalloonTop"></div>
					           <div id="featureBalloonContent"></div>
				               </div>
					      

<!--div class="ct-menu">
<div class="hd">Daftar Judul Penelitian</div>
<div class="bd">
<?
foreach ($this->penelitianList as $key => $val):
	$n_judul = $this->escape($val['n_judul']); 
	$n_peneliti_u = $this->escape($val['n_peneliti_u']);
	$judul = $n_judul."<br>".$n_peneliti_u."<br>"; 
?>
<div>-<?echo $judul;?></div>
<?endforeach;
?>

</div>
<div class="ft"></div>		   
</div> 
<div id="featureBalloonPos">
<div id="featureBalloonTop"></div>
<div id="featureBalloonContent"></div>
</div-->


<!--div class="ct-menu">
<div class="hd">Link</div>
<div class="bd">
<a href="#" onclick="open_persyaratan();">Detik</a><BR>
</div>
<div class="ft"></div>		   
</div> 
<div id="featureBalloonPos">
<div id="featureBalloonTop"></div>
<div id="featureBalloonContent"></div>
</div-->



<script type="text/javascript">
//<![CDATA[
//IE PNG bug workarround

if(navigator.userAgent.toLowerCase().indexOf("msie")>0 && navigator.userAgent.toLowerCase().indexOf("msie 7.0")<=0){
	var imgArr = Array();
	imgArr[imgArr.length] = document.getElementById("featureBalloonTop");
	//imgArr[imgArr.length] = document.getElementById("featureBalloonLeft");
	imgArr[imgArr.length] = document.getElementById("featureBalloonContent");
	for(i=0;i<imgArr.length;i++)	{
		if(imgArr[i].currentStyle.backgroundImage.lastIndexOf(".png") != -1){
			var img = imgArr[i].currentStyle.backgroundImage.substring(5,imgArr[i].currentStyle.backgroundImage.length-2);
			//alert(img);
			imgArr[i].style.filter = "progid:DXImageTransform.Microsoft.AlphaImageLoader(src='"+img+"', sizingMethod='scale')";
			imgArr[i].style.backgroundImage = "url(images/spacer.gif)";
		}
	}
}
ACEventArr = Array();
function Event(id, text, description, url) {
	this.id		= id;
	this.text	= text;
	this.description = description;
	this.url	= '';//url;
}

<?
  $sFile = file("../etc/data/event.txt");
  $s=sizeof($sFile);
    if ($s > 0) {
	while (list($c,$line) = each($sFile)) {
		list($TGL,$EVENT) = explode(";;",$line);
		$TGLID=ereg_replace("/","",$TGL);
		$MONTHARRAY = array('Januari','Februari','Maret','April','Mei','Juni','July','Agustus','September','Oktober','November','Desember');
		list($DAY,$MONTH,$YEAR) = explode("/",$TGL);
		
?>		
				   //<![CDATA[
				   ACEventArr[ACEventArr.length] = new Event("<?=$TGLID;?>","<?=$DAY." ".$MONTHARRAY[$MONTH-1]." ".$YEAR;?>","<?=$EVENT;?>");
				   //]]>
<?
	}	
   }
?>
function balloonText(featureId, aObj, e) {
	var posObj = document.getElementById("featureBalloonPos");
	var conObj = document.getElementById("featureBalloonContent");
	var accUrl = "";
	var accDesc = "";
	var accText = "";
	var lc = "id".toLowerCase();
	
	for(i = 0; i < ACEventArr.length; i++){
		if(ACEventArr[i].id == featureId){
			accDesc = ACEventArr[i].description;
			accText = ACEventArr[i].text;
			accUrl	= ACEventArr[i].url
			break;
		}
	}
	
	if(accUrl != ''){
		accDesc += "<br /><a href='spg.jsp?cc=id&amp;lc=id&amp;ver=4000&template=" + accUrl + "&zone=pp&lm=pp2&fid=" + featureId + "' class='link'><img  src='popup_files/CWS31AFW_9382high_56_0_4000.gif' border='0' alt='' />Baca selengkapnya</a>";
	}
	
	tmpObj = aObj;
	if (lc == 'he' || lc == 'ar' ){
		aObj.style.display = "block";
		aObj.style.width = "120px";
	}
	var curleft = 0;
	var curtop = 0;
	if (tmpObj.offsetParent){
		while (tmpObj.offsetParent)	{
			curtop += tmpObj.offsetTop;
			curleft += tmpObj.offsetLeft;
			tmpObj = tmpObj.offsetParent;
		}
	}
	else if (tmpObj.x){
		curtop += tmpObj.y;
		curleft += tmpObj.x;
	}
	
	
	posObj.style.display = "block";
	posObj.style.position = "absolute";
	//posObj.style.width = "200px";
	
	if (lc == 'he' || lc == 'ar' ){
		posObj.style.left = (curleft-20) + "px";
	}
	else {
		posObj.style.left = (curleft+20) + "px";
	}
	
	posObj.style.top = (curtop) + "px";

	//headObj.innerHTML = accText;
	conObj.innerHTML = '<b>'+accText+'</b><br />'+accDesc+'<br /><br /><a href="javascript:closeBalloonText();void(0);" class="arrow" style="position:relative ">Tutup jendela</a>';
	
	//IE bug workarround, stop for 350 milisecs, otherwise images are not shown.
	if(navigator.userAgent.toLowerCase().indexOf("msie")>0){
		d = new Date() //today's date
		while (1){
			mill=new Date() // Date Now
			diff = mill-d //difference in milliseconds
			if( diff > 350 ){
				break;
			}
		}
	}
}

function closeBalloonText() {
	document.getElementById("featureBalloonPos").style.display = "none";
}


//]]>



</script>


					<div class="ct-menu">
				        <div class="hd">Kalender </div>
						<div class="bd">
					<?
						$todayd=date("d",time())*1;
						$todaym=date("m",time())*1;
						$todayy=date("Y",time());
						$today="$todayd/$todaym/$todayy";
						echo "<DIV class=\"contentModule\" id='MYCAL'></DIV>\n";
						$sFile = file($this->baseData."/event.txt");
						$sFile2 = file($this->baseData."/event2.txt");
						$s=sizeof($sFile);
						$n=$s-1;
						$s2=sizeof($sFile2);
						$n2=$s2-1;
						echo "<script>\n";
						echo "var datedarray=new Array(";
						if ($s > 0) {
						while (list($c,$line) = each($sFile)) {
							list($TGL,$EVENT) = explode(";;",$line);
							if ($c==$n)  echo "'$TGL'";
							 else    echo "'$TGL', ";
							
						}	
						}
						echo ")\n";
						echo "var datedarray2=new Array(";
						if ($s2 > 0) {
						while (list($c2,$line2) = each($sFile2)) {
							list($TGL2,$EVENT2) = explode(";;",$line2);
							if ($c2==$n2)  echo "'$TGL2'";
							 else    echo "'$TGL2', ";
							
						}	
						}
						echo ")\n";
						?>							
						var today="<?=$today?>";
						</script>

						<script type="text/javascript" src="<?echo $this->basepath; ?>/js/kalender.js"></script>
						</div>
					<div class="ft"></div>
				</div>

			</div>

	

	   <div id="daftar_rekanan"></div> 
		<div class="contentdata"  ><!--start contentdata-->
			<div class="ct-welcome">
			<div class="hd">
			Selamat Datang di Sistem Informasi Monografi Kelurahan</div>		   
			<div class="bd">
				<div id='dialog-cari-sab'>
					<!--form method="post" id="frmCariPenelitian" name="frmCariPenelitian">
					Judul :
					<input type="text" name="cariiSb" id="cariiSb" value ="<? echo $this->carii;?>" size="70" maxlength="70" >
					<?
						$atribSubmit = array("onclick"=>"javascript:cariPenelitian();");
						echo $ctrlFrm->formSubmit('cari', 'Search', $atribSubmit)."&nbsp;";
					?>
					</form-->
				Aplikasi ini dibuat untuk monografi kelurahan
				<div id="table-standar-belanja"></div>
				</div>

			</div>
			<div class="ft"></div>
			</div>
		</div><!--end contentdata-->

		


	  </div><!--end tableview-->
		  
        					
</div>
</div>

</div><!-- end container -->
     <div id="footer" class="clear"><!--start footer-->
     <div class="copyright">MONOGRAFI KELURAHAN <?php echo date('Y')?></div>
     </div><!-- end footer --> 
</div>	

</body>
</html>		
	
<script type="text/javascript">
function lupa()
{
	var url = '<?php echo $this->basePath; ?>/home/index/lupapassword';
	var param = { };
	jQuery.get(url, param, function(data) {
		jQuery("div#daftar_rekanan").html(data);
		jQuery("#frmlupapassword").ajaxForm(lupapassword_opt);
	});
	
}
var lupapassword_opt = {
	target : '#daftar_rekanan',
	url: '<?php echo $this->basePath; ?>/home/index/lupa',
	beforeSubmit : function() {
		if (document.getElementById('userid').value == ''){
			alert('User harus Diisi');
			return false;
		}
	},
	//success: function(){doCount(5);},
	type: 'post', 
	resetForm: false
};
function masukanFormx()
{
	var url = '<?php echo $this->basePath; ?>/home/index/daftarrekanan';
	var param = { };
	jQuery.get(url, param, function(data) {
		jQuery("div#daftar_rekanan").html(data);
		jQuery("#frmtambahrekanan").ajaxForm(tambahrekanan_opt);
	});
	
}
function daftarrekanan()
{
	$("#frmtambahrekanan").ajaxForm(tambahrekanan_opt);

	/*var url = '<?php echo $this->basePath; ?>/home/index/daftarrekanan';
	var param = { };
	
	jQuery.get(url, param, function(data) {
		jQuery("div#daftar_rekanan").html(data);
		jQuery("#frmtambahrekanan").ajaxForm(tambahrekanan_opt);
	});*/
	
}
var tambahrekanan_opt = {
	target : '#daftar_rekanan',
	url: '<?php echo $this->basePath; ?>/home/index/daftar',
	beforeSubmit : function() {
		if (document.getElementById('userid').value == ''){
			alert('User harus Diisi');
			return false;
		}
	},
	success: function(){
		//location.href="#tabs-1";
		//doCounter(5);
		jQuery("#frmtambahrekanan").ajaxForm(tambahrekanan_opt);
	},
	//success: function(){alert("OK");},

	type: 'post', 
	resetForm: false
};
function cariPenelitian()
{
		$("#frmCariPenelitian").ajaxForm(frmcaripenelitian_opt);
	
}
var frmcaripenelitian_opt = {
		target : '#table-standar-belanja',//daftarpenelitian
		url: '<?php echo $this->basePath; ?>/home/index/daftarpenelitian',
		type: 'post', 
		resetForm: false
};
</script>	
	
