			<div style="text-align: center;">
				<form name="loginform" id="loginform" action="<? echo $this->basePath;?>/home/index/main" method="post">
				<h3 class="title">LOGIN <?=$this->par?></h3>
				<table cellspacing="3" cellpadding="3" border="0" style="margin: 0pt auto;">
				<tbody>
					<tr>
						<td align="left" width="35%">
							User Id
						</td>
						<td align="left" width="5%">
							:
						</td>						
						<td align="left" width="60%">
							<input type="text" name="log" id="user_login" class="input" value="<?=$this->log?>" size="15" tabindex="10" />
							<input type="hidden" name="par" id="par" class="input" value="<?=$this->par?>" size="20" tabindex="10" />
							<input type="hidden" name="usergroup" id="usergroup" class="input" value="<?=$this->usergroup?>" size="20" tabindex="10" />
						</td>
					</tr>
					<tr>
						<td align="left">
							Kata Sandi
						</td>
						<td align="left">
							:
						</td>							
						<td align="left">
							<input type="password" name="pwd" id="user_pass" class="input" value="<?=$this->pwd?>" size="15" tabindex="20" /></label>
						</td>
					</tr>
					<tr align="right">
						<td align="left">
						&nbsp;
						</td>
						<td align="left">
						&nbsp;
						</td>						
						<td>
							<input id="Login" class="button2" type="submit" value="Login"/>&nbsp;
							<input id="Login" class="button2" type="button" onclick="open_url_to_divindex ('<?php echo $this->basePath; ?>/home/index/login2?par=<?=$this->par?>')" value="Cancel"/>
						</td>
					</tr>
				</tbody>
				</table>
											<?
							if ($paswd=="kosong"){
								echo "Userid atau Password harus diisi";
							}
							if ($paswd=="salah"){
								echo "Nama Pengguna atau Kata Sandi Salah atau menu aplikasi ini bukan autorisasi anda";
							}							
							?>
				</form>
			</div>
