<h2 class="accessibility">Navigation</h2><!--start nav-->
<div class="menuback">
<ul id="menu" class="menu">
	<!--<li>
		<a title=USER href="#" class=menulink ><span>User</span></a>
		<ul>
			<li><a href="#" onclick="open_url_to_div('<?php echo $this->basePath; ?>/pasien/pengguna/penggunalist?','<?php echo $this->basePath; ?>/pasien/pengguna/penggunajs');">User Pengguna</a></li>
		</ul>
	</li>

	<li>
	<a title=group_user href="#" class=menulink onclick="open_url_to_div('<?php echo $this->basePath; ?>/adm/groupuser/groupuserlist?','<?php echo $this->basePath; ?>/adm/groupuser/groupuserjs');"><span>Group User</span></a>
	</li>
		-->

	<li>
	<a title=pendaftaran href="#" class=menulink onclick="open_url_to_div('<?php echo $this->basePath; ?>/kelurahan/pendaftaran/pendaftaranlist?','<?php echo $this->basePath; ?>/kelurahan/pendaftaran/pendaftaranjs');"><span>Monografi Kelurahan</span></a>
	</li>

	<li>
	<a title=pendaftaran href="#" class=menulink onclick="open_url_to_div('<?php echo $this->basePath; ?>/pasien/analisispasien/analisispasienlist?','<?php echo $this->basePath; ?>/pasien/analisispasien/analisispasienjs');"><span>Laporan Monografi Kelurahan</span></a>
	</li>

	



 </ul>
 </div>

<script type="text/javascript">tabdropdown.init("colortab", "auto")</script> 

<script type="text/javascript">
var menu = new menu.dd("menu");
menu.init("menu","menuhover");

</script>
<!--end nav-->



	