    <div class="desc"><!--start msg-->
      <div class="crdate"><span id="servertime"></span> | <span class="username"><?echo $this->nama;?><?echo $this->n_mhs;?></span> (<a href="http://<? echo $_SERVER['SERVER_NAME'];?>" title="Logout">Logout</a>) | <a href="#" onclick="open_url_to_div('<?php echo $this->basePath; ?>/adm/user/gantikatasandi?userid=<?echo $this->id;?>','<?php echo $this->basePath; ?>/adm/user/gantikatasandijs');">Ganti Password</a>|</div>
    </div><!--end msg-->
