<div id="screen-meta">
	<div id="contextual-help-wrap" style="display:none">
	<h4>Notifikasi</h4>
	<div class="metabox-prefs">
		
		<ul class="lsb">
		   <li>Ada <a href="" class="bold">3 buah surat</a> yang belum ditangani dan sudah melewati waktu tanggap</li>
		   <li>Ada <a href="" class="bold">1 buah surat keluar yang belum diverifikasi</a> dan untuk segera  diverifikasi</li>
		   <li>Anda belum memasukkan <a href="" class="bold">laporan bulanan</a> untuk bidang Anda</li>
		   <li>Ada <a href="" class="bold">pengajuan anggota tim</a> yang harus Anda proses</li>
	    </ul>
	
	
</div>
</div>

<div id="screen-meta-links">
<div id="contextual-help-link-wrap" class="hide-if-no-js screen-meta-toggle">
<a href="#contextual-help" id="contextual-help-link" class="show-settings">Notifikasi</a>

</div>

</div>
</div>
