function carigoldarah()
{
	$("#frmcarigoldarah").ajaxForm(frmcarigoldarah_opt);
}
var frmcarigoldarah_opt = {
		target : '#tableview',
		url: '<?php echo $this->basePath; ?>/adm/goldarah/goldarahlist',
		type: 'post', 
		resetForm: false
};
function goldarahlist()
{
	kategoriCari = document.getElementById('kategoriCari').value;
	carii = document.getElementById('carii').value;
	var param = {kategoriCari:kategoriCari,carii:carii};
	
	var url = '<?php echo $this->basePath; ?>/adm/goldarah/goldarahlist';
	jQuery.get(url, param, function(data) {
		$("div#tableview").html(data);
	});
}

function goldarahForm(jenisForm, id_goldar)
{
	kategoriCari = document.getElementById('kategoriCari').value;
	carii = document.getElementById('carii').value;
	var url = '<?php echo $this->basePath; ?>/adm/goldarah/goldarahdata';
	var param = { jenisForm:jenisForm, id_goldar:id_goldar,kategoriCari:kategoriCari,carii:carii};
	jQuery.get(url, param, function(data) {
		jQuery("div#tableview").html(data);
		jQuery("#frmtambahgoldarah").ajaxForm(tambahGoldarah_opt);
		jQuery("#frmubahgoldarah").ajaxForm(ubahGoldarah_opt);
	});
}

var tambahGoldarah_opt = {
	target : '#tableview',
	url: '<?php echo $this->basePath; ?>/adm/goldarah/goldarah',
	beforeSubmit : function() {
		
		if (document.getElementById('n_goldar').value == ''){
			alert('Golongan Darah harus Diisi');
			return false;
		}

	answer = confirm('\n\   Apakah data yang anda masukan adalah benar.\n\n   \'OK\' Jika setuju, \'Cancel\' Jika tidak setuju.');
		if(answer !=0) { 
			return true;
		}
		else{
			return false;
		}
		
	},
	success: function(){doCount(5);},
	type: 'post', 
	resetForm: false
};

var ubahGoldarah_opt = {
	target : '#tableview',
	url: '<?php echo $this->basePath; ?>/adm/goldarah/goldarahupdate',
	beforeSubmit : function() {
		
		if (document.getElementById('n_goldar').value == ''){
			alert('Golongan Darah harus Diisi');
			return false;
		}
	answer = confirm('\n\   Apakah data yang anda masukan adalah benar.\n\n   \'OK\' Jika setuju, \'Cancel\' Jika tidak setuju.');
		if(answer !=0) { 
			return true;
		}
		else{
			return false;
		}
		
	},
	success: function(){doCount(5);},
	type: 'post', 
	resetForm: false
};

function goldarahHapus(param1, nama, param2)
{ 
	
	if(ConfirmDelete(param1,nama))
	{	
		handler = '<?php echo $this->basePath; ?>/adm/goldarah/goldarahhapus';
		var opt = {id_goldar : param2};
		jQuery.get(handler,opt,function(data) {
				$("#tableview").html(data);
				doCount(5);
			 });
	}
}

function BukaWindows(){
	var w = 0; 
	var h = 0;
	w = screen.availWidth;
	h = screen.availHeight;
	var popW = 800, popH = 600;
	var leftc = (w-popW)/2;
	var topc = (h-popH)/2;
	var selectWindow = window.open(url,'Selection', 'left=' + leftc + ',top=' + topc + ', width='+popW+',height='+popH+',resizable=0,scrollbars=yes');
}

