<?
require_once 'Zend/View.php';
require_once 'share/format_date.php'; 
require_once 'share/format_page.php';
require_once "share/share_message.php";
require_once "share/oa_dec_cur_conv.php";

$ctrlFrm = new Zend_View();
$pesan = new share_message();
$halaman = new format_page();
$dec_cur = new oa_dec_cur_conv();
$format_date = new format_date();

$currentPage = $this->currentPage;
$numToDisplay = $this->numToDisplay;
?>
<div class="navlink">
<a href="#" onclick="open_url_to_home('<?php echo $this->basePath; ?>/home/index/depan','<?php echo $this->basePath; ?>/home/index/main');">Halaman Utama</a>
>> Data Pasien
</div>

<div id="dialog-browse">  
</div>

<div class="panel">
	<div class="inner">
		<span class="corners-top"><span></span></span>
		<h2 class="title">FORM DATA PASIEN</h2>
	    <div class="spacer"></div> 
		
		<? if(strtolower($this->jenisForm) == 'insert') {$namaForm = 'frmtambahpendaftaran'; }
			else if (strtolower($this->jenisForm) == 'update') {$namaForm = 'frmubahpendaftaran'; }
			else {$namaForm = 'frmhapuspendaftaran'; }
		?>

		<form method="post" name="<? echo $namaForm;?>" id="<? echo $namaForm;?>">
<?
	$status = $this->hasil;
	$proses = $this->proses;
	$keterangan = $this->keterangan;
	$pesan->show_message($proses, $keterangan, "$status" ); 
?>
			<table width="100%" border="0" cellpadding="0" cellspacing="1" class="std">
<input name="id" id="id" type="hidden" value="<?echo $this->id;?>" />
<input name="kategoriCari" id="kategoriCari" type="hidden" value="<?echo $this->kategoriCari;?>" />
<input name="carii" id="carii" type="hidden" value="<?echo $this->carii;?>" />
<input name="id_user" id="id_user" type="hidden" value="<?echo $this->detailPendaftaran['id_user'];?>" />

				<tr>
				    <td align="right" width="180">* Nama :</td>
					<td>	
	<? 
	$n_namaAttrib = array("id"=>"n_nama","size" => 103,"maxlength" => 100 );
	echo $ctrlFrm->formText("n_nama", $this->detailPendaftaran['n_nama'], $n_namaAttrib);
	?>
				</td>
				</tr>

				<tr>
				    <td align="right" width="180">* Jenis Kelamin :</td>
					<td>
	<?
	$genderList['-'] = '--Pilih--';
	$genderList['L'] = 'Laki-Laki';
	$genderList['P'] = 'Perempuan';
	$jenis_pendAtrib = array("id"=>"gender", "tabindex"=>"17");
	echo $ctrlFrm->formSelect('gender', trim($this->detailPendaftaran['gender']), $genderAtrib, $genderList);
	?>
					</td>
				</tr>

				<tr>
				    <td align="right" width="180">* Tempat/Tgl Lahir :</td>
					<td>
	<? 
	$t_lahirAttrib = array("id"=>"t_lahir","size" => 22,"maxlength" => 20 );
	echo $ctrlFrm->formText("t_lahir", $this->detailPendaftaran['t_lahir'], $t_lahirAttrib);
	?>/<input name="d_lahir" id="d_lahir" type="text" value="<?echo $format_date->convertTglMachineToHuman($this->detailPendaftaran['d_lahir']);?>" />

					</td>
				</tr>

	<tr>
	<td align="left" width="180">* Alamat :</td>
	<td>
	<? 
		$n_alamatAttrib = array("id" =>"n_alamat" ,"rows" => 1,"cols" => 2);
		echo $ctrlFrm->formTextArea('n_alamat', $this->detailPendaftaran['n_alamat'], $n_alamatAttrib);
	?>	
	</td>
	</tr>

				<tr>
				    <td align="right" width="180"> Pekerjaan :</td>
					<td>	
	<? 
	$n_pekerjaanAttrib = array("id"=>"n_pekerjaan","size" => 53,"maxlength" => 50 );
	echo $ctrlFrm->formText("n_pekerjaan", $this->detailPendaftaran['n_pekerjaan'], $n_pekerjaanAttrib);
	?>
				</td>
				</tr>
	
	<tr>
				    <td align="right" width="180">* Nomor Pasien :</td>
					<td>	
	<? 
	$kode_pasienAttrib = array("id"=>"kode_pasien","size" => 13,"maxlength" => 13 );
	echo $ctrlFrm->formText("kode_pasien", $this->detailPendaftaran['kode_pasien'], $kode_pasienAttrib);
	?>
				</td>
				</tr>

				

	<tr>
	<td align="right" width="180"> Golongan Darah :</td>
	<td>
	<?
	$goldarList['0'] = '--Pilih--';
	$jmlgoldarList = count($this->goldarList);
		for ($i = 0; $i < $jmlgoldarList; $i++) {
		$goldarList[$this->goldarList[$i]->id_goldar] = (string)$this->goldarList[$i]->n_goldar;			 
		}
	
	$goldarAtrib = array("id"=>"c_goldar", "tabindex"=>"17");
	echo $ctrlFrm->formSelect('c_goldar', trim($this->detailPendaftaran['c_goldar']), $goldarAtrib, $goldarList);
	?>
	</td>
	</tr>

	<!--tr>
	<td align="right" width="180">* Propinsi :</td>
	<td>
	<?
	$propinsiList['0'] = '--Pilih--';
	$jmlpropinsiList = count($this->propinsiList);
		for ($i = 0; $i < $jmlpropinsiList; $i++) {
		$propinsiList[$this->propinsiList[$i]->id_prop] = (string)$this->propinsiList[$i]->n_prop;			 
		}
	$propinsiAtrib = array("id"=>"c_propinsi", "tabindex"=>"17","onchange"=>"javascript:getKab();");
	echo $ctrlFrm->formSelect('c_propinsi', trim($this->detailPendaftaran['c_propinsi']), $propinsiAtrib, $propinsiList);
	?>
	</td>
	</tr>
				
	<tr>
	<td align="right" width="180">* Kota/Kabupaten :</td>
	<td>
					<?
					$kabList['0'] = '--Pilih--';
					$jmlkabList = count($this->kabList);
					for ($i = 0; $i < $jmlkabList; $i++) {
					$kabList[$this->kabList[$i]->id_kab] = (string)$this->kabList[$i]->n_kab;			 
					}
					$kabAtrib = array("id"=>"c_kota", "tabindex"=>"17");
					echo $ctrlFrm->formSelect('c_kota', trim($this->detailPendaftaran['n_kota']), $kabAtrib, $kabList);
					?>
	</td>
	</tr>

	<tr>
	<td align="right" width="180">* Agama :</td>
	<td>
	<?
	$agamaList['0'] = '--Pilih--';
	$jmlagamaList = count($this->agamaList);
		for ($i = 0; $i < $jmlagamaList; $i++) {
		$agamaList[$this->agamaList[$i]->id_agama] = (string)$this->agamaList[$i]->n_agama;			 
		}
	$agamaAtrib = array("id"=>"c_agama", "tabindex"=>"17");
	echo $ctrlFrm->formSelect('c_agama', trim($this->detailPendaftaran['c_agama']), $agamaAtrib, $agamaList);
	?>
	</td>
	</tr-->

	<tr>
	<td align="right" width="180"> Status :</td>
	<td>
	<?
	$statusList['0'] = '--Pilih--';
	$jmlstatusList = count($this->statusList);
		for ($i = 0; $i < $jmlstatusList; $i++) {
		$statusList[$this->statusList[$i]->id_status] = (string)$this->statusList[$i]->n_status;			 
		}
	
	$statusAtrib = array("id"=>"c_marital", "tabindex"=>"17");
	echo $ctrlFrm->formSelect('c_marital', trim($this->detailPendaftaran['c_marital']), $statusAtrib, $statusList);
	?>
	</td>
	</tr>

				<tr>
				    <td align="right" width="180">* Telp/HP :</td>
					<td>
	<? 
	$n_phoneAttrib = array("id"=>"n_phone","size" => 30,"maxlength" => 30);
	echo $ctrlFrm->formText("n_phone", $this->detailPendaftaran['n_phone'], $n_phoneAttrib);
	?>/
	<? 
	$n_hpAttrib = array("id"=>"n_hp","size" => 30,"maxlength" => 30);
	echo $ctrlFrm->formText("n_hp", $this->detailPendaftaran['n_hp'], $n_hpAttrib);
	?>
					</td>
				</tr>

				<tr>
				    <td align="right" width="180"> Email :</td>
					<td>
	<? 
	$n_emailAttrib = array("id"=>"n_email","size" => 52,"maxlength" => 50 );
	echo $ctrlFrm->formText("n_email", $this->detailPendaftaran['n_email'], $n_emailAttrib);
	?>
					</td>
				</tr>

				<!--tr>
				    <td align="right" width="180">* Berat Badan :</td>
					<td>
	<? 
	$b_badanAttrib = array("id"=>"b_badan","size" => 4,"maxlength" => 3 );
	echo $ctrlFrm->formText("b_badan", $this->detailPendaftaran['b_badan'], $b_badanAttrib);
	?> Kg
					</td>
				</tr>

				<tr>
				    <td align="right" width="180">* Tinggi Badan :</td>
					<td>
	<? 
	$t_badanAttrib = array("id"=>"t_badan","size" => 4,"maxlength" => 3 );
	echo $ctrlFrm->formText("t_badan", $this->detailPendaftaran['t_badan'], $t_badanAttrib);
	?> Cm
					</td>
				</tr-->

				
				
				
					
				<tr>
				    <td></td>
				    <td>
						<div class="right">
<input type="button" value="Batal" onclick="pendaftaranlist()"> 
<input type="reset" value="Ulangi"> 
<input   type="submit" value="Simpan">


						</div>
					</td>
				</tr>
				<tr>
				    <td>* Harus Diisi</td>
				    <td></td>
				</tr>
			</table>
		</form>
	</div>
</div>

<script>

 	$(function() {
		$("#d_lahir").datepicker();
	});


function showDialog(val,jum) {      
    $( "#dialog-browse" ).dialog({
      autoOpen: false,
      height: 380,
      width: 640,
      modal: true,
      resizable:false,
      title: "Data"
    });
    if(val =='dosen'){dosenlist(jum);}  
    if(val =='prodi'){prodilist();}  
    return false;
  }

</script>

