<?php 
require_once 'Zend/View.php';
require_once "share/tanggal.php";  
require_once 'share/Portalconf.php'; 

/*$vFoto = $this->basePath."../data/sdm/photo/".trim($this->i_peg_nip).".jpg";

	if (!file_exists($vFoto)) {
		$vFoto = $this->basePath."../images/nophoto.jpg";
	} 
*/
?>
<div class="widget">
	<h4 class="widgettitle">Konten</h4>
	<div class="content">		
		<h2 class="title"><?=$this->jdlagenda?></h2>
		<span class="date"><?=returnbulan($this->tglagenda)?></span><br>
		<span class="place">Tempat : <?=$this->tempat?></span><br>
		<?=$this->detilagenda?>
		<div class="hr"></div>
		<a class="all" href="#indexagenda" onclick="goExec_Script('<?php echo $this->basePath; ?>/portalmodule/agenda/indeksagenda','<?php echo $this->basePath; ?>/portalmodule/agenda/agendajs', 'Agenda')">Arsip Agenda</a>		
	</div>
</div>
