<?
require_once 'Zend/View.php';
require_once 'share/format_date.php'; 
require_once 'share/format_page.php';
require_once "share/share_message.php";
require_once "share/oa_dec_cur_conv.php";

$ctrlFrm = new Zend_View();
$pesan = new share_message();
$halaman = new format_page();
$dec_cur = new oa_dec_cur_conv();
$format_date = new format_date();


$currentPage = $this->currentPage;
$numToDisplay = $this->numToDisplay;

?>
<div class="navlink">
<a href="#" onclick="open_url_to_home('<?php echo $this->basePath; ?>/home/index/depan','<?php echo $this->basePath; ?>/home/index/main');">Halaman Utama</a>
>>  Data Rekam Pasien
</div>
<div class="panel">
	<div class="inner">
		<span class="corners-top"><span></span></span>
		<h2 class="title">Data Rekam Medik <? echo $this->detailPasien['n_nama'];?> , Kode Pasien <? echo $this->kode_pasien;?></h2>
			<form method="post" id="frmcarirekampasien" name="frmcarirekampasien">
		<input name="kode_pasien" id="kode_pasien" type="hidden" value="<?echo $this->kode_pasien;?>" />

				<table width="100%" border="0" cellpadding="0" cellspacing="1" class="std">
				</table>
<div class="add" title="Tambah Data" onClick="rekampasienForm('insert','');"></div>			
				Filter :
				<?
				$kategoriCari = array("n_nama" => "Nama", "t_badan" => "Alamat");
	echo $ctrlFrm->formSelect('kategoriCari', $this->kategoriCari, null, $kategoriCari);						
				?>
<input type="text" name="carii" id="carii" align="center" value ="<? echo $this->carii;?>">
				<?
			         $atribSubmit = array("onclick"=>"javascript:carirekampasien();");
			         echo $ctrlFrm->formSubmit('cari', 'Search', $atribSubmit)."&nbsp;";
				?>
	</form>
<fieldset class="fields"> 
<? 
$status = $this->hasil;
$proses = $this->proses;
$pesan->show_message($proses, $k_rekampasien, "$status" ); 
?>
<table id="sorter" class="sortable" cellspacing="1" cellpadding="2" border="0" align="center">
				<th >No</th>
				<th >Tanggal</th> 
				<th >Kode Pasien</th> 
				<th >Nama</th> 
				<th >Alasan</th> 
				<th >Tindakan</th> 
				<th >Terapi</th> 
				<th colspan="2" class="nosort">FUNGSI</th>
				
				<?
				if (count($this->rekampasienList) == 0){ 
				?>
					<tr class="event2"><td colspan="5"><font color="red">Data Tidak Ditemukan</font></td></tr>
				<?} else {
						
						
						foreach ($this->rekampasienList as $key => $val): 
						if ($key%2==0) { ?>
							<tr class="event">
						<? } else if ($key%2==1) { ?>
							<tr class="event2">
						<? } 
						$id		= $this->escape($val['id']); 
						$kode_pasien	= $this->escape($val['kode_pasien']); 
						$n_nama		= $this->escape($val['n_nama']);
						$d_medrec	= $this->escape($val['d_medrec']);
						$t_badan	= $this->escape($val['t_badan']);
						$b_badan	= $this->escape($val['b_badan']);
						$n_tensi	= $this->escape($val['n_tensi']);
						$n_diagnosis	= $this->escape($val['n_diagnosis']);
						$n_terapi	= $this->escape($val['n_terapi']);
						$n_klasifikasi	= $this->escape($val['n_klasifikasi']);
						$n_tindakan	= $this->escape($val['n_tindakan']);
						
						$noUrut = (($currentPage -1)* $numToDisplay) + $key +1;
						echo $ctrlFrm->formHidden('id', $id, null);
						
						?>
<td align="center"><? echo $noUrut;?></td>
<td class="clcenter"><? echo $format_date->convertTglMachineToHuman($d_medrec);?></td>
<td align="center"><? echo $kode_pasien;?></td>
<td class="clleft"><? echo $n_nama;?></td>
<td align="center"><? echo $n_klasifikasi;?></td>
<td align="center"><? echo $n_tindakan;?></td>
<td class="clleft"><? echo $n_terapi;?></td>

<td><div onClick="rekampasienForm('update','<? echo $id;?>');" class="edit" title="Ubah Data"></div></td>
<td><div onClick="rekampasienHapus('Data','<? echo $id;?>','<? echo $n_nama;?>');" class="delete" title="Hapus Data"></div>
						</td>
						
					
						</tr>
					<?
					endforeach;
				}
				?>
			</table>

			<?	
			$totalData = $this->totRekampasienList;
			$modul = $this->basePath."/pasien/rekampasien/rekampasienlist";
			$param1 = $this->cabang;$param2 = $this->tahun;$param3 = $this->bulan;$param4 = $this->jenis;$param5 = $this->status;
			echo $halaman->showPage($totalData, $numToDisplay, $currentPage, 'tableview', $modul, $param1, $param2, $param3, $param4);		
			
			?>
		</fieldset>		 
		
		<span class="corners-bottom"><span></span></span>
	</div>
</div>
<script type="text/javascript">
var sorter=new table.sorter("sorter");
sorter.init("sorter",0);
</script>