<?
require_once 'Zend/View.php';
require_once 'share/format_date.php'; 
require_once 'share/format_page.php';
require_once "share/share_message.php";
require_once "share/oa_dec_cur_conv.php";

$ctrlFrm = new Zend_View();
$pesan = new share_message();
$halaman = new format_page();
$dec_cur = new oa_dec_cur_conv();
$format_date = new format_date();

$currentPage = $this->currentPage;
$numToDisplay = $this->numToDisplay;
?>
<div class="navlink">
<a href="#" onclick="open_url_to_home('<?php echo $this->basePath; ?>/home/index/depan','<?php echo $this->basePath; ?>/home/index/main');">Halaman Utama</a>
>> Data Kelurahan
</div>

<div id="dialog-browse">  
</div>

<div class="panel">
	<div class="inner">
		<span class="corners-top"><span></span></span>
		
		
		<? if(strtolower($this->jenisForm) == 'insert') {$namaForm = 'frmtambahpendaftaran'; $nama='tambah';}
			else if (strtolower($this->jenisForm) == 'update') {$namaForm = 'frmubahpendaftaran'; $nama='ubah'; }
			else {$namaForm = 'frmhapuspendaftaran';  $nama='hapus';}
		?>
		
		<h2 class="title">FORM <?php echo strtoupper($nama)?> DATA KELURAHAN <strong><?php echo  strtoupper($this->detailPendaftaran['kelurahan']); ?></strong> </h2>
		
	    <div class="spacer"></div> 
		<form method="post" name="<? echo $namaForm;?>" id="<? echo $namaForm;?>" class="validasi">
<?
	$status = $this->hasil;
	$proses = $this->proses;
	$keterangan = $this->keterangan;
	$pesan->show_message($proses, $keterangan, "$status" ); 
?>
			<table width="100%" border="0" cellpadding="0" cellspacing="1" class="std">
<input name="kd_kel" id="kd_kel" type="hidden" value="<?echo $this->detailPendaftaran['kd_kel'];?>" />
<input name="kategoriCari" id="kategoriCari" type="hidden" value="<?echo $this->kategoriCari;?>" />
	<input name="carii" id="carii" type="hidden" value="<?echo $this->carii;?>" />
				
				
				<tr>
				    <td align="right" width="180">* KODE WILAYAH :</td>
					<td>	
						<? 
							$c_noregAttrib = array("size" => 50,"maxlength" => 50,"required"=>"requried");
							echo $ctrlFrm->formText("kode_wilayah", $this->detailPendaftaran['kode_wilayah'], $c_noregAttrib);
						?>
				</td>
				</tr>

				
				
				<tr>
				    <td align="right" width="180">* Nama Kelurahan :</td>
					<td>	
						<? 
							$n_namaAttrib = array("size" => 50,"maxlength" => 50,"required"=>"requried", "readonly"=>"readonly");
							echo $ctrlFrm->formText("kelurahan", $this->detailPendaftaran['kelurahan'], $n_namaAttrib);
						?>
				</td>
				</tr>

				<tr>
				    <td align="right" width="180">* Tahun Pembentukan :</td>
					<td>
						<? 
							$tahun_pembentukanAttrib = array("size" => 50,"maxlength" => 50,"required"=>"requried");
							echo $ctrlFrm->formText("tahun_pembentukan",trim($this->detailPendaftaran['tahun_pembentukan']), $tahun_pembentukanAttrib);
						?>
					</td>
				</tr>

				<tr>
				    <td align="right" width="180">* Dasar Hukum Pembentukan :</td>
					<td>	
						<? 
						$t_waktuAttrib = array("size" => 50,"maxlength" => 50,"required"=>"requried");
						echo $ctrlFrm->formText("dasar_pembentukan", $this->detailPendaftaran['dasar_pembentukan'], $t_waktuAttrib);
						?>
				</td>
				</tr>
				
				
				
				<tr>
				    <td align="right" width="180">* Nomor Kode Pos :</td>
					<td>	
	<? 
	$t_beratAttrib = array("size" => 50,"maxlength" => 50,"required"=>"requried");
	echo $ctrlFrm->formText("kode_pos", $this->detailPendaftaran['kode_pos'], $t_beratAttrib);
	?>
				</td>
				</tr>
				
				
				</td>
				</tr>

				<tr>
				    <td align="right" width="180">* Kecamatan :</td>
					<td>	
						<? 
						$t_tinggiAttrib = array("size" => 50,"maxlength" => 50,"required"=>"requried","readonly"=>"readonly");
						echo $ctrlFrm->formText("kecamatan", $this->detailPendaftaran['kecamatan'], $t_tinggiAttrib);
						?>
				</td>
				</tr>
				
				<tr>
				    <td align="right" width="180">* Kabupaten / Kota :</td>
					<td>	
					<? 
						$kotaAttrib = array("size" => 50,"maxlength" => 50,"required"=>"requried","readonly"=>"readonly");
						echo $ctrlFrm->formText("kota", "Cimahi", $kotaAttrib);
					?>
				</td>
				</tr>
				
				<tr>
				    <td align="right" width="180">* Provinsi :</td>
					<td>	
						<? 
						$provAttrib = array("size" => 50,"maxlength" => 50,"required"=>"requried","readonly"=>"readonly");
						echo $ctrlFrm->formText("prov", "Jawa Barat", $provAttrib);
					?>
				</td>
				</tr>
				
				
				
				
				
					
				<tr>  
					<td>&nbsp;</td>
					<td width="500px;">&nbsp;</td>
				    <td>
						
							<input type="button" value="Batal" onclick="pendaftaranlist()"> 
							<input type="reset" value="Ulangi"> 
							<input type="submit" value="Simpan">
					</td>
				</tr>
				<tr>
				    <td>* Harus Diisi</td>
				    <td></td>
				</tr>
			</table>
		</form>
	</div>
</div>

<script>
	$(document).ready(function() {
	$(".validasi").validate();
});
</script>

<script>

 	$(function() {
		$("#d_lahir").datepicker();
	});


function showDialog(val,jum) {      
    $( "#dialog-browse" ).dialog({
      autoOpen: false,
      height: 380,
      width: 640,
      modal: true,
      resizable:false,
      title: "Data"
    });
    if(val =='dosen'){dosenlist(jum);}  
    if(val =='prodi'){prodilist();}  
    return false;
  }

</script>

