<?
require_once 'Zend/View.php';
require_once 'share/format_date.php'; 
require_once 'share/format_page.php';
require_once "share/share_message.php";
require_once "share/oa_dec_cur_conv.php";

$ctrlFrm = new Zend_View();
$pesan = new share_message();
$halaman = new format_page();
$dec_cur = new oa_dec_cur_conv();
$format_date = new format_date();

$currentPage = $this->currentPage;
$numToDisplay = $this->numToDisplay;

function ribuan($angka)
{
	$hasil =  number_format($angka,0,',','.');
	return $hasil;
}

?>
<div class="navlink">
<a href="#" onclick="open_url_to_home('<?php echo $this->basePath; ?>/home/index/depan','<?php echo $this->basePath; ?>/home/index/main');">Halaman Utama</a>
>> Data Kelurahan
</div>

<div id="dialog-browse">  
</div>

<div class="panel">
	<div class="inner">
		<span class="corners-top"><span></span></span>
		
		
		<? if(strtolower($this->jenisForm) == 'insert') {$namaForm = 'frmtambahpendaftaran'; $nama='tambah';}
			else if (strtolower($this->jenisForm) == 'update') {$namaForm = 'frmubahpendaftaran'; $nama='ubah'; }
			else {$namaForm = 'frmhapuspendaftaran';  $nama='hapus';}
		?>
		
		<h2 class="title">FORM <?php echo strtoupper($nama)?> DATA KELURAHAN <strong><?php echo  strtoupper($this->detailPendaftaran['kelurahan']); ?></strong> </h2>
		
	    <div class="spacer"></div> 
		<form method="post" name="<? echo $namaForm;?>" id="<? echo $namaForm;?>" class="validasi">
<?
	$status = $this->hasil;
	$proses = $this->proses;
	$keterangan = $this->keterangan;
	$pesan->show_message($proses, $this->kd_kel, "$status" ); 
?>
			<table width="100%" border="0" cellpadding="0" cellspacing="1" class="std">
<input name="kd_kel" id="kd_kel" type="hidden" value="<?echo $this->detailPendaftaran['kd_kel'];?>" />
<input name="kategoriCari" id="kategoriCari" type="hidden" value="<?echo $this->kategoriCari;?>" />
	<input name="carii" id="carii" type="hidden" value="<?echo $this->carii;?>" />
				
				
				<tr>
				    <td align="right" width="275">* Kode Wilayah :</td>
					<td>	
						<? 
							$kode_wilayahAttrib = array("size" => 50,"maxlength" => 50,"required"=>"required");
							echo $ctrlFrm->formText("kode_wilayah", $this->detailPendaftaran['kode_wilayah'], $kode_wilayahAttrib);
						?>
				</td>
				</tr>

				
				
				<tr>
				    <td align="right" width="180">* Nama Kelurahan :</td>
					<td>	
						<? 
							$kelurahanAttrib = array("size" => 50,"maxlength" => 50,"required"=>"required");
							echo $ctrlFrm->formText("kelurahan", $this->detailPendaftaran['kelurahan'], $kelurahanAttrib);
						?>
				</td>
				</tr>

				<tr>
				    <td align="right" width="180">* Tahun Pembentukan :</td>
					<td>
						<? 
							$tahun_pembentukanAttrib = array("size" => 50,"maxlength" => 50,"required"=>"required");
							echo $ctrlFrm->formText("tahun_pembentukan",trim($this->detailPendaftaran['tahun_pembentukan']), $tahun_pembentukanAttrib);
						?>
					</td>
				</tr>

				<tr>
				    <td align="right" width="180">* Dasar Hukum Pembentukan :</td>
					<td>	
						<? 
						$t_waktuAttrib = array("size" => 50,"maxlength" => 50,"required"=>"required");
						echo $ctrlFrm->formText("dasar_pembentukan", $this->detailPendaftaran['dasar_pembentukan'], $t_waktuAttrib);
						?>
				</td>
				</tr>
				
				
				
				<tr>
				    <td align="right" width="180">* Nomor Kode Pos :</td>
					<td>	
							<? 
							$kode_posAttrib = array("size" => 50,"maxlength" => 50,"required"=>"required");
							echo $ctrlFrm->formText("kode_pos", $this->detailPendaftaran['kode_pos'], $kode_posAttrib);
							?>
				</td>
				</tr>
				
				
				</td>
				</tr>

				<tr>
				    <td align="right" width="180">* Kecamatan :</td>
					<td>	
						<? 
						$kecamatanAttrib = array("size" => 50,"maxlength" => 50,"required"=>"required","readonly"=>"readonly");
						echo $ctrlFrm->formText("kecamatan", $this->detailPendaftaran['kecamatan'], $kecamatanAttrib);
						?>
				</td>
				</tr>
				
				<tr>
				    <td align="right" width="180">* Kabupaten / Kota :</td>
					<td>	
					<? 
						$kotaAttrib = array("size" => 50,"maxlength" => 50,"required"=>"required","readonly"=>"readonly");
						echo $ctrlFrm->formText("kota", "Cimahi", $kotaAttrib);
					?>
				</td>
				</tr>
				
				<tr>
				    <td align="right" width="180">* Provinsi :</td>
					<td>	
						<? 
						$provAttrib = array("size" => 50,"maxlength" => 50,"required"=>"required","readonly"=>"readonly");
						echo $ctrlFrm->formText("prov", "Jawa Barat", $provAttrib);
					?>
				</td>
				</tr>
				
				<!--KELURAHAN-->
	<tr>
		<td align="right" >* 2. Luas Wilayah :</td>
		<td>	
				<? 
				
				$luas =  explode('.',$this->detailPendaftaran['luas']);
					$luas = (!empty($luas[0])) ? ribuan($luas[0]) : 0;
				echo $ctrlFrm->formText("luas", $luas, $luasAttrib);
				$luasAttrib = array("size" => 50,"maxlength" => 50, "required"=>"required","placeholder"=>"contoh : 127,045 ","onkeydown"=>"javascript:return numbersonly(this, event)","onkeyup"=>"javascript:tandaPemisahTitik(this)");
				
				?> km&sup2;
		</td>
	</tr>
	
	
	<tr>
		<td align="right" >3. Batas Wilayah :</td>
		<td>	
		<tr>
				<td align="right" >&nbsp;&nbsp;&nbsp; 1. Sebelah Utara :</td>
				<td align="center">
					<? 
						$batas_utaraAttrib = array("size" => 50,"maxlength" => 50, "required"=>"required");
						echo $ctrlFrm->formText("batas_utara", $this->detailPendaftaran['batas_utara'], $batas_utaraAttrib);
					?>
				</td>
			</tr>
			<tr>
				<td align="right" >&nbsp;&nbsp;&nbsp; 2. Sebelah Selatan :</td>
				<td align="center">
					<? 
						$batas_selatanAttrib = array("size" => 50,"maxlength" => 50, "required"=>"required");
						echo $ctrlFrm->formText("batas_selatan", $this->detailPendaftaran['batas_selatan'], $batas_selatanAttrib);
					?>
				</td>
			</tr>
			<tr>
				<td align="right" >&nbsp;&nbsp;&nbsp;3. Sebelah Barat :</td>
				<td align="center">
					<? 
						$batas_baratAttrib = array("size" => 50,"maxlength" => 50, "required"=>"required");
						echo $ctrlFrm->formText("batas_barat", $this->detailPendaftaran['batas_barat'], $batas_baratAttrib);
					?>
				</td>
			</tr>
			<tr>
				<td align="right" >&nbsp;&nbsp;&nbsp;4. Sebelah Timur :</td>
				<td align="center">
					<? 
						$batas_timurAttrib = array("size" => 50,"maxlength" => 50, "required"=>"required");
						echo $ctrlFrm->formText("batas_timur", $this->detailPendaftaran['batas_timur'], $batas_timurAttrib);
					?>
				</td>
			</tr>
			
		</td>
	</tr>
	
	<tr>
		<td colspan="2" align="right" >4. Orbitrasi (Jarak dari Pusat Pemerintahan) :</td>
		<td></td>
	</tr>		
		
	<tr>
		<td align="right" >&nbsp;&nbsp;&nbsp; Jarak dari Pusat Pemerintahan Kecamatan :</td>
		<td align="center">
			<? 
				$jarak_dari_kecamatan =  explode('.',$this->detailPendaftaran['jarak_dari_kecamatan']);
				$jarak_dari_kecamatan = (!empty($jarak_dari_kecamatan[0])) ? ribuan($jarak_dari_kecamatan[0]) : 0;
				$jarak_dari_kecamatanAttrib = array("placeholder"=>"Diisi hanya dengan angka. Misal: 5000000",  "size" => 50,"maxlength" => 50, "required"=>"required","onkeydown"=>"javascript:return numbersonly(this, event)","onkeyup"=>"javascript:tandaPemisahTitik(this)");
				echo $ctrlFrm->formText("jarak_dari_kecamatan", $jarak_dari_kecamatan, $jarak_dari_kecamatanAttrib);
			?> km
		</td>
	</tr>
	
	<tr>
		<td align="right" >&nbsp;&nbsp;&nbsp; Jarak dari Pusat Pemerintahan Kota :</td>
		<td align="center">
			<? 
				$jarak_dari_kota =  explode('.',$this->detailPendaftaran['jarak_dari_kota']);
				$jarak_dari_kota = (!empty($jarak_dari_kota[0])) ? ribuan($jarak_dari_kota[0]) : 0;
				$jarak_dari_kotaAttrib = array("id"=>"inputTextId","placeholder"=>"Diisi hanya dengan angka. Misal: 5000000",  "size" => 50,"maxlength" => 50, "required"=>"required","onkeydown"=>"javascript:return numbersonly(this, event)","onkeyup"=>"javascript:tandaPemisahTitik(this)");
				echo $ctrlFrm->formText("jarak_dari_kota", $jarak_dari_kota, $jarak_dari_kotaAttrib);
			?>  km 
		</td>
	</tr>
	<tr>
		<td align="right" >&nbsp;&nbsp;&nbsp; Jarak dari Kota/Ibukota Kabupaten:</td>
		<td align="center">
			<? 
				$jarak_dari_ibukota_kota =  explode('.',$this->detailPendaftaran['jarak_dari_ibukota_kota']);
				$jarak_dari_ibukota_kota = (!empty($jarak_dari_ibukota_kota[0])) ? ribuan($jarak_dari_ibukota_kota[0]) : 0;
				$jarak_dari_ibukota_kotaAttrib = array("placeholder"=>"Diisi hanya dengan angka. Misal: 5000000",  "size" => 50,"maxlength" => 50, "required"=>"required","onkeydown"=>"javascript:return numbersonly(this, event)","onkeyup"=>"javascript:tandaPemisahTitik(this)");
				echo $ctrlFrm->formText("jarak_dari_ibukota_kota", $jarak_dari_ibukota_kota, $jarak_dari_ibukota_kotaAttrib);
			?>  km
		</td>
	</tr>
	<tr>
		<td align="right" >&nbsp;&nbsp;&nbsp; Jarak dari Ibukota Provinsi :</td>
		<td align="center">
			<? 
				$jarak_dari_ibukota_prov =  explode('.',$this->detailPendaftaran['jarak_dari_ibukota_prov']);
				$jarak_dari_ibukota_prov = (!empty($jarak_dari_ibukota_prov[0])) ? ribuan($jarak_dari_ibukota_prov[0]) : 0;
				
				$jarak_dari_ibukota_provAttrib = array("placeholder"=>"Diisi hanya dengan angka. Misal: 5000000",  "size" => 50,"maxlength" => 50, "required"=>"required","onkeydown"=>"javascript:return numbersonly(this, event)","onkeyup"=>"javascript:tandaPemisahTitik(this)");
				echo $ctrlFrm->formText("jarak_dari_ibukota_prov", $jarak_dari_ibukota_prov[0], $jarak_dari_ibukota_provAttrib);
			?>  km
		</td>
	</tr>	
	<!--End KELURAHAN-->
	<tr>  
		<td>&nbsp;</td>
		<td width="400px;">&nbsp;</td>
		<td colspan="2">
			
				<input type="button" value="Batal" onclick="pendaftaranlist()"> 
				<input type="reset" value="Ulangi"> 
				<input type="submit" value="Simpan">
		</td>
	</tr>
	<tr>
		<td>* Harus Diisi</td>
		<td></td>
	</tr>
</table>
</form>
	</div>
</div>

<script>
	$(document).ready(function() {
	$(".validasi").validate();
});

$.noConflict();
jQuery( document ).ready(function($) {
// Code that uses jQuery's $ can follow here.
	$('.numeric').autoNumeric('init');
});

</script>



<script language="JavaScript">


function showDialog(val,jum) {      
    $( "#dialog-browse" ).dialog({
      autoOpen: false,
      height: 380,
      width: 640,
      modal: true,
      resizable:false,
      title: "Data"
    });
    if(val =='dosen'){dosenlist(jum);}  
    if(val =='prodi'){prodilist();}  
    return false;
  }

</script>