<?
require_once 'Zend/View.php';
require_once 'share/format_date.php'; 
require_once 'share/format_page.php';
require_once "share/share_message.php";
require_once "share/oa_dec_cur_conv.php";

$ctrlFrm = new Zend_View();
$pesan = new share_message();
$halaman = new format_page();
$dec_cur = new oa_dec_cur_conv();

$currentPage = $this->currentPage;
$numToDisplay = $this->numToDisplay;

?>
<div class="navlink">
<a href="#" onclick="open_url_to_home('<?php echo $this->basePath; ?>/home/index/depan','<?php echo $this->basePath; ?>/home/index/main');">Halaman Utama</a>
>>  Data Kelurahan
</div>
<div class="panel">
	<div class="inner">
		<span class="corners-top"><span></span></span>
		<h2 class="title">DATA KELURAHAN</h2>
			<form method="post" id="frmcaripendaftaran" name="frmcaripendaftaran">				
				Filter :
				<?
					$kategoriCari = array("K.kelurahan" => "Nama Kelurahan", "KEC.kecamatan" => "Kecamatan","tahun_pembentukan" => "Tahun Pembentukan");
					echo $ctrlFrm->formSelect('kategoriCari', $this->kategoriCari, null, $kategoriCari);						
				?>
				
				<input type="text" name="carii" id="carii" align="center" value ="<? echo $this->carii;?>">
				<?
					$atribSubmit = array("onclick"=>"javascript:caripendaftaran();");
					echo $ctrlFrm->formSubmit('cari', 'Search', $atribSubmit)."&nbsp;";
				?>
		</form>
	
<fieldset class="fields"> 
<? 
$status = $this->hasil;
$proses = $this->proses;
$pesan->show_message($proses, $k_pendaftaran, "$status" ); 
?>

<!-- <div class="add" title="Tambah Data" onClick="pendaftaranForm('insert','');"></div>-->

<table id="sorter" class="sortable" cellspacing="1" cellpadding="2" border="0" align="center">
				<th >NoUrut</th>
				<th >Kode Kelurahan</th>
				<th >Nama Kelurahan</th> 
				<th >Tahun Pembentukan</th> 
				<th >Dasar Hukum Pembentukan</th> 
				<th >Nomor Kode Pos</th> 
				<th> Kecamatan</th> 
				<th >Kabupaten/Kota</th> 
				<th >Provinsi</th> 
				
				<th colspan="3" class="nosort">FUNGSI</th>
				
				<?
				if (count($this->pendaftaranList) == 0){ 
				?>
					<tr class="event2"><td colspan="11" style="color:#8C0000; font-weight:bold; background-color: #FF9999">Data Tidak Ditemukan</td></tr>
				<?} else {
						
						
						foreach ($this->pendaftaranList as $key => $val): 
						if ($key%2==0) { ?>
							<tr class="event">
						<? } else if ($key%2==1) { ?>
							<tr class="event2">
						<? } 
						$kd_kel		= $this->escape($val['kd_kel']); 
						$kelurahan	= $this->escape($val['kelurahan']); 
						$kode_wilayah	= $this->escape($val['kode_wilayah']); 
						$tahun_pembentukan	= $this->escape($val['tahun_pembentukan']);
						$dasar_pembentukan	= $this->escape($val['dasar_pembentukan']);
						$kode_pos	= $this->escape($val['kode_pos']);
						$kecamatan	= $this->escape($val['kecamatan']);
						$kota	="Cimahi";
						$prov	="Jawa Barat";
					
						$noUrut = (($currentPage -1)* $numToDisplay) + $key +1;
						echo $ctrlFrm->formHidden('kd_kel', $noreg, null);
						
						?>
					<td align="center"><? echo $noUrut;?></td>
					<td align="center"><a href="#" title= "detail <?php echo $kelurahan?>" onclick="open_url_to_div('<?php echo $this->basePath; ?>/kelurahan/rekamkelurahan/rekamkelurahan?jenisForm=update&kd_kel=<?echo $kd_kel;?>','<?php echo $this->basePath; ?>/kelurahan/rekamkelurahan/rekamkelurahanjs');"><? echo $kd_kel;?></a></td>

					<td align="left"><? echo $kelurahan;?></td>
					<td align="center"><? echo $tahun_pembentukan;?></td>
					<td align="center"><? echo $dasar_pembentukan;?></td>
					<td align="center"><? echo $kode_pos;?></td>
					<td align="center"><? echo $kecamatan;?></td>
					<td align="center"><? echo $kota;?></td>
					<td align="center"><? echo $prov;?></td>


<td><div onClick="cetak('<? echo $id;?>');" class="pdf" title="Cetak Data"></div></td>
<td><div onClick="pendaftaranForm('update','<? echo $kd_kel;?>');" class="edit" title="Ubah Data"></div></td>
<td><div onClick="pendaftaranHapus('Data','<? echo $kd_kel;?>','<? echo $nama;?>');" class="delete" title="Hapus Data"></div></td>


						
					
						</tr>
					<?
					endforeach;
				}
				?>
			</table>

			<?	
			$totalData = $this->totPendaftaranList;
			$modul = $this->basePath."/pasien/pendaftaran/pendaftaranlist";
			$param1 = $this->cabang;$param2 = $this->tahun;$param3 = $this->bulan;$param4 = $this->jenis;$param5 = $this->status;
			echo $halaman->showPage($totalData, $numToDisplay, $currentPage, 'tableview', $modul, $param1, $param2, $param3, $param4);		
			
			?>
		</fieldset>		 
		
		<span class="corners-bottom"><span></span></span>
	</div>
</div>
<script type="text/javascript">
var sorter=new table.sorter("sorter");
sorter.init("sorter",0);
</script>