<? require_once 'Zend/View.php';
   require_once "share/tanggal.php";  
   require_once "share/pesan.php";
   
    $pesan = new pesan();
	$ctrlDate = new tanggal();   
	
	$ctrlFrm = new Zend_View();
	
   $jmldata = count($this->namadosen);
    for ($j = 0; $j < $jmldata; $j++) {
		$datalist[$j] = array(	
								"id" =>(string)$this->namadosen[$j]['id'],								"n_nama" =>(string)$this->namadosen[$j]['n_nama'],
								"i_nidn" =>(string)$this->namadosen[$j]['i_nidn'],								"n_nama" =>(string)$this->namadosen[$j]['n_nama'],
								"n_gelar" =>(string)$this->namadosen[$j]['n_gelar']								
								);
					}  

$par=$this->par;	
///====== referensi ============================================================================================================================================================================	
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=windows-1252">
<title>Popup</title>
<link rel="stylesheet" href="<? echo $this->basePath;?>/css/default.css" type="text/css" title="Nice Blue style" />
<link href="<? echo $this->basePath;?>/css/tools.css" rel="stylesheet" type="text/css" />
<link rel="stylesheet" href="<? echo $this->basePath;?>/css/thickbox.css" type="text/css" media="screen" />
<link href="<? echo $this->basePath;?>/css/main.css" rel="stylesheet" type="text/css" />
<link rel="stylesheet" href="<? echo $this->basePath;?>/css/style.css" type="text/css" title="Nice Blue style" />
<SCRIPT src="<? echo $this->basePath;?>/js/jquery.js" type="text/javascript"></SCRIPT>
<SCRIPT src="<? echo $this->basePath;?>/js/jquery.form.js" type="text/javascript"></SCRIPT>
</head>
<script>
function PilihanData(i_nidn,id) {  

	opener.document.forms[0].user_id.value =id;
	//opener.document.forms[0].n_nama.value =n_nama;	
	window.close();		
 }
</script> 
<body>
<div class="popups" >
<div class="space-line"></div>
<div id="tableview">
<div class="blank"></div>
	<h3 class="title">Daftar Dosen</h3>

		
<fieldset class="fields"> 
	<table align="center" border="0" cellspacing="1" cellpadding="2" class="tbl">
		      	<th width=5%>No</th>
			<th width=10%>Kode</th>
		      	<th width=85%>Nama</th>
			     
<?
					if($jmldata == 0)
					{
						echo '<tr class="event">
								<td><font color=\"red\">-</font></td>								
								<td>&nbsp;</td>
								<td>&nbsp;</td>
								</tr>';
					}
					else
					{			  
			  			  
			  $j=1;	$no=0;
			  $x=0;
 foreach ($datalist as $key => $val):
  $no = (($currentPage -1)* $numToDisplay) + $key +1;						
			  if ($key%2==0) { ?>
			<tr class="event">
			  <?php } else if ($key%2==1) { ?>
			<tr class="event2">
			  <?php } ?>
		  
			<td class="clright">
				<?php echo $no;?>
			</td>
			<td class="clcenter">			
				<?php 
				echo $this->escape($val['i_nidn']);
				?>
			</td>
			<td class="clleft">
			<a class="enclose" href="#" onclick="return PilihanData('<? echo $this->escape($val['i_nidn']); ?>','<? echo $this->escape($val['id']);  ?>')">
				<?php 
					echo $this->escape($val['n_nama']);
				?>
				, <?php 
					echo $this->escape($val['n_gelar']);
				?>
			</a>	
			</td>

		</tr>
 <?php $i++; $x++;
endforeach; 
  }
 ?>	
			
</table>
		</fieldset>
		<fieldset class="fields1" >	
			<input type="button" onclick="window.close()" value="Tutup"/>
		</fieldset>		
</div>

</div>
</body>
</html>