<?
require_once 'fpdf/Pdf_Service.php';
require_once 'Zend/View.php';
require_once 'share/format_date.php'; 
require_once "share/oa_dec_cur_conv.php";
$dec_cur = new oa_dec_cur_conv();
$tanggal = new format_date();

      			$html = $html.'<html><body>';
			$html = $html.'<table width="150" border="0" align="center" cellpadding="1" cellspacing="1">';
      			$html = $html.'<tr>';
      			$html = $html.'<td align="left" colspan="3"></td>';
   			$html = $html.'</tr>';
      				
      			$html = $html.'<tr class="event">';
      			$html = $html.'<td colspan="3" align="center"><div align="center">Data Nilai '.$this->n_jenis.' Mahasiswa </div></td>';
			$html = $html.'</tr>';
      				
      			$html = $html.'<tr class="event">';
      			$html = $html.'<td align="left" colspan="3"></td>';
   			$html = $html.'</tr>';
      			$html = $html.'</table><br />';

				$html = $html.'<table width="190" border="0" align="center" cellpadding="1" cellspacing="1">';
      				$html = $html.'<tr class="event">';
      				  $html = $html.'<td align="left" width="25%">Nama</td>';
      				  $html = $html.'<td align="left" width="0.5%"><div align="center">:</div></td>';
      				  $html = $html.'<td align="left" width="52%">'.$this->n_mhs.'</td>';
   				  $html = $html.'</tr>';
      				$html = $html.'<tr class="event">';
      				  $html = $html.'<td align="left">Npm</td>';
      				  $html = $html.'<td align="left"><div align="center">:</div></td>';
      				  $html = $html.'<td align="left">'.$this->id_npm.'</td>';
   				  $html = $html.'</tr>';
      				$html = $html.'<tr class="event">';
      				  $html = $html.'<td align="left">Program Studi</td>';
      				  $html = $html.'<td align="left"><div align="center">:</div></td>';
      				  $html = $html.'<td align="left">'.$this->n_prodi.'</td>';
   				  $html = $html.'</tr>';
      				$html = $html.'<tr class="event">';
      				  $html = $html.'<td align="left"></td>';
      				  $html = $html.'<td align="left"><div align="center"></div></td>';
      				  $html = $html.'<td align="left"></td>';
   				  $html = $html.'</tr>';
      				$html = $html.'<tr class="event">';
      				  $html = $html.'<td align="left"></td>';
      				  $html = $html.'<td align="left"><div align="center"></div></td>';
      				  $html = $html.'<td align="left"></td>';
   				  $html = $html.'</tr>';
      				 $html = $html.'<tr class="event">';
      				  $html = $html.'<td align="left" colspan = "3">Semester : '.$this->n_semester.'</td>';
      				 $html = $html.'</tr>';
      				      				      				      				      				      				
      			$html = $html.'</table>';
				$html = $html.'<BR />';
				$html = $html.'<table width="190" border="1" align="center" cellpadding="1" cellspacing="1">';
      				
				$html = $html.'<tr class="event">';
      				  $html = $html.'<td width="10%"  align="center"><div align="center">No</div></td>';
      				  $html = $html.'<td width="25%"  align="center"><div align="center">Kode</div></td>';
      				  $html = $html.'<td  width="80%" align="center"><div align="center">Matakuliah</div></td>';
      				  $html = $html.'<td  align="center" ><div align="center">Sks</div></td>';
   				  $html = $html.'<td  align="center" ><div align="center">Nilai</div></td>';
   				  $html = $html.'</tr>';

				
				if (count($this->detailAnalisispasienList) == 0){ 
				
					$html = $html.'<tr class="event2"><td colspan="7"><font color="red">No data</font></td></tr>';
				} else {
						
						foreach ($this->detailAnalisispasienList as $key => $val): 
						if ($key%2==0) { 
							$html = $html.'<tr class="event">';
						 } else if ($key%2==1) { 
							$html = $html.'<tr class="event2">';
						 } 
					$id		= $this->escape($val['id']); 
					$n_nama		= $this->escape($val['n_nama']); 
					$n_klasifikasi	= $this->escape($val['n_klasifikasi']);
					$n_tindakan	= $this->escape($val['n_tindakan']); 
					$c_alergi	= $this->escape($val['c_alergi']);
					$c_rematik	= $this->escape($val['c_rematik']); 

					$n_alergi ='';
					if($c_alergi =='N'){$n_alergi ='Normal';}
					if($c_alergi =='T'){$n_alergi ='Tidak Normal';}
					$n_rematik ='';
					if($c_rematik =='N'){$n_rematik ='Normal';}
					if($c_rematik =='T'){$n_rematik ='Tidak Normal';}
					
						
      				$html = $html.'<tr class="event">';
      				  $html = $html.'<td align="center">'.$noUrut.'</td>';
      				  $html = $html.'<td align="center">'.$n_nama.'</td>';
      				  $html = $html.'<td align="left">'.$n_klasifikasi.'</td>';
      				  $html = $html.'<td align="center">'.$n_tindakan.'</td>';
   				  $html = $html.'<td align="center">'.$n_alergi.'</td>';
   				  $html = $html.'</tr>';
				endforeach;
				}
			
			$html = $html.'<table width="190" border="0" align="center" cellpadding="1" cellspacing="1">';
      			$html = $html.'<tr>';
      			$html = $html.'<td align="left" colspan="3"></td>';
   			$html = $html.'</tr>';
      			//$jum_nilai = $jum_sks*$jum_mutu;
      			$html = $html.'<tr class="event">';
      			$html = $html.'<td colspan="3" >Jumlah SKS : '.$jum_sks.'</td>';
			$html = $html.'</tr>';
      			$html = $html.'<tr class="event">';
			/*$jum_sks = 2.0;
			$ipk = $jum_nilai/3.3;
			$ipk =substr($ipk,0,4);*/
      			$html = $html.'<td align="left" colspan="3">Jumlah Nilai : '.$jum_totnilai.'</td>';
   			$html = $html.'</tr>';
			$html = $html.'<tr class="event">';
      			$html = $html.'<td align="left" colspan="3">IP	      : </td>';
   			$html = $html.'</tr>';
      			$html = $html.'</table><br />';	  
			
      			$html = $html.'</table><br />';
			$html = $html.'<table width="175" border="0" align="center" cellpadding="1" cellspacing="1">';
      			$html = $html.'<tr>';
      			$html = $html.'<td align="left" ></td>';
   			$html = $html.'<td align="left" ></td>';
   			$html = $html.'</tr>';

			$html = $html.'<tr>';
      			$html = $html.'<td align="left" ></td>';
   			$html = $html.'<td align="left" ></td>';
   			$html = $html.'</tr>';
      				
      			$html = $html.'<tr class="event">';
      			$html = $html.'<td  align="center"></td>';
		        $html = $html.'<td  align="center"></td>';
		        $html = $html.'</tr>';
      				
      			$html = $html.'<tr class="event">';
      			$html = $html.'<td align="center"></td>';
   			$html = $html.'<td align="center"></td>';
   			$html = $html.'</tr>';

			$html = $html.'<tr class="event">';
      			$html = $html.'<td align="left"></td>';
   			$html = $html.'<td align="left"></td>';
   			$html = $html.'</tr>';
			$html = $html.'<tr class="event">';
      			$html = $html.'<td align="left"></td>';
   			$html = $html.'<td align="left"></td>';
   			$html = $html.'</tr>';
			$html = $html.'<tr class="event">';
      			$html = $html.'<td align="left"></td>';
   			$html = $html.'<td align="left"></td>';
   			$html = $html.'</tr>';
			
			$html = $html.'<tr class="event">';
      			$html = $html.'<td align="center"></td>';
   			$html = $html.'<td align="center"></td>';
   			$html = $html.'</tr>';


      			$html = $html.'</table>';

      			$html = $html.'</body>';
			$html = $html.'</html>';  


  class PDF extends Pdf_Service
    {
        var $angle=0;
       
       
        function Header()
        {
           
        }
		
    }
        
      $p = new PDF($orientation='P',$unit='mm',$format='Legal');
	
    $p ->AliasNbPages();
    $p ->AddPage();
    $p->SetMargins(10,30,10); //L,T,B
    $p->SetFont('Arial', 'B', 12);
    $p->SetTextColor(35, 35, 35);  
    $p->Cell(45);
    $p->Cell(175,5,'',0,1,'C');
   //$p->WriteHTML('Lembar 1 untuk Mahasiswa<br>');
    $p->WriteHTML($html);
  //  $p->WriteHTML('<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>');
  //  $p->WriteHTML('Lembar 2 untuk Dosen Wali<br>');
  //  $p->WriteHTML($html);
    // echo $htmlRM;
    $p->output('','I');   
//echo $html;
                     
?>