<?php
	header("Content-type: application/octet-stream");
	header("Content-Disposition: attachment; filename = Data Kejadian Kelurahan Per Bulan.xls");
	header("Pragma: no-cache");
	header("Expires: 0");
?>
<h3 align ="center">Laporan Kejadian Kelurahan</h3>
<h3 align ="center">Tahun <?php echo $this->thn?></h3>
<h3 align ="center">Kelurahan <?php echo $this->kelurahan?></h3>

<table border="1">
  <tr align ="center">
	  <th>No</th>
	  <th>Hari/ Tanggal</th>
	  <th>Uraian</th>
	  <th>Waktu</th>
	  <th>Lokasi</th>
	  <th>Kerugian</th>
	  <th>Nominal</th>
	  <th>Pelapor</th>
	  <th>Keterangan</th>
	  <th>Lampiran</th>
  </tr>
<?php $i=1?>
<?php  foreach($this->cetak as $data) : ?>
	<tr>
		<td><?php echo $i;?></td>		
		<td><?php echo $this->escape($data->hari); echo ", ";echo $this->escape($data->tanggal);?></td>
		<td><?php echo $this->escape($data->uraian); ?></td>			
		<td><?php echo $this->escape($data->waktu);?></td>
		<td><?php echo "'".$this->escape($data->lokasi);?></td>
		<td><?php echo $this->escape($data->kerugian);?></td>
		<td><?php echo $this->escape($data->nominal);?></td>
		<td><?php echo $this->escape($data->pelapor);?></td>
		<td><?php echo $this->escape($data->keterangan);?></td>
		<td><?php echo $this->escape($data->lampiran);?></td>
	</tr>
<?php $i++; endforeach; ?>
</table>

<?php
//ambil tgl hari ini
//$tanggal = date("Y-m-d");
// Array Hari
$array_hari = array(1=>'Senin','Selasa','Rabu','Kamis','Jumat', 'Sabtu','Minggu');
$hari = $array_hari[date('N')];

//Format Tanggal 
$tanggal = date ('j');

//Array Bulan 
$array_bulan = array(1=>'Januari','Februari','Maret', 'April', 'Mei', 'Juni','Juli','Agustus','September','Oktober', 'November','Desember'); 
$bulan = $array_bulan[date('n')];
 
//Format Tahun 
$tahun = date('Y');
echo "<h4>Cimahi, " . $tanggal ." ". $bulan ." ". $tahun."</h4>";
//echo "<h4>Cimahi, $tanggal</h4>";
?>