function carilaporankelurahan()
{
	$("#frmcarilaporankelurahan").ajaxForm(frmcarilaporankelurahan_opt);
}
var frmcarilaporankelurahan_opt = {
		target : '#tableview',
		url: '<?php echo $this->basePath; ?>/kelurahan/laporankelurahan/laporankelurahanlist',
		type: 'post', 
		resetForm: false
};
function laporankelurahanlist()
{
	periode = document.getElementById('periode').value;
	kd_kel = document.getElementById('kd_kel').value;
	var param = {periode:periode,kd_kel:kd_kel};
	var url = '<?php echo $this->basePath; ?>/kelurahan/laporankelurahan/laporankelurahanlist';
	jQuery.get(url, param, function(data) {
		$("div#tableview").html(data);
	});
}

function laporankelurahanForm(jenisForm, id)
{
	periode = document.getElementById('periode').value;
	kd_kel = document.getElementById('kd_kel').value;
	var url = '<?php echo $this->basePath; ?>/kelurahan/laporankelurahan/laporankelurahandata';
	var param = { jenisForm:jenisForm,id:id,periode:periode,kd_kel:kd_kel};
	jQuery.get(url, param, function(data) {
		jQuery("div#tableview").html(data);
		jQuery("#frmtambahlaporankelurahan").ajaxForm(tambahlaporankelurahan_opt);
		jQuery("#frmubahlaporankelurahan").ajaxForm(ubahlaporankelurahan_opt);
	});
}

var tambahlaporankelurahan_opt = {
	target : '#tableview',
	url: '<?php echo $this->basePath; ?>/kelurahan/laporankelurahan/laporankelurahan',
	beforeSubmit : function() {
		
		if (document.getElementById('kode_kelurahan').value == ''){
			alert('Kode/Nama kelurahan harus Diisi');
			return false;
		}

		if (document.getElementById('n_nama').value == ''){
			alert('Kode/Nama kelurahan harus Diisi');
			return false;
		}


		/*if (document.getElementById('gender').value == '-'){
			alert('Jenis Kelamin harus Dipilih');
			return false;
		}

		if (document.getElementById('t_lahir').value == ''){
			alert('Tempat/Tgl Lahir harus Diisi');
			return false;
		}

		if (document.getElementById('d_medrec').value == ''){
			alert('Tempat/Tgl Lahir harus Diisi');
			return false;
		}

		if (document.getElementById('t_badan').value == ''){
			alert('Alamat harus Diisi');
			return false;
		}
		
		if (document.getElementById('b_badan').value == ''){
			alert('Telp/HP Diisi');
			return false;
		}
		if (document.getElementById('n_tensi').value == ''){
			alert('Telp/HP Diisi');
			return false;
		}

		if (document.getElementById('n_diagnosis').value == ''){
			alert('Bidang Studi harus Diisi');
			return false;
		}*/
	answer = confirm('Apakah data anda masukan sudah benar?.\n\'OK\' Jika benar, \'Cancel\' jika tidak.' );

	//alert(answer);
	if(answer !=0) { 
		return true;
	}
	else{
		return false;
	}
		
	},
	success: function(){
	doCount(5);
	
	},
	type: 'post', 
	resetForm: false
};

var ubahlaporankelurahan_opt = {
	target : '#tableview',
	url: '<?php echo $this->basePath; ?>/kelurahan/laporankelurahan/laporankelurahanupdate',
	beforeSubmit : function() {

		/*if (document.getElementById('gender').value == '-'){
			alert('Jenis Kelamin harus Dipilih');
			return false;
		}

		if (document.getElementById('t_lahir').value == ''){
			alert('Tempat/Tgl Lahir harus Diisi');
			return false;
		}

		if (document.getElementById('d_medrec').value == ''){
			alert('Tempat/Tgl Lahir harus Diisi');
			return false;
		}

		if (document.getElementById('t_badan').value == ''){
			alert('Alamat harus Diisi');
			return false;
		}
		
		if (document.getElementById('b_badan').value == ''){
			alert('Telp/HP Diisi');
			return false;
		}
		if (document.getElementById('n_tensi').value == ''){
			alert('Telp/HP Diisi');
			return false;
		}

		if (document.getElementById('n_diagnosis').value == ''){
			alert('Bidang Studi harus Diisi');
			return false;
		}*/
	answer = confirm('Apakah data anda masukan sudah benar?.\n\'OK\' Jika benar, \'Cancel\' jika tidak.' );
	if(answer !=0) { 
		return true;
	}
	else{
		return false;
	}

	},
	success: function(){
	doCount(5);
	jQuery("#frmubahlaporankelurahan").ajaxForm(ubahlaporankelurahan_opt);
	},
	type: 'post', 
	resetForm: false
};


function laporankelurahanHapus(param1, param2, n_nama)
{ 
	periode = document.getElementById('periode').value;
	kd_kel = document.getElementById('kd_kel').value;
	
	if(ConfirmDelete(param1,n_nama))
	{	
		handler = '<?php echo $this->basePath; ?>/kelurahan/laporankelurahan/laporankelurahanhapus';
		var opt = {id : param2,periode:periode,kd_kel:kd_kel};
		jQuery.get(handler,opt,function(data) {
				$("#tableview").html(data);
				doCount(5);
			 });
	}
}

function cetak(d_medrec)
{
	if(d_medrec == '' || d_medrec == '-' || d_medrec == '--'){alert('Tanngal harus Ada');return false;}

	var url = '<?php echo $this->basePath; ?>/kelurahan/laporankelurahan/cetakrekappdf?&d_medrec='+d_medrec;
	swin = window.open(url,'win','scrollbars,width=600,height=400,top=80,left=140,status=yes,toolbar=no,menubar=yes,location=no');
	swin.focus();
}

function cetakrekap()
{
	bulan = document.getElementById('bulan').value;
	tahun = document.getElementById('tahun').value;
	kd_kel = document.getElementById('kd_kel').value;
	
	if(bulan == 'bulan' || bulan == '-' || bulan == '--'){alert('bulan harus diisi');return false;}
	if(tahun == 'tahun' || tahun == '-' || tahun == '--'){alert('tahun harus diisi');return false;}
	if(kd_kel == '' || kd_kel == '-' || kd_kel == '--'){alert('Kode Kelurahan harus diisi');return false;}

	var url = '<?php echo $this->basePath; ?>/kelurahan/rekamkelurahan/rekamkelurahancetak?&bulan='+bulan+'&tahun='+tahun+'&kd_kel='+kd_kel;
	
}



function BukaWindows(){
	var w = 0; 
	var h = 0;
	w = screen.availWidth;
	h = screen.availHeight;
	var popW = 800, popH = 600;
	var leftc = (w-popW)/2;
	var topc = (h-popH)/2;
	var selectWindow = window.open(url,'Selection', 'left=' + leftc + ',top=' + topc + ', width='+popW+',height='+popH+',resizable=0,scrollbars=yes');
}

function CariPengadaan()
{
	document.getElementById('n_pengadaan').readOnly = true;
	id_pengadaan = document.getElementById('id_pengadaan').value;

	url = "<?php echo $this->basePath; ?>/adm/laporankelurahan/n_namapengadaan?id_pengadaan="+id_pengadaan;
	BukaWindows();
}


function tambahKepada()
{
	var table = document.getElementById('kepada'); 
	var rowCount = (table.rows.length);  
	var idRow = (rowCount)*1;
	var row = table.insertRow(rowCount);
	row.className = "event";	
	
	var cell0 = row.insertCell(0);  
	var num = (rowCount)*1+1;
	cell0.innerHTML = num+".";
	
	var cell1 = row.insertCell(1);  
	cell1.innerHTML = "<input type=\"text\" size = \"120\" maxlength = \"150\" name=\"n_nama_"+idRow+"\" id=\"n_nama_"+idRow+"\" value=\"\" > <input type=\"button\" value=\"Cari\" onclick=\"showDialog('dosen','"+idRow+"');\" >";
	
	var cell2 = row.insertCell(2);  
	var rowDelete = (idRow*1)+1;
	cell2.innerHTML = "<input type=\"hidden\" name=\"id_pegawai_"+idRow+"\" id=\"id_pegawai_"+idRow+"\" value=\"\" ><input type=\"hidden\" name=\"id_pembimbing_"+idRow+"\" id=\"id_pembimbing_"+idRow+"\" value=\"\"><img src=\"/images/cross.png\" title=\"Hapus Data\" onclick=\"deleteRow('kepada', this);getjumlahx();\"><a name=\"baris_"+idRow+"\"/>";
	
	document.getElementById('jumlahItem').value = (rowCount*1)+1;

}

function deleteRow(tableID, r) {
	var i=r.parentNode.parentNode.rowIndex;
	document.getElementById(tableID).deleteRow(i);
	var table = document.getElementById(tableID); 
	var rowCount = table.rows.length;  
	var idRow = rowCount*1;
	document.getElementById("jumlahItem").value = idRow;
	
}
function deleteRow2(param,id_item,no_item)
{ 
	if(ConfirmDelete(param, no_item))
	{	
		handler = '<?php echo $this->basePath; ?>/kelurahan/laporankelurahan/laporankelurahanhapus';
		//var opt = {id_item:id_item,tahun:tahun,cabang:cabang,kategoriCari:kategoriCari,carii:carii};
		jQuery.get(handler,function(data) {
				$("#tableview").html(data);
				doCount(5);
			 });
	}
}

function getKab(){
	var url = '<?php echo $this->basePath; ?>/kelurahan/laporankelurahan/get-kab';
	var propinsi = document.getElementById('c_propinsi').value;
	var param = {propinsi:propinsi};	
	$.getJSON(url,param,function(data){
		$('#kota').find('option').remove().end();
		
		$('#kota').attr('disabled',false).end();
		$('.someElement').attr('disabled', '');
		$('#kota').append($('<option>').text("--Pilih--").attr('value', "-"));
		$.each(data, function(i, value) {
				$('#kota').append($('<option>').text(value.n_kab).attr('value', value.id_kab));
		  });
	});
}



function dosenlist(jum) {
  var url        = '<?php echo $this->basePath; ?>/kelurahan/laporankelurahan/dosenlist';
  var param      = {jum:jum};
  jQuery.get(url,param,function(data) {   
    $("#dialog-browse").html(data);
    $("#dialog-browse").dialog("open");
  }); 
}

function cariDosen(jum)  {
  $("#frmCariDosen").ajaxForm(frmCariDosen_opt);
}

var frmCariDosen_opt = {
    target : '#dialog-browse',
    url: '<?php echo $this->basePath; ?>/kelurahan/laporankelurahan/dosenlist',
    type: 'get', 
    resetForm: false
};

function closeDialogDosen(id_pegawai,nama,jum) {  
  $("#dialog-browse").dialog("close");
  $("#id_pegawai_"+jum).val(id_pegawai);
  $("#n_nama_"+jum).val(nama);
}




function kelurahanlist() {
    var url        = '<?php echo $this->basePath; ?>/kelurahan/laporankelurahan/kelurahanlist';
    jQuery.get(url,function(data) {   
    $("#dialog-browse").html(data);
    $("#dialog-browse").dialog("open");
  }); 
}

function carikelurahan()  {
  $("#frmCarikelurahan").ajaxForm(frmCarikelurahan_opt);
}

var frmCarikelurahan_opt = {
    target : '#dialog-browse',
    url: '<?php echo $this->basePath; ?>/kelurahan/laporankelurahan/kelurahanlist',
    type: 'get', 
    resetForm: false
};

function closeDialogkelurahan(kode_kelurahan,n_kelurahan) {  
  $("#dialog-browse").dialog("close");
  $("#kode_kelurahan").val(kode_kelurahan);
  $("#n_nama").val(n_kelurahan);
}




