<?
//include "charts.php";

$servernya = $_SERVER['SERVER_NAME'];
$imgnya = "http://".$servernya.$this->baseData."/util/tampilfoto/viewimages?f=edit";
//$imgnya = $this->baseData."/chart/test.php";
//echo $imgnya;
//$findchart =InsertChart( $imgnya, "charts_library", "modules/stock/chart_stock.php?sCode=".$sCode."&iBUMN=".$idBumn."" ,600, 400, "8844FF", true );
//$findchart =InsertChart ( "charts.swf", "charts_library", "chart.php?sCode=".$sCode."&iBUMN=".$idBumn."" ,600, 400, "8844FF", true );
//echo $findchart;
?>


