function caristatuspasien()
{
	$("#frmcaristatuspasien").ajaxForm(frmcaristatuspasien_opt);
}
var frmcaristatuspasien_opt = {
		target : '#tableview',
		url: '<?php echo $this->basePath; ?>/adm/statuspasien/statuspasienlist',
		type: 'post', 
		resetForm: false
};
function statuspasienlist()
{
	kategoriCari = document.getElementById('kategoriCari').value;
	carii = document.getElementById('carii').value;
	var param = {kategoriCari:kategoriCari,carii:carii};
	
	var url = '<?php echo $this->basePath; ?>/adm/statuspasien/statuspasienlist';
	jQuery.get(url, param, function(data) {
		$("div#tableview").html(data);
	});
}

function statuspasienForm(jenisForm, id_status)
{
	kategoriCari = document.getElementById('kategoriCari').value;
	carii = document.getElementById('carii').value;
	var url = '<?php echo $this->basePath; ?>/adm/statuspasien/statuspasiendata';
	var param = { jenisForm:jenisForm, id_status:id_status,kategoriCari:kategoriCari,carii:carii};
	jQuery.get(url, param, function(data) {
		jQuery("div#tableview").html(data);
		jQuery("#frmtambahstatuspasien").ajaxForm(tambahStatuspasien_opt);
		jQuery("#frmubahstatuspasien").ajaxForm(ubahStatuspasien_opt);
	});
}

var tambahStatuspasien_opt = {
	target : '#tableview',
	url: '<?php echo $this->basePath; ?>/adm/statuspasien/statuspasien',
	beforeSubmit : function() {
		
		if (document.getElementById('n_status').value == ''){
			alert('Status Pasien harus Diisi');
			return false;
		}

	answer = confirm('\n\   Apakah data yang anda masukan adalah benar.\n\n   \'OK\' Jika setuju, \'Cancel\' Jika tidak setuju.');
		if(answer !=0) { 
			return true;
		}
		else{
			return false;
		}
		
	},
	success: function(){doCount(5);},
	type: 'post', 
	resetForm: false
};

var ubahStatuspasien_opt = {
	target : '#tableview',
	url: '<?php echo $this->basePath; ?>/adm/statuspasien/statuspasienupdate',
	beforeSubmit : function() {
		
		if (document.getElementById('n_status').value == ''){
			alert('Status Pasien harus Diisi');
			return false;
		}
	answer = confirm('\n\   Apakah data yang anda masukan adalah benar.\n\n   \'OK\' Jika setuju, \'Cancel\' Jika tidak setuju.');
		if(answer !=0) { 
			return true;
		}
		else{
			return false;
		}
		
	},
	success: function(){doCount(5);},
	type: 'post', 
	resetForm: false
};

function statuspasienHapus(param1, nama, param2)
{ 
	
	if(ConfirmDelete(param1,nama))
	{	
		handler = '<?php echo $this->basePath; ?>/adm/statuspasien/statuspasienhapus';
		var opt = {id_status : param2};
		jQuery.get(handler,opt,function(data) {
				$("#tableview").html(data);
				doCount(5);
			 });
	}
}

function BukaWindows(){
	var w = 0; 
	var h = 0;
	w = screen.availWidth;
	h = screen.availHeight;
	var popW = 800, popH = 600;
	var leftc = (w-popW)/2;
	var topc = (h-popH)/2;
	var selectWindow = window.open(url,'Selection', 'left=' + leftc + ',top=' + topc + ', width='+popW+',height='+popH+',resizable=0,scrollbars=yes');
}

