function tentangkamiM(par,idtentangkami){

	var url = '<?php echo $this->basePath;?>/cmsmodule/tentangkami/tentangkami';	
	var param = {par:par,idtentangkami:idtentangkami};
		jQuery.get(url, param, function(data) {
			jQuery("#tableview").html(data);
			jQuery("#formtentangkami").ajaxForm(maintain_tentangkami);
		});
}
function inserttentangkami(){
	jQuery("#formtentangkami").ajaxForm(maintain_tentangkami);
}
var maintain_tentangkami = {
	target:'#tableview',
	beforeSubmit: function() {		
		aobj= document.formtentangkami;
		astr= "document.formtentangkami";
		var cekVal="";
		with(aobj){      
			var Proceed = 1;
			while (Proceed == 1)
			{
				/*sdmValidasiData (navigation.js)*/
				if((!content.value)){cekVal = sdmValidasiData(astr,"content","Konten tentang kami harus diisi....!");return false;break;}
				break;
			}
			
		}
		
		//if (cekVal == false) {return false;}
	
	}, 
	success:function(){
		location.href="#top";
		doCounter(5);
		jQuery("#formtentangkami").ajaxForm(maintain_tentangkami);
	},
	url: '<?php echo $this->basePath; ?>/cmsmodule/tentangkami/maintaindata',
	type: 'post',
	resetForm: false
};



function HapusDatatentangkami(idtentangkami,jdl)
{
	var where_to= confirm("Yakin anda akan hapus data tentangkami :"+jdl);
	 if (where_to== true)
	 {
		url = "<?php echo $this->basePath; ?>/cmsmodule/tentangkami/hapusdata"
		 
		var opt = {idtentangkami:idtentangkami};
		jQuery.get(url,opt,function(data) {
			jQuery("#tableview").html(data);
				location.href="#top";
				doCounter(5);
			});
	 }
}

function setvalueuplpdf(v,n,f) { 

	  if (f!="") {
	    var pass=false;
	    var af=f.split("/");
        var nval=eval("document.forms[0]."+n);
		var ext=v.substring(v.lastIndexOf(".")+1,v.length);
		if ((ext==f)||(ext=='png')||(ext=='gif')){ 
		document.forms[0].a_file.value=v; 
		}
		else{
		  alert ("Hanya untuk file berekstensi '"+f+"',jpg,gif,png ");
		  nval.value="";
		  document.forms[0].a_file.value=""; 
		  return;	  
		}
	  }
}