
     <dl>
		<!--<dd class="col-left2">&nbsp;</dd>
		<dd class="dot2">&nbsp;</dd>
		<dd class="space">&nbsp;</dd>-->
		<dd class="space">&nbsp;</dd>
		<dd class="space">&nbsp;</dd>
		<dd class="space">&nbsp;</dd>
		<dd class="textarea">
			<a href="#" class="cDP" id="iDP" nip="<?=$this->escape($this->nip)?>">Data Pokok |</a> 
			<a href="#" class="cDidik" id="iDidik" nip="<?=$this->escape($this->nip)?>">Riwayat Pendidikan |</a> 
			<a href="#" class="cLatih" id="iLatih" nip="<?=$this->escape($this->nip)?>">Pelatihan |</a> 
			<a href="#" class="cSeminar" id="iSeminar" nip="<?=$this->escape($this->nip)?>">Seminar |</a> 
			<a href="#" class="cPangkat" id="iPangkat" nip="<?=$this->escape($this->nip)?>">Riwayat Kepangkatan |</a> 
			<a href="#" class="cJabat" id="iJabat" nip="<?=$this->escape($this->nip)?>">Riwayat Jabatan |</a> 
			<a href="#" class="cSer" id="iSer" nip="<?=$this->escape($this->nip)?>">Sertifikasi |</a> 
			<a href="#" class="cOrg" id="iOrg" nip="<?=$this->escape($this->nip)?>">Organisasi |</a> 
			<a href="#" class="cHarga" id="iHarga" nip="<?=$this->escape($this->nip)?>">Penghargaan |</a> 
			<!--<a href="<?php echo $this->basePath; ?>/sdm/pegawai/sdmdatapegawaiupdate?nip=<?php echo $this->escape($this->nip)?>">Data Pokok |</a>           
			<a href="<?php echo $this->basePath; ?>/sdm/pegawai/sdmdatapegawaipendidikan?nip=<?php echo $this->escape($this->nip)?>">Riwayat Pendidikan |</a>
			<a href="<?php echo $this->basePath; ?>/sdm/pegawai/sdmdatapegawaipelatihan?nip=<?php echo $this->escape($this->nip)?>">Pelatihan |</a>
			<a href="<?php echo $this->basePath; ?>/sdm/pegawai/sdmdatapegawaikeluarga?nip=<?php echo $nip?>">Keluarga |</a>
			<a href="<?php echo $this->basePath; ?>/sdm/pegawai/sdmdatapegawaikeluarga?nip=<?php echo $nip?>">Keterangan |</a>
			<a href="<?php echo $this->basePath; ?>/sdm/pegawai/sdmdatapegawaikeluarga?nip=<?php echo $nip?>">Riwayat Kepangkatan |</a>  -->         
		</dd>
	</dl>
    <dl>
		<!--<dd class="col-left2">&nbsp;</dd>-->
		<dd class="dot2">&nbsp;</dd>
		<dd class="space">&nbsp;</dd>
		<dd class="space">&nbsp;</dd>
		<dd class="space">&nbsp;</dd>
		<dd class="space">&nbsp;</dd>
		<dd class="space">&nbsp;</dd>
		<dd class="textarea">
			<a href="#" class="cHukum" id="iHukum" nip="<?=$this->escape($this->nip)?>">Riwayat Hukuman |</a> 
			<a href="#" class="cLN" id="iLN" nip="<?=$this->escape($this->nip)?>">Ke Luar Negeri |</a> 
			<a href="#" class="cKet" id="iKet" nip="<?=$this->escape($this->nip)?>">Ciri-ciri Fisik |</a> 
			<a href="#" class="cKes" id="iKes" nip="<?=$this->escape($this->nip)?>">Riwayat Kesehatan |</a> 
			<a href="#" class="cKel" id="iKel" nip="<?=$this->escape($this->nip)?>">Keluarga |</a> 
			<a href="#" class="cKer" id="iKer" nip="<?=$this->escape($this->nip)?>">Orang Tua & Kerabat |</a> 
			<a href="#" class="cAlamat" id="iAlamat" nip="<?=$this->escape($this->nip)?>">Riwayat Alamat</a> 
			<!--<a href="#" class="acAmbilFoto" id="aiAmbilFoto" nip="<?=$this->escape($this->nip)?>">Ambil Foto</a>  
			<a href="<?php echo $this->basePath; ?>/sdm/pegawai/sdmdatapegawaipendidikan?nip=<?php echo $nip?>">Organisasi |</a>
			<a href="<?php echo $this->basePath; ?>/sdm/pegawai/sdmdatapegawaipelatihan?nip=<?php echo $nip?>">Seminar |</a>
			<a href="<?php echo $this->basePath; ?>/sdm/pegawai/sdmdatapegawaikeluarga?nip=<?php echo $nip?>">Penghargaan |</a>
			<a href="<?php echo $this->basePath; ?>/sdm/pegawai/sdmdatapegawaikeluarga?nip=<?php echo $nip?>">Riwayat Jabatan |</a>
			<a href="<?php echo $this->basePath; ?>/sdm/pegawai/sdmdatapegawaikeluarga?nip=<?php echo $nip?>">Riwayat Hukuman |</a>           
			<a href="<?php echo $this->basePath; ?>/sdm/pegawai/sdmdatapegawaikeluarga?nip=<?php echo $nip?>">Ke Luar Negeri |</a>           
	-->	</dd>
	</dl>
