<? require_once 'Zend/View.php';
   require_once 'share/oa_date.php'; 
   
	$ctrlDate = new oa_date();   
   
   $ctrlFrm = new Zend_View();
   $thnskrg = date("Y");


	//$jenjang = $_REQUEST['jenjang'];
	$nip = $_REQUEST['nip'];
	//echo "test".$test;

   $spath = $this->getScriptPaths();
   $this->addScriptPath($spath[0] . 'viewpegawai');
   echo $this->render('viewpegawaijs.phtml'); 


?>
<div class="contentdata-modul" id="modul">
	<div class="navlink">Halaman Utama Pegawai</div>
	<h3 class="title">MELIHAT DATA PENDIDIKAN</h3>
	&nbsp;&nbsp;&nbsp;&nbsp;Menu ini digunakan untuk melihat data riwayat pendidikan pegawai.
	<div class="spacer"></div>
	<a name="top"></a>	
	<div class="search-panel">
		<fieldset class="panel-form3">
				<?php include "menulink.phtml";?>  
				<?php include "datapokok.phtml";?>  
		</fieldset>
	</div> <!--end div Search Panel-->

	<div class="space-line">
		<div class="title2">Data Pendidikan</div>
		<fieldset  class="panel-form">	
			<form action="<?php echo $this->basePath; ?>/sdm/viewpegawai/pendidikanview" method="post">	  
				<dl>
					<dt>Jenjang</dt>
					<dd class="dot2">:</dd> 
					<dd class="col-right">
					<?php 
					  $nmJenjang = $this->escape($this->nmjenjang);
					  echo $nmJenjang;
					?>
					</dd>
				</dl>
				<dl>
					<dt>Nama Sekolah</dt>
					<dd class="dot2">:</dd> 
					<dd class="col-right">
					<?php 
						$pendidikan = $this->escape($this->pendidikan);
						echo $pendidikan;
					?>
					</dd>
				</dl>
				<dl>
					<dt>Jurusan</dt>
					<dd class="dot2">:</dd> 
					<dd class="col-right">
					<?php 
						$jurusan = $this->escape($this->jurusan);
						echo $jurusan;
					?>
					</dd>
				</dl>
				<dl>
					<dt>Alamat Sekolah</dt>
					<dd class="dot2">:</dd> 
					<dd class="col-right">
					<?php 
						$tempat = $this->escape($this->tempat);
						echo $tempat;
					?>
					</dd>
				</dl>
				<dl>
					<dt>Nama Pimpinan</dt>
					<dd class="dot2">:</dd> 
					<dd class="col-right">
					<?php 
						$kepSek = $this->escape($this->kepSek);
						echo $kepSek;
					?>
					</dd>
				</dl>
				<dl>
					<dt>Mulai</dt>
					<dd class="dot2">:</dd> 
					<dd class="col-right">
					<?php 
						$mulai = $this->escape($this->mulai);
						echo $mulai;
					?>
					</dd>
				</dl>
				<dl>
					<dt>Akhir</dt>
					<dd class="dot2">:</dd> 
					<dd class="col-right">
					<?php 
						$akhir = $this->escape($this->akhir);
						echo $akhir;
					?>
					</dd>
				</dl>
				<dl>
					<dt>IPK / Nilai Ijazah</dt>
					<dd class="dot2">:</dd> 
					<dd class="col-right">
					<?php 
						$ipk = $this->escape($this->ipk);
						if ($ipk == 0.00) {
							$ipk = $_POST['ipk'];
						}
						if ($ipk == '') {
							$ipk = 0.00;
						} 			
						echo $ipk;
					?>
					</dd>
				</dl>
				<dl>
					<dt>Sumber Biaya</dt>
					<dd class="dot2">:</dd> 
					<dd class="col-right">
					<?php 
					$biaya = $this->escape($this->biaya);
					if ($biaya == 'B') {
						$biaya = 'Beasiswa';
					}
					else if ($biaya == 'NB') {
						$biaya = 'Non Beasiswa';
					}
						echo $biaya;
					?>
					</dd>
				</dl>
				<dl>
					<dt>Nomor Ijazah</dt>
					<dd class="dot2">:</dd> 
					<dd class="col-right">
					<?php 
						$noIjazah = $this->escape($this->noIjazah);
						echo $noIjazah;
					 ?>
					</dd>
				</dl>
				<dl>
					<dt>Tanggal Ijazah</dt>
					<dd class="dot2">:</dd> 
					<dd class="col-right">
					<?php 
						$tglIjazah = $this->escape($this->tglIjazah);
						echo $ctrlDate->convertTglMachineToHuman($tglIjazah);
					 ?>
					</dd>
				</dl>
				<dl>
					<dt>Judul Skripsi</dt>
					<dd class="dot2">:</dd> 
					<dd class="col-right">
					<?php 
						$skripsi = $this->escape($this->skripsi);
						echo $skripsi;
					 ?>
					</dd>
				</dl>
				<dl>
					<dt>Keterangan</dt>
					<dd class="dot2">:</dd> 
					<dd class="col-right">
					<?php 
						$keterangan = $this->escape($this->keterangan);
						echo $keterangan;
					?>
				</dl>
 			<dl>
				<?php 
				  echo $ctrlFrm->formHidden('nipH', $nip, null)."&nbsp;";
				?>
				<dt>&nbsp;</dt>
				<dd class="dot2">&nbsp;</dd> 
				<dd class="col-right">&nbsp;</dd>			
				<div class="back" onClick="javascript:kembaliDidikView('<? echo $this->escape($this->nip); ?>');" title="Kembali"><input type="button" value="Kembali" id="kembaliDidikView"></div>
			</dl>
		  	</form>
		  	<div class="space-line"></div>
		  	<div><a href="#top" class="top" title="Kembali ke atas">Kembali ke atas</a></div>	  	
	         
		</fieldset>
	</div>
</div>		

<!--
<table border="0" align=center width=100%>		
		<tr>
		  <td >&nbsp;</td>
		</tr>
		<tr>
		  <td align="center">
			<?php 
			  echo $ctrlFrm->formHidden('nipH', $nip, null)."&nbsp;";
			?>
		  </td>
		</tr>
</table>
 		  
			<div class="back2">
			  <a href="#" onClick="javascript:kembaliDidikView('<? echo $this->escape($this->nip); ?>');" class="back" title="Kembali">Kembali</a>
			</div>
-->