<?
require_once 'Zend/View.php';
require_once 'share/format_date.php'; 
require_once 'share/format_page.php';
require_once "share/share_message.php";
require_once "share/oa_dec_cur_conv.php";

$ctrlFrm = new Zend_View();
$pesan = new share_message();
$halaman = new format_page();
$dec_cur = new oa_dec_cur_conv();
		
$currentPage = $this->currentPage;
$numToDisplay = $this->numToDisplay;

?>
<div class="navlink">
<a href="#" onclick="open_url_to_home('<?php echo $this->basePath; ?>/home/index/depan','<?php echo $this->basePath; ?>/home/index/main');">Halaman Utama</a>
</div>
<div class="panel">
	<div class="inner">
		<span class="corners-top"><span></span></span>
		<h2 class="title">Data Pengumuman</h2>
		<div class="search-panel">
			<form method="post" id="frmCariPengumuman" name="frmCariPengumuman">
<table width="100%" border="0" cellpadding="0" cellspacing="1" class="std">
	
</table>
<table width="50%" border="0" cellpadding="0" cellspacing="1" align="center">
<?
	$kategoriCari = array("n_nama" => "Nama","NIP" => "NIP","n_unitkerja" => "Unit Kerja");
	echo $ctrlFrm->formSelect('kategoriCari', $this->kategoriCari, null, $kategoriCari);						
?>
	<input type="text" name="carii" align="center">
				<?
			         $atribSubmit = array("onclick"=>"javascript:cariPengumuman();");
			         echo $ctrlFrm->formSubmit('cari', 'Search', $atribSubmit)."&nbsp;";
				?>
</table>

			</form>
		</div>
		<div class="space-line"></div>

		
		<fieldset class="fields"> 
			<div class="spacer"> </div>
			<? 
			
			$status = $this->hasil;
			$proses = $this->proses;
			$keterangan = $this->keterangan;
			
			$pesan->show_message($proses, $keterangan, "$status" ); ?>
			<div class="spacer"> </div>	
			
			<div class="add" title="Tambah Data" onClick="pengumumanForm('insert','');"></div> 

			<div class="blank"></div>
			
			
			<table id="sorter" class="sortable" cellspacing="1" cellpadding="2" border="0" align="center">
				<th class="nosort">No</th> 
				<th >Pengumuman</th>
				<th  colspan="2" class="nosort">Tindakan</th>
				
				<?
				if (count($this->pengumumanList) == 0){ 
				?>
					<tr class="event2"><td colspan="5"><font color="red">Data Tidak Ditemukan</font></td></tr>
				<?} else {
						
						
						$id_kegiatanx = '';

						foreach ($this->pengumumanList as $key => $val): 
						if ($key%2==0) { ?>
							<tr class="event">
						<? } else if ($key%2==1) { ?>
							<tr class="event2">
						<? } 

						$id = $this->escape($val['id']); 
						$e_pengumuman = $this->escape($val['e_pengumuman']); 
						$n_nama = $this->escape($val['n_nama']); 
						$n_gol = $this->escape($val['n_gol']); 
						$n_unitkerja = $this->escape($val['n_unitkerja']); 
						$n_rek = $this->escape($val['n_rek']); 
						if($NIP == '0'){$NIP ='';}
						$noUrut = (($currentPage -1)* $numToDisplay) + $key +1;
						
						if($flagMhs){$mode = 'update';}else{$mode = 'insert';}
						// form Hidden 
						echo $ctrlFrm->formHidden('id', $id, null);
						
						?>
						
						<td class="clcenter"><? echo $noUrut;?>&nbsp;&nbsp;</td>
						<td align = "justify">&nbsp;<? echo $e_pengumuman;?></td>
						
						<td><div onClick="pengumumanForm('update','<? echo $id;?>');" class="edit" title="Edit Data"></div></td>
						<td><div class="delete" title="Hapus Data" onClick="pengumumanHapus('pengumuman', '<? echo $id; ?>')" ></td>
						
						
					
						</tr>
					<?
					endforeach;
				}
				?>
			</table>
			<?	
			$totalData = $this->totpengumumanList;
			$modul = $this->basePath."/pengumuman/pengumuman/pengumumanlist";
			$param1 = $this->prodi;$param2 = $this->status;$param3 = $this->kegiatan;$param4 = $this->tahun;$param5 = $this->bulan;
			echo $halaman->showPage($totalData, $numToDisplay, $currentPage, 'tableview', $modul, $param1, $param2, $param3, $param4, $param5);		
			?>
		</fieldset>		 
		
		<span class="corners-bottom"><span></span></span>
	</div>
</div>
<script type="text/javascript">
var sorter=new table.sorter("sorter");
sorter.init("sorter",0);
</script>