<?
require_once 'Zend/View.php';
require_once 'share/format_date.php'; 
require_once 'share/format_page.php';
require_once "share/share_message.php";
require_once "share/oa_dec_cur_conv.php";

$ctrlFrm = new Zend_View();
$pesan = new share_message();
$halaman = new format_page();
$dec_cur = new oa_dec_cur_conv();
$format_date = new format_date();

$currentPage = $this->currentPage;
$numToDisplay = $this->numToDisplay;
?>
<div class="navlink">
<a href="#" onclick="open_url_to_home('<?php echo $this->basePath; ?>/home/index/depan','<?php echo $this->basePath; ?>/home/index/main');">Halaman Utama</a>
>> Data Pengguna
</div>

<div id="dialog-browse">  
</div>

<div class="panel">
	<div class="inner">
		<span class="corners-top"><span></span></span>
		<h2 class="title">FORM DATA PENGGUNA</h2>
	    <div class="spacer"></div> 
		
		<? if(strtolower($this->jenisForm) == 'insert') {$namaForm = 'frmtambahpengguna'; }
			else if (strtolower($this->jenisForm) == 'update') {$namaForm = 'frmubahpengguna'; }
			else {$namaForm = 'frmhapuspengguna'; }
		?>

		<form method="post" name="<? echo $namaForm;?>" id="<? echo $namaForm;?>">
<?
	$status = $this->hasil;
	$proses = $this->proses;
	$keterangan = $this->keterangan;
	$pesan->show_message($proses, $keterangan, "$status" ); 
?>
			<table width="100%" border="0" cellpadding="0" cellspacing="1" class="std">
<input name="userid" id="userid" type="hidden" value="<?echo $this->userid;?>" />
<input name="kategoriCari" id="kategoriCari" type="hidden" value="<?echo $this->kategoriCari;?>" />
<input name="carii" id="carii" type="hidden" value="<?echo $this->carii;?>" />
<input name="id_user" id="id_user" type="hidden" value="<?echo $this->detailPengguna['id_user'];?>" />

				<tr>
				    <td align="right" width="180">* Nama Pengguna :</td>
					<td>	
	<? 
	$usernameAttrib = array("id"=>"username","size" => 33,"maxlength" => 30 );
	echo $ctrlFrm->formText("username", $this->detailPengguna['username'], $usernameAttrib);
	?>
				</td>

				<tr>
				    <td align="right" width="180">* Nama Pengguna :</td>
					<td>	
	<? 
	$namaAttrib = array("id"=>"nama","size" => 53,"maxlength" => 50 );
	echo $ctrlFrm->formText("nama", $this->detailPengguna['nama'], $namaAttrib);
	?>
				</td>
				</tr>

	<tr>
	<td align="right" width="180">* Kelompok Pengguna :</td>
	<td>
	<?
	$groupList['0'] = '--Pilih--';
	$jmlgroupList = count($this->groupList);
		for ($i = 0; $i < $jmlgroupList; $i++) {
		$groupList[$this->groupList[$i]->id] = (string)$this->groupList[$i]->n_group;			 
		}
	
	$groupAtrib = array("id"=>"c_group", "tabindex"=>"17");
	echo $ctrlFrm->formSelect('c_group', trim($this->detailPengguna['c_group']), $groupAtrib, $groupList);
	?>
	</td>
	</tr>

	<tr>
				    <td align="right" width="180">* Password :</td>
					<td>
						<?
						$passwordAttrib = array("size" => 20,"maxlength" => 20);
						echo $ctrlFrm->formPassword('pass', '', $passwordAttrib);
						?>
					</td>
				</tr>
				<tr>
				    <td align="right" width="180">* Confirm Password :</td>
					<td>
						<input type="password"  size ="20" name="confirmPassword"  Value="<?php echo $password; ?>" userid="confirmPassword" >
					</td>
				</tr>

	<tr>
	<td align="right" width="180">* Status :</td>
	<td>
	<?
	$statusList['A'] = 'Aktif';
	$statusList['T'] = 'Tidak Aktif';
	
	$statusAtrib = array("id"=>"c_status", "tabindex"=>"17");
	echo $ctrlFrm->formSelect('c_status', trim($this->detailPengguna['c_status']), $statusAtrib, $statusList);
	?>
	</td>
	</tr>

					
				<tr>
				    <td></td>
				    <td>
						<div class="right">
<input type="button" value="Batal" onclick="penggunalist()"> 
<input type="reset" value="Ulangi"> 
<input   type="submit" value="Simpan">


						</div>
					</td>
				</tr>
				<tr>
				    <td>* Harus Diisi</td>
				    <td></td>
				</tr>
			</table>
		</form>
	</div>
</div>

<script>


function showDialog(val,jum) {      
    $( "#dialog-browse" ).dialog({
      autoOpen: false,
      height: 380,
      width: 640,
      modal: true,
      resizable:false,
      title: "Data"
    });
    if(val =='dosen'){dosenlist(jum);}  
    if(val =='prodi'){prodilist();}  
    return false;
  }

</script>

