<?
require_once 'Zend/View.php';
require_once 'share/format_date.php'; 
require_once 'share/format_page.php';
require_once "share/share_message.php";
require_once "share/oa_dec_cur_conv.php";

$ctrlFrm = new Zend_View();
$pesan = new share_message();
$halaman = new format_page();
$dec_cur = new oa_dec_cur_conv();
$format_date = new format_date();


$currentPage = $this->currentPage;
$numToDisplay = $this->numToDisplay;
?>
<div class="navlink">
<a href="#" onclick="open_url_to_home('<?php echo $this->basePath; ?>/home/index/depan','<?php echo $this->basePath; ?>/home/index/main');">Halaman Utama</a>
>>  Data Rekam Kelurahan
</div>
<div class="panel">
	<div class="inner">
		<span class="corners-top"><span></span></span>
		<h2 class="title">Data Kelurahan <strong><?php echo strtoupper($this->detailKelurahan->kelurahan) ?></strong> , Kode Kelurahan <? echo $this->kd_kel;?></h2>
		
			<form method="post" id="frmcarirekamkelurahan" name="frmcarirekamkelurahan">
				<input name="kd_kel" id="kd_kel" type="hidden" value="<?echo $this->kd_kel;?>" />
				Filter :
					<?
						$kategoriCari = array("P.tahun" => "Tahun", "P.bulan" => "Bulan");
						echo $ctrlFrm->formSelect('kategoriCari', $this->kategoriCari, null, $kategoriCari);						
					?>
					<input type="text" name="carii" id="carii" align="center" value ="<? echo $this->carii;?>">
					<?
						$atribSubmit = array("onclick"=>"javascript:carirekamkelurahan();");
						echo $ctrlFrm->formSubmit('cari', 'Search', $atribSubmit)."&nbsp;";
					?>
			</form>
		
<fieldset class="fields"> 
<? 
$status = $this->hasil;
$proses = $this->proses;
$pesan->show_message($proses, $kd_kel, "$status" ); 
?>

<table width="100%" border="0" cellpadding="0" cellspacing="1" class="std">
				</table>
<div class="add" title="Tambah Data" onClick="rekamkelurahanForm('insert','<? echo $this->kd_kel;?>','<? echo $this->lastPeriode->bulan;?>','<? echo $this->lastPeriode->tahun;?>');"></div>	

<table id="sorter" class="sortable" cellspacing="1" cellpadding="2" border="0" align="center">
				<th >No</th>
				<th >Bulan</th>
				<th >Tahun</th> 
				<th >Nama Lurah</th> 
				<th >NIP Lurah</th>
			
				
				
				<th colspan="3" class="nosort">FUNGSI</th>
				
				<?
				if (count($this->rekamkelurahanlist) == 0){ 
				?>
					<tr class="event2"><td colspan="7"  style="color:#8C0000; font-weight:bold; background-color: #FF9999">Data Tidak Ditemukan</td></tr>
				<?} else {
						
						
						foreach ($this->rekamkelurahanlist as $key => $val): 
						if ($key%2==0) { ?>
							<tr class="event">
						<? } else if ($key%2==1) { ?>
							<tr class="event2">
						<? }
						$kd_kel	= $this->escape($val['kd_kel']);						
						$tahun	= $this->escape($val['tahun']); 
						$bulan	= $this->escape($val['bulan']); 
						$nama_lurah	= $this->escape($val['nama_lurah']);
						$nip_lurah	= $this->escape($val['nip_lurah']);
						
						
						$noUrut = (($currentPage -1)* $numToDisplay) + $key +1;
						echo $ctrlFrm->formHidden('kd_kel', $kd_kel, null);
						
						?>
							
						<td align="center"><? echo $noUrut;?></td>
						<td align="center"><? echo $bulan;?></td>
						<td align="center"><? echo $tahun;?></td>
						<td class="clleft"><? echo $nama_lurah;?></td>
						<td class="clleft"><? echo $nip_lurah;?></td>
						

<td><div onClick="rekamkelurahanForm('print','<? echo $kd_kel;?>','<? echo $bulan;?>','<? echo $tahun;?>');" class="filedoc" title="cetak Data"></div></td>

<td><div onClick="rekamkelurahanForm('update','<? echo $kd_kel;?>','<? echo $bulan;?>','<? echo $tahun;?>');" class="view" title="Lihat Data"></div></td>
<td><div onClick="rekamkelurahanForm('update','<? echo $kd_kel;?>','<? echo $bulan;?>','<? echo $tahun;?>');" class="edit" title="Ubah Data"></div></td>
<td><div onClick="rekamkelurahanHapus('delete','<? echo $kd_kel;?>','<? echo $this->detailKelurahan->kelurahan ;?>','<? echo $tahun;?>','<? echo $bulan;?>');" class="delete" title="Hapus Data"></div>
						</td>
						
					
						</tr>
					<?
					endforeach;
				}
				?>
			</table>

			<?	
			$totalData = $this->totRekamkelurahanList;
			$modul = $this->basePath."/kelurahan/rekamkelurahan/rekamkelurahanlist";
			// $param1 = $this->cabang;$param2 = $this->tahun;$param3 = $this->bulan;$param4 = $this->jenis;$param5 = $this->status;
			echo $halaman->showPage($totalData, $numToDisplay, $currentPage, 'tableview', $modul, $param1, $param2, $param3, $param4);		
			
			?>
		</fieldset>		 
		
		<span class="corners-bottom"><span></span></span>
	</div>
</div>
<script type="text/javascript">
var sorter=new table.sorter("sorter");
sorter.init("sorter",0);
</script>

