<?
require_once 'Zend/View.php';
require_once 'share/format_date.php'; 
require_once 'share/format_page.php';
require_once "share/share_message.php";
require_once "share/oa_dec_cur_conv.php";

$ctrlFrm = new Zend_View();
$pesan = new share_message();
$halaman = new format_page();
$dec_cur = new oa_dec_cur_conv();
$format_date = new format_date();

$currentPage = $this->currentPage;
$numToDisplay = $this->numToDisplay;
?>
<div class="navlink">
<a href="#" onclick="open_url_to_home('<?php echo $this->basePath; ?>/home/index/depan','<?php echo $this->basePath; ?>/home/index/main');">Halaman Utama</a>
>> Data Kelurahan
</div>

<div id="dialog-browse">  
</div>

<div class="panel">
	<div class="inner">
		<span class="corners-top"><span></span></span>
		
		
		
		<? if(strtolower($this->jenisForm) == 'insert') {$namaForm = 'frmtambahrekamkelurahan'; $nama='tambah';}
			else if (strtolower($this->jenisForm) == 'update') {$namaForm = 'frmubahrekamkelurahan'; $nama='ubah'; }
			else {$namaForm = 'frmhapusrekamkelurahan';  $nama='hapus';}
		?>
		
		<h2 class="title">FORM <?php echo strtoupper($nama) ?> DATA KELURAHAN <strong><?php echo strtoupper($this->detailKelurahan->kelurahan) ?></strong></h2>
	    <div class="spacer"></div> 
		
		
<? echo $namaForm;?>
<form method="post" name="<? echo $namaForm;?>" id="<? echo $namaForm;?>" class="validasi">
<table width="100%" border="0" cellpadding="0" cellspacing="2" class="std">
	<input name="id" id="id" type="hidden" value="<?echo $this->id;?>" />

	<input name="kategoriCari" id="kategoriCari" type="hidden" value="<?echo $this->kategoriCari;?>" />
	<input name="carii" id="carii" type="hidden" value="<?echo $this->carii;?>" />
	<input name="kd_kel" id="kd_kel" type="hidden" value="<?echo $this->detailKelurahan->kd_kel;?>" />
	<input name="bulan" id="bulan" type="hidden" value="<?echo $this->bulan;?>" />
	<input name="tahun" id="tahun" type="hidden" value="<?echo $this->tahun;?>" />
	
<? 
$status = $this->hasil;
$proses = $this->proses;
$keterangan = $this->keterangan;
$pesan->show_message($proses, $keterangan, "$status" ); ?>

<script type="text/javascript">
$(function(){
	$("#tabs").tabs();
	});
</script>

<tr>
	<td colspan="4">
	<div id="tabs">
	<ul>
		<li><a href="#tabs-1">DATA UMUM</a></li>
		<li><a href="#tabs-2" onClick="labForm('insert','<? echo $this->id;?>');" >DATA PERSONIL</a></li>
		<li><a href="#tabs-3" onClick="fotoForm('insert','<? echo $this->id;?>');" >DATA KEWENANGAN</a></li>
		<li><a href="#tabs-4" onClick="fotoForm('insert','<? echo $this->id;?>');" >DATA KEUANGAN</a></li>
		<li><a href="#tabs-5" onClick="fotoForm('insert','<? echo $this->id;?>');" >KELEMBAGAAN</a></li>
		<li><a href="#tabs-6" onClick="fotoForm('insert','<? echo $this->id;?>');" >KETENTRAMAN DAN KETERTIBAN</a></li>
		
	</ul>
<div id="tabs-1"> <!-- DATA UMUM -->
<table width="100%" border="0" cellpadding="0" cellspacing="1" class="std">
	
	<tr>
		<td align="right" >* Kode Kelurahan :</td>
		<td>	
		<input name="kd_kel" id="kd_kel" type="text" value="<?echo $this->kd_kel;?>" readonly />
		
		<!--input type="button" value="Cari" onClick="showDialog('pasien');"-->
			</td>
	</tr>
	<tr>
		<td>
			Pilih Bulan dan Tahun
		</td>
		<td>
			<select name="bulan" class="kecil">
				<option selected="selected">Bulan</option>
				<?php
				echo date('m');
				$bulan_ind=array("Januari","Februari","Maret","April","Mei","Juni","Juli","Agustus","September","Oktober","November","Desember");
				$bulan=array("1","2","3","4","5","6","7","8","9","10","11","12");
				$jlh_bln=count($bulan_ind);
				for($c=0; $c<$jlh_bln; $c+=1){
					if(date('mm') == $bulan[$c]){
						echo"<option value=$bulan[$c] selected='selected'> $bulan_ind[$c] </option>";
					}else
					echo"<option value=$bulan[$c]> $bulan_ind[$c] </option>";
				}
				?>
				</select>
				<select name="tahun" class="kecil">
				<option selected="selected">Tahun</option>
				<?php
				for($i=date('Y'); $i>=2010; $i-=1){
				echo"<option value=$i> $i </option>";
				}
				?>
				</select>
		</td>
	</tr>
	
	<tr>
		<td width="275px" align="right" >* 1. Tipologi Kelurahan :</td>
		<td width="400px" >&nbsp;</td>
		<td width="20px" ></td>
	</tr>
	<tr>
		
		<?php 
		$tipologi=explode(",",$this->tipologi->tipologi);
		?>
					 
		<td align="right" >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <input type="checkbox" name="tipologi[]" id="tipologi" value="Persawahan" <?php if(in_array("Persawahan",$tipologi)) { ?> checked="checked" <?php } ?>> a. Persawahan</td>		
	</tr>
	<tr>
		<td align="right" >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <input type="checkbox" name="tipologi[]" id="tipologi" value="Perladangan"<?php if(in_array("Perladangan",$tipologi)) { ?> checked="checked" <?php } ?>> b. Perladangan</td>		
	</tr>
	<tr>
		<td align="right" >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <input type="checkbox" name="tipologi[]" id="tipologi" value="Perkebunan"<?php if(in_array("Perkebunan",$tipologi)) { ?> checked="checked" <?php } ?>> c. Perkebunan</td>
	</tr>
	<tr>
		<td align="right" >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <input type="checkbox" name="tipologi[]" id="tipologi" value="Peternakan"<?php if(in_array("Peternakan",$tipologi)) { ?> checked="checked" <?php } ?>> d. Peternakan</td>
	</tr>
	
	<tr>
		<td align="right" >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <input type="checkbox" name="tipologi[]" id="tipologi" value="Nelayan"<?php if(in_array("Nelayan",$tipologi)) { ?> checked="checked" <?php } ?>> e. Nelayan</td>
	</tr>
	<tr>
		<td align="right" >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <input type="checkbox" name="tipologi[]" id="tipologi" value="Pertambangan"<?php if(in_array("Pertambangan",$tipologi)) { ?> checked="checked" <?php } ?>> f. Pertambangan / Galian </tr>
	<tr>
		<td align="right" >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <input type="checkbox" name="tipologi[]" id="tipologi" value="Kerajinan"<?php if(in_array("Kerajinan",$tipologi)) { ?> checked="checked" <?php } ?>> g. Kerajinan dan industri kecil</td>
	</tr>
	
	<tr>
		<td align="right" >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <input type="checkbox" name="tipologi[]" id="tipologi" value="Industri"<?php if(in_array("Industri",$tipologi)) { ?> checked="checked" <?php } ?>> h. Industri sedang dan besar :</td>
	</tr>
	
	<tr>
		<td align="right" >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <input type="checkbox" name="tipologi[]" id="tipologi" value="Jasa"<?php if(in_array("Jasa",$tipologi)) { ?> checked="checked" <?php } ?>> i. Jasa dan Perdagangan :</td>
	</tr>
	<!--KELURAHAN-->
	<tr>
		<td align="right" >* 2. Luas Wilayah :</td>
		<td>	
				<? 
				$luasAttrib = array("size" => 50,"maxlength" => 50, "required"=>"requried","digits"=>"true");
				echo $ctrlFrm->formText("luas", $this->detailKelurahan->luas, $luasAttrib);
				?> km
		</td>
	</tr>
	
	
	<tr>
		<td align="right" >3. Batas Wilayah :</td>
		<td>	
		<tr>
				<td align="right" >&nbsp;&nbsp;&nbsp; 1. Sebelah Utara :</td>
				<td align="center">
					<? 
						$batas_utaraAttrib = array("size" => 50,"maxlength" => 50, "required"=>"requried");
						echo $ctrlFrm->formText("batas_utara", $this->detailKelurahan->batas_utara, $batas_utaraAttrib);
					?>
				</td>
			</tr>
			<tr>
				<td align="right" >&nbsp;&nbsp;&nbsp; 2. Sebelah Selatan :</td>
				<td align="center">
					<? 
						$batas_selatanAttrib = array("size" => 50,"maxlength" => 50, "required"=>"requried");
						echo $ctrlFrm->formText("batas_selatan", $this->detailKelurahan->batas_selatan, $batas_selatanAttrib);
					?>
				</td>
			</tr>
			<tr>
				<td align="right" >&nbsp;&nbsp;&nbsp;3. Sebelah Barat :</td>
				<td align="center">
					<? 
						$batas_baratAttrib = array("size" => 50,"maxlength" => 50, "required"=>"requried");
						echo $ctrlFrm->formText("batas_barat", $this->detailKelurahan->batas_barat, $batas_baratAttrib);
					?>
				</td>
			</tr>
			<tr>
				<td align="right" >&nbsp;&nbsp;&nbsp;4. Sebelah Timur :</td>
				<td align="center">
					<? 
						$batas_timurAttrib = array("size" => 50,"maxlength" => 50, "required"=>"requried");
						echo $ctrlFrm->formText("batas_timur", $this->detailKelurahan->batas_timur, $batas_timurAttrib);
					?>
				</td>
			</tr>
			
		</td>
	</tr>
	
	<tr>
		<td colspan="2" align="right" >4. Orbitrasi (Jarak dari Pusat Pemerintahan) :</td>
		<td></td>
	</tr>		
		
	<tr>
		<td align="right" >&nbsp;&nbsp;&nbsp; Jarak dari Pusat Pemerintahan Kecamatan :</td>
		<td align="center">
			<? 
				$jarak_dari_kecamatanAttrib = array("placeholder"=>"Diisi hanya dengan angka. Misal: 5000000",  "size" => 50,"maxlength" => 50, "required"=>"requried","digits"=>"true");
				echo $ctrlFrm->formText("jarak_dari_kecamatan", $this->detailKelurahan->jarak_dari_kecamatan, $jarak_dari_kecamatanAttrib);
			?> km
		</td>
	</tr>
	
	<tr>
		<td align="right" >&nbsp;&nbsp;&nbsp; Jarak dari Pusat Pemerintahan Kota :</td>
		<td align="center">
			<? 
				$jarak_dari_kotaAttrib = array("placeholder"=>"Diisi hanya dengan angka. Misal: 5000000",  "size" => 50,"maxlength" => 50, "required"=>"requried","digits"=>"true");
				echo $ctrlFrm->formText("jarak_dari_kota", $this->detailKelurahan->jarak_dari_kota, $jarak_dari_kotaAttrib);
			?>  km
		</td>
	</tr>
	<tr>
		<td align="right" >&nbsp;&nbsp;&nbsp; Jarak dari Kota/Ibukota Kabupaten:</td>
		<td align="center">
			<? 
				$jarak_dari_ibukota_kotaAttrib = array("placeholder"=>"Diisi hanya dengan angka. Misal: 5000000",  "size" => 50,"maxlength" => 50, "required"=>"requried","digits"=>"true");
				echo $ctrlFrm->formText("jarak_dari_ibukota_kota", $this->detailKelurahan->jarak_dari_ibukota_kota, $jarak_dari_ibukota_kotaAttrib);
			?>  km
		</td>
	</tr>
	<tr>
		<td align="right" >&nbsp;&nbsp;&nbsp; Jarak dari Ibukota Provinsi :</td>
		<td align="center">
			<? 
				$jarak_dari_ibukota_provAttrib = array("placeholder"=>"Diisi hanya dengan angka. Misal: 5000000",  "size" => 50,"maxlength" => 50, "required"=>"requried","digits"=>"true");
				echo $ctrlFrm->formText("jarak_dari_ibukota_prov", $this->detailKelurahan->jarak_dari_ibukota_prov, $jarak_dari_ibukota_provAttrib);
			?>  km
		</td>
	</tr>	
	<!--End KELURAHAN-->
	
	<!--UMUM-->
	<tr>
		<td align="right" >5. Jumlah Penduduk :</td>
		<td><? 
				$jml_jiwaAttrib = array("placeholder"=>"Diisi hanya dengan angka. Misal: 5000000",  "size" => 25,"maxlength" => 25, "required"=>"requried","digits"=>"true", "class"=>"kecil","digits"=>"true");
				echo $ctrlFrm->formText("jml_jiwa", $this->detailUmum['jml_jiwa'], $jml_jiwaAttrib);
			?>   jiwa 
			<? 
				$jml_kkAttrib = array("placeholder"=>"Diisi hanya dengan angka. Misal: 5000000",  "size" => 25,"maxlength" => 25, "required"=>"requried","digits"=>"true" ,"class"=>"kecil");
				echo $ctrlFrm->formText("jml_kk", $this->detailUmum['jml_kk'], $jml_kkAttrib);
			?>  kk
		</td>
	
	</tr>
	
	<tr>
		<td align="right" >&nbsp;&nbsp;&nbsp; Laki-laki :</td>
		<td align="center">
			<? 
				$jml_lakiAttrib = array("placeholder"=>"Diisi hanya dengan angka. Misal: 5000000",  "size" => 25,"maxlength" => 25, "required"=>"requried","digits"=>"true");
				echo $ctrlFrm->formText("jml_laki", $this->detailUmum['jml_laki'], $jml_lakiAttrib);
			?>  Jiwa
		</td>
	</tr>

	<tr>
		<td align="right" >&nbsp;&nbsp;&nbsp; Perempuan :</td>
		<td align="center">
			<? 
				$jml_perempuanAttrib = array("placeholder"=>"Diisi hanya dengan angka. Misal: 5000000",  "size" => 25,"maxlength" => 25, "required"=>"requried","digits"=>"true");
				echo $ctrlFrm->formText("jml_perempuan", $this->detailUmum['jml_perempuan'], $jml_perempuanAttrib);
			?>  Jiwa
		</td>
	</tr>
	<tr>
		<td align="right" >&nbsp;&nbsp;&nbsp; Usia 0-15 :</td>
		<td align="center">
			<? 
				$jml_0_15Attrib = array("placeholder"=>"Diisi hanya dengan angka. Misal: 5000000",  "size" => 25,"maxlength" => 25, "required"=>"requried","digits"=>"true");
				echo $ctrlFrm->formText("jml_0_15", $this->detailUmum['jml_0_15'], $jml_0_15Attrib);
			?>  Jiwa
		</td>
	</tr>
	<tr>
		<td align="right" >&nbsp;&nbsp;&nbsp; Usia 15-65:</td>
		<td align="center">
			<? 
				$jml_15_65Attrib = array("placeholder"=>"Diisi hanya dengan angka. Misal: 5000000",  "size" => 25,"maxlength" => 25, "required"=>"requried","digits"=>"true");
				echo $ctrlFrm->formText("jml_15_65", $this->detailUmum['jml_15_65'], $jml_15_65Attrib);
			?>  Jiwa
		</td>
	</tr>
	<tr>
		<td align="right" >&nbsp;&nbsp;&nbsp; Usia 65 ke-atas:</td>
		<td align="center">
			<? 
				$jml_65_keatasAttrib = array("placeholder"=>"Diisi hanya dengan angka. Misal: 5000000",  "size" => 25,"maxlength" => 25, "required"=>"requried","digits"=>"true");
				echo $ctrlFrm->formText("jml_65_keatas", $this->detailUmum['jml_65_keatas'], $jml_65_keatasAttrib);
			?>  Jiwa
		</td>
	</tr>
			
	<tr>
		<td colspan="2" align="right" >6. Pekerjaan / Mata Pencaharian :</td>
	</tr>
	<tr>
		<td align="right" >&nbsp;&nbsp;&nbsp; a. Karyawan :</td>
	</tr>
	
	<tr>
		<td align="right" >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 1. Pegawai Negeri Asli :</td>
		<td>
			<? 
				$jml_pnsAttrib = array("placeholder"=>"Diisi hanya dengan angka. Misal: 5000000",  "size" => 25,"maxlength" => 25, "required"=>"requried","digits"=>"true");
				echo $ctrlFrm->formText("jml_pns", $this->detailUmum['jml_pns'], $jml_pnsAttrib);
			?>  Jiwa
		</td>
	</tr>
	
	<tr>
		<td align="right" >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  2. ABRI :</td>
		<td>
			<? 
				$jml_abriAttrib = array("placeholder"=>"Diisi hanya dengan angka. Misal: 5000000",  "size" => 25,"maxlength" => 25, "required"=>"requried","digits"=>"true");
				echo $ctrlFrm->formText("jml_abri", $this->detailUmum['jml_abri'], $jml_abriAttrib);
			?>  Jiwa
		</td>
	</tr>
	<tr>
		<td align="right" >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 3. Swasta</td>
		<td>
			<? 
				$jml_swastaAttrib = array("placeholder"=>"Diisi hanya dengan angka. Misal: 5000000",  "size" => 25,"maxlength" => 25, "required"=>"requried","digits"=>"true");
				echo $ctrlFrm->formText("jml_swasta", $this->detailUmum['jml_swasta'], $jml_swastaAttrib);
			?>  Jiwa
		</td>
	</tr>
	
	<tr>
		<td align="right" >&nbsp;&nbsp;&nbsp; b. Wiraswasta / Pedagang</td>
		<td>	
			<? 
				$jml_wiraswastaAttrib = array("placeholder"=>"Diisi hanya dengan angka. Misal: 5000000",  "size" => 25,"maxlength" => 25, "required"=>"requried","digits"=>"true");
				echo $ctrlFrm->formText("jml_wiraswasta", $this->detailUmum['jml_wiraswasta'], $jml_wiraswastaAttrib);
			?>  Jiwa
	</td>
	</tr>
	
	<tr>
		<td align="right" >&nbsp;&nbsp;&nbsp; c. Tani</td>
		<td>	
			<? 
				$jml_taniAttrib = array("placeholder"=>"Diisi hanya dengan angka. Misal: 5000000",  "size" => 25,"maxlength" => 25, "required"=>"requried","digits"=>"true");
				echo $ctrlFrm->formText("jml_tani", $this->detailUmum['jml_tani'], $jml_taniAttrib);
			?>  Jiwa
		</td>
	</tr>
				
	<tr>
	    <td align="right" >&nbsp;&nbsp;&nbsp; d. Pertukangan</td>
		<td>	
			<? 
				$jml_pertukanganAttrib = array("placeholder"=>"Diisi hanya dengan angka. Misal: 5000000",  "size" => 25,"maxlength" => 25, "required"=>"requried","digits"=>"true");
				echo $ctrlFrm->formText("jml_pertukangan", $this->detailUmum['jml_pertukangan'], $jml_pertukanganAttrib);
			?>  Jiwa
		</td>
	</tr>
				
	<tr>
	    <td align="right" >&nbsp;&nbsp;&nbsp; e. Buruh Tani:</td>
		<td>	
			<? 
				$jml_buruh_taniAttrib = array("placeholder"=>"Diisi hanya dengan angka. Misal: 5000000",  "size" => 25,"maxlength" => 25, "required"=>"requried","digits"=>"true");
				echo $ctrlFrm->formText("jml_buruh_tani", $this->detailUmum['jml_buruh_tani'], $jml_buruh_taniAttrib);
			?>  Jiwa
		</td>
	</td>
	</tr>

	<tr>
		<td align="right" >&nbsp;&nbsp;&nbsp; f.Pensiunan :</td>
		<td>	
			<? 
				$jml_pensiunanAttrib = array("placeholder"=>"Diisi hanya dengan angka. Misal: 5000000",  "size" => 25,"maxlength" => 25, "required"=>"requried","digits"=>"true");
				echo $ctrlFrm->formText("jml_pensiunan", $this->detailUmum['jml_pensiunan'], $jml_pensiunanAttrib);
			?>  Jiwa
	</td>
	</tr>

	<tr>
		<td align="right" >&nbsp;&nbsp;&nbsp; g. Nelayan :</td>
		<td>	
			<? 
				$jml_nelayanAttrib = array("placeholder"=>"Diisi hanya dengan angka. Misal: 5000000",  "size" => 25,"maxlength" => 25, "required"=>"requried","digits"=>"true");
				echo $ctrlFrm->formText("jml_nelayan", $this->detailUmum['jml_nelayan'], $jml_nelayanAttrib);
			?>  Jiwa
	</td>
	</tr>

	<tr>
		<td align="right" >&nbsp;&nbsp;&nbsp; h. Pemulung :</td>
		<td>	
			<? 
				$jml_pemulungAttrib = array("placeholder"=>"Diisi hanya dengan angka. Misal: 5000000",  "size" => 25,"size" => 50,"maxlength" => 50, "required"=>"number");
				echo $ctrlFrm->formText("jml_pemulung", $this->detailUmum['jml_pemulung'], $jml_pemulungAttrib);
			?> jiwa
		</td>
	</tr>

	<tr>
		<td align="right" >&nbsp;&nbsp;&nbsp; i. Jasa :</td>
		<td>	
			<? 
				$jml_jasaAttrib = array("placeholder"=>"Diisi hanya dengan angka. Misal: 5000000",  "size" => 50,"maxlength" => 50, "required"=>"requried");
				echo $ctrlFrm->formText("jml_jasa", $this->detailUmum['jml_jasa'], $jml_jasaAttrib);
			?> jiwa
		</td>
	</tr>

	<tr>
		<td colspan="2" align="right" >7. Tingkat Pendidikan Masyarakat</td>
		
	</tr>	

	<tr>
		<td colspan="2" align="right" >&nbsp;&nbsp;&nbsp; a. Lulusan Pendidikan Umum :</td>
		<td>	</td>
	</tr>		


	<tr>
		<td align="right" >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  1. Taman Kanak-kanak :</td>
		<td>	
			<? 
				$jml_lulusan_tkAttrib = array("placeholder"=>"Diisi hanya dengan angka. Misal: 5000000",  "size" => 25,"size" => 50,"maxlength" => 50, "required"=>"requried");
				echo $ctrlFrm->formText("jml_lulusan_tk", $this->detailUmum['jml_lulusan_tk'], $jml_lulusan_tkAttrib);
			?> jiwa
	</td>
	</tr>		


	<tr>
		<td align="right" >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 2. Sekolah Dasar :</td>
		<td>	
			<? 
				$jml_lulusan_sdAttrib = array("placeholder"=>"Diisi hanya dengan angka. Misal: 5000000",  "size" => 25,"size" => 50,"maxlength" => 50, "required"=>"requried");
				echo $ctrlFrm->formText("jml_lulusan_sd", $this->detailUmum['jml_lulusan_sd'], $jml_lulusan_sdAttrib);
			?> jiwa
	</td>
	</tr>

	<tr>
		<td align="right" >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 3. SMP :</td>
		<td>	
			<? 
				$jml_lulusan_smpAttrib = array("placeholder"=>"Diisi hanya dengan angka. Misal: 5000000",  "size" => 25,"size" => 50,"maxlength" => 50, "required"=>"requried");
				echo $ctrlFrm->formText("jml_lulusan_smp", $this->detailUmum['jml_lulusan_smp'], $jml_lulusan_smpAttrib);
			?> jiwa
	</td>
	</tr>

	<tr>
		<td align="right" >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 4. SMA/SMU :</td>
		<td>	
			<? 
				$jml_lulusan_smaAttrib = array("placeholder"=>"Diisi hanya dengan angka. Misal: 5000000",  "size" => 25,"size" => 50,"maxlength" => 50, "required"=>"requried");
				echo $ctrlFrm->formText("jml_lulusan_sma", $this->detailUmum['jml_lulusan_sma'], $jml_lulusan_smaAttrib);
			?> jiwa
	</td>
	</tr>

	<tr>
		<td align="right" >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 5. Akademi /D1-D3 :</td>
		<td>	
			<? 
				$jml_lulusan_diplomaAttrib = array("placeholder"=>"Diisi hanya dengan angka. Misal: 5000000",  "size" => 50,"maxlength" => 50, "required"=>"requried");
				echo $ctrlFrm->formText("jml_lulusan_diploma", $this->detailUmum['jml_lulusan_diploma'], $jml_lulusan_diplomaAttrib);
			?> jiwa
		</td>
	</tr>
				
	<tr>
		<td align="right" >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 6. Sarjana :</td>
		<td>	
			<? 
				$jml_lulusan_sarjanaAttrib = array("placeholder"=>"Diisi hanya dengan angka. Misal: 5000000",  "size" => 50,"maxlength" => 50, "required"=>"requried");
				echo $ctrlFrm->formText("jml_lulusan_sarjana", $this->detailUmum['jml_lulusan_sarjana'], $jml_lulusan_sarjanaAttrib);
			?> jiwa
		</td>
	</tr>
				
				
	<tr>
		<td align="right" >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 7. Pascasarjana :</td>
		<td>	
			<? 
				$jml_lulusan_pascasarjanaAttrib = array("placeholder"=>"Diisi hanya dengan angka. Misal: 5000000",  "size" => 50,"maxlength" => 50, "required"=>"requried");
				echo $ctrlFrm->formText("jml_lulusan_pascasarjana", $this->detailUmum['jml_lulusan_pascasarjana'], $jml_lulusan_pascasarjanaAttrib);
			?> jiwa
		</td>
	</tr>
				
	<tr>
		<td align="right" >&nbsp;&nbsp;&nbsp; b. Lulusan Pendidikan Khusus :</td>
		<td> </td>				
	</tr>
				
	<tr>
		<td align="right" >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;1. Pondok Pesantren :</td>
		<td>	
			<? 
				$jml_lulusan_pontrenAttrib = array("placeholder"=>"Diisi hanya dengan angka. Misal: 5000000",  "size" => 50,"maxlength" => 50, "required"=>"requried");
				echo $ctrlFrm->formText("jml_lulusan_pontren", $this->detailUmum['jml_lulusan_pontren'], $jml_lulusan_pontrenAttrib);
			?> jiwa
		</td>
	</tr>
				
	<tr>
		<td align="right" >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;2. Pendidikan Keagamaan :</td>
		<td>	
			<? 
				$jml_lulusan_keagamaanAttrib = array("placeholder"=>"Diisi hanya dengan angka. Misal: 5000000",  "size" => 50,"maxlength" => 50, "required"=>"requried");
				echo $ctrlFrm->formText("jml_lulusan_keagamaan", $this->detailUmum['jml_lulusan_keagamaan'], $jml_lulusan_keagamaanAttrib);
			?> jiwa
		</td>
	</tr>
				
	<tr>
		<td align="right" >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;3. Sekolah Luar Biasa:</td>
		<td>	
			<? 
				$jml_lulusan_slbAttrib = array("placeholder"=>"Diisi hanya dengan angka. Misal: 5000000",  "size" => 50,"maxlength" => 50, "required"=>"requried");
				echo $ctrlFrm->formText("jml_lulusan_slb", $this->detailUmum['jml_lulusan_slb'], $jml_lulusan_slbAttrib);
			?>	jiwa
		</td>
	</tr>
	
	<tr>
		<td align="right" >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;4. Kursus Keterampilan:</td>
		<td>	
			<? 
				$jml_lulusan_kursusAttrib = array("placeholder"=>"Diisi hanya dengan angka. Misal: 5000000",  "size" => 50,"maxlength" => 50, "required"=>"requried");
				echo $ctrlFrm->formText("jml_lulusan_kursus", $this->detailUmum['jml_lulusan_kursus'], $jml_lulusan_kursusAttrib);
			?>	jiwa
		</td>
	</tr>
	
	<tr>
		<td align="right" >8. Jumlah Penduduk Miskin:</td>
		<td>	
			<? 
				$jml_jiwa_miskinAttrib = array("placeholder"=>"Diisi hanya dengan angka. Misal: 5000000",  "size" => 50,"maxlength" => 50, "required"=>"requried","class"=>"kecil");
				echo $ctrlFrm->formText("jml_jiwa_miskin", $this->detailUmum['jml_jiwa_miskin'], $jml_jiwa_miskinAttrib);
			?> jiwa
			<? 
				$jml_jiwa_kkAttrib = array("placeholder"=>"Diisi hanya dengan angka. Misal: 5000000",  "size" => 50,"maxlength" => 50, "required"=>"requried","class"=>"kecil");
				echo $ctrlFrm->formText("jml_jiwa_kk", $this->detailUmum['jml_jiwa_kk'], $jml_jiwa_kkAttrib);
			?>  KK
		</td>
	</tr>
	<tr>
		<td align="right" >(menurut standar BPS)</td>
		<td></td>
	</tr>
	
	<tr>
		<td align="right" >9. UMR Kabupaten / Kota:</td>
		<td>	
			Rp &nbsp;
			<? 
				$umrAttrib = array("placeholder"=>"Diisi hanya dengan angka. Misal: 5000000",  "size" => 50,"maxlength" => 50, "required"=>"requried");
				echo $ctrlFrm->formText("umr", $this->detailUmum['umr'], $umrAttrib);
			?> 
		</td>
	</tr>
	
	<tr>
		<td colspan="2"align="right" >10. Sarana Prasarana</td>
		<td>	
		</td>
	</tr>
	
	<tr>
		<td align="right" >&nbsp;&nbsp;&nbsp; a. Kantor Kelurahan:</td>
		<td>	
				<input type="radio" name="sarana_kantor" id="sarana_kantor" value="semi" <?php if($this->tipologi->sarana_kantor=="semi") { ?> checked="checked" <?php } ?>> Semi Permanen /
				<input type="radio" name="sarana_kantor" id="sarana_kantor" value="permanen" <?php if($this->tipologi->sarana_kantor=="permanen") { ?> checked="checked" <?php } ?>> Permanen
		</td>
	</tr>
	
	<tr>
		<td align="right" >&nbsp;&nbsp;&nbsp; b. Prasarana Kesehatan:</td>
		<td></td>
	</tr>
	
	<tr>
		<td align="right" >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 1. Puskesmas:</td>
		<td>	
				<input type="radio" name="sarana_puskesmas" id="sarana_puskesmas" value="ada" <?php if($this->tipologi->sarana_puskesmas=="ada") { ?> checked="checked" <?php } ?>> ada /
				<input type="radio" name="sarana_puskesmas" id="sarana_puskesmas" value="tidak" <?php if($this->tipologi->sarana_puskesmas=="tidak") { ?> checked="checked" <?php } ?>> tidak
		</td>
	</tr>
	
	<tr>
		<td align="right" >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 2. UKBM /Posyandu:</td>
		<td>	
			<? 
				$sarana_jml_posyanduAttrib = array("placeholder"=>"Diisi hanya dengan angka. Misal: 5000000",  "size" => 50,"maxlength" => 50, "required"=>"requried");
				echo $ctrlFrm->formText("sarana_jml_posyandu", $this->detailUmum['sarana_jml_posyandu'], $sarana_jml_posyanduAttrib);
			?>  buah
		</td>
	</tr>
	
	<tr>
		<td align="right" >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 3. Poliklinik / Balai Pelayanan <br />Masyarat:</td>
		<td>	
			<? 
				$sarana_jml_poliklinikAttrib = array("placeholder"=>"Diisi hanya dengan angka. Misal: 5000000",  "size" => 50,"maxlength" => 50, "required"=>"requried");
				echo $ctrlFrm->formText("sarana_jml_poliklinik", $this->detailUmum['sarana_jml_poliklinik'], $sarana_jml_poliklinikAttrib);
			?> buah
		</td>
	</tr>
	
	<tr>
		<td align="right" >&nbsp;&nbsp;&nbsp; c. Prasarana Pendidikan:</td>
		<td></td>
	</tr>
	
	<tr>
		<td align="right" >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 1. Gedung Sekolah PAUD:</td>
		<td>	
					<? 
				$sarana_jml_paudAttrib = array("placeholder"=>"Diisi hanya dengan angka. Misal: 5000000",  "size" => 50,"maxlength" => 50,"required"=>"required");
				echo $ctrlFrm->formText("sarana_jml_paud", $this->detailUmum['sarana_jml_paud'], $sarana_jml_paudAttrib);
			?>  buah
		</td>
	</tr>
	
	<tr>
		<td align="right" >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 2. Gedung Sekolah TK:</td>
		<td>	
			<? 
				$sarana_jml_tkAttrib = array("placeholder"=>"Diisi hanya dengan angka. Misal: 5000000",  "size" => 50,"maxlength" => 50,"required"=>"required");
				echo $ctrlFrm->formText("sarana_jml_tk", $this->detailUmum['sarana_jml_tk'], $sarana_jml_tkAttrib);
			?>  buah
		</td>
	</tr>
	
	<tr>
		<td align="right" >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 3. Gedung Sekolah SD:</td>
		<td>	
			<? 
				$sarana_jml_sdAttrib = array("placeholder"=>"Diisi hanya dengan angka. Misal: 5000000",  "size" => 50,"maxlength" => 50,"required"=>"required");
				echo $ctrlFrm->formText("sarana_jml_sd", $this->detailUmum['sarana_jml_sd'], $sarana_jml_sdAttrib);
			?>  buah
		</td>
	</tr>
	
	<tr>
		<td align="right" >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 4. Gedung Sekolah SMP:</td>
		<td>	
			<? 
				$sarana_jml_smpAttrib = array("placeholder"=>"Diisi hanya dengan angka. Misal: 5000000",  "size" => 50,"maxlength" => 50,"required"=>"required");
				echo $ctrlFrm->formText("sarana_jml_smp", $this->detailUmum['sarana_jml_smp'], $sarana_jml_smpAttrib);
			?>  buah
		</td>
	</tr>
					
	<tr>
		<td align="right" >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 5. Gedung Sekolah SMA:</td>
		<td>	
			<? 
				$sarana_jml_smaAttrib = array("placeholder"=>"Diisi hanya dengan angka. Misal: 5000000",  "size" => 50,"maxlength" => 50,"required"=>"required");
				echo $ctrlFrm->formText("sarana_jml_sma", $this->detailUmum['sarana_jml_sma'], $sarana_jml_smaAttrib);
			?>  buah
		</td>
	</tr>
					
	<tr>
		<td align="right" >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 6. Gedung Perguruan Tinggi:</td>
		<td>	
			<? 
				$sarana_jml_ptAttrib = array("placeholder"=>"Diisi hanya dengan angka. Misal: 5000000",  "size" => 50,"maxlength" => 50,"required"=>"required");
				echo $ctrlFrm->formText("sarana_jml_pt", $this->detailUmum['sarana_jml_pt'], $sarana_jml_ptAttrib);
			?>  buah
		</td>
	</tr>
					
	<tr>
		<td align="right" >&nbsp;&nbsp;&nbsp; d. Prasarana Ibadah:</td>
		<td></td>
	</tr>
	
	<tr>
		<td align="right" >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 1. Mesjid:</td>
		<td>	
			<? 
				$sarana_jml_masjidAttrib = array("placeholder"=>"Diisi hanya dengan angka. Misal: 5000000",  "size" => 50,"maxlength" => 50,"required"=>"required");
				echo $ctrlFrm->formText("sarana_jml_masjid", $this->detailUmum['sarana_jml_masjid'], $sarana_jml_masjidAttrib);
			?>  buah
		</td>
	</tr>
	
	<tr>
		<td align="right" >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 2. Mushola:</td>
		<td>	
			<? 
				$sarana_jml_musholaAttrib = array("placeholder"=>"Diisi hanya dengan angka. Misal: 5000000",  "size" => 50,"maxlength" => 50,"required"=>"required");
				echo $ctrlFrm->formText("sarana_jml_mushola", $this->detailUmum['sarana_jml_mushola'], $sarana_jml_musholaAttrib);
			?>  buah
		</td>
	</tr>
	
	<tr>
		<td align="right" >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 3. Gereja:</td>
		<td>	
			<? 
				$sarana_jml_gerejaAttrib = array("placeholder"=>"Diisi hanya dengan angka. Misal: 5000000",  "size" => 50,"maxlength" => 50,"required"=>"required");
				echo $ctrlFrm->formText("sarana_jml_gereja", $this->detailUmum['sarana_jml_gereja'], $sarana_jml_gerejaAttrib);
			?>  buah
		</td>
	</tr>
	
	<tr>
		<td align="right" >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 4. Pura:</td>
		<td>	
			<? 
				$sarana_jml_puraAttrib = array("placeholder"=>"Diisi hanya dengan angka. Misal: 5000000",  "size" => 50,"maxlength" => 50,"required"=>"required");
				echo $ctrlFrm->formText("sarana_jml_pura", $this->detailUmum['sarana_jml_pura'], $sarana_jml_puraAttrib);
			?>  buah
		</td>
	</tr>
					
	<tr>
		<td align="right" >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 5. Vihara:</td>
		<td>	
			<? 
				$sarana_jml_viharaAttrib = array("placeholder"=>"Diisi hanya dengan angka. Misal: 5000000",  "size" => 50,"maxlength" => 50,"required"=>"required");
				echo $ctrlFrm->formText("sarana_jml_vihara", $this->detailUmum['sarana_jml_vihara'], $sarana_jml_viharaAttrib);
			?>  buah
		</td>
	</tr>
					
	<tr>
		<td align="right" >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 6. Klenteng:</td>
		<td>	
			<? 
				$sarana_jml_klentengAttrib = array("placeholder"=>"Diisi hanya dengan angka. Misal: 5000000",  "size" => 50,"maxlength" => 50,"required"=>"required");
				echo $ctrlFrm->formText("sarana_jml_klenteng", $this->detailUmum['sarana_jml_klenteng'], $sarana_jml_klentengAttrib);
			?>  buah
		</td>
	</tr>
					
	<tr>
		<td align="right" >&nbsp;&nbsp;&nbsp; e. Prasarana Umum:</td>
		<td></td>
	</tr>
	
	<tr>
		<td align="right" >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 1. Olahraga:</td>
		<td>	
			<? 
				$sarana_jml_olahragaAttrib = array("placeholder"=>"Diisi hanya dengan angka. Misal: 5000000",  "size" => 50,"maxlength" => 50,"required"=>"required");
				echo $ctrlFrm->formText("sarana_jml_olahraga", $this->detailUmum['sarana_jml_olahraga'], $sarana_jml_olahragaAttrib);
			?>  buah
		</td>
	</tr>
	
	<tr>
		<td align="right" >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 2. Kesenian / Budaya:</td>
		<td>	
			<? 
				$sarana_jml_kesenianAttrib = array("placeholder"=>"Diisi hanya dengan angka. Misal: 5000000",  "size" => 50,"maxlength" => 50,"required"=>"required");
				echo $ctrlFrm->formText("sarana_jml_kesenian", $this->detailUmum['sarana_jml_kesenian'], $sarana_jml_kesenianAttrib);
			?>  buah
		</td>
	</tr>
	
	<tr>
		<td align="right" >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 3. Balai Pertemuan:</td>
		<td>	
			<? 
				$sarana_jml_balai_pertemuanAttrib = array("placeholder"=>"Diisi hanya dengan angka. Misal: 5000000",  "size" => 50,"maxlength" => 50,"required"=>"required");
				echo $ctrlFrm->formText("sarana_jml_balai_pertemuan", $this->detailUmum['sarana_jml_balai_pertemuan'], $sarana_jml_balai_pertemuanAttrib);
			?>  buah
		</td>
	</tr>
	
	<tr>
		<td align="right" >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 4. Lainnya:</td>
		<td>	
			<? 
				$sarana_jml_lainnyaAttrib = array("placeholder"=>"Diisi hanya dengan angka. Misal: 5000000",  "size" => 50,"maxlength" => 50,"required"=>"required");
				echo $ctrlFrm->formText("sarana_jml_lainnya", $this->detailUmum['sarana_jml_lainnya'], $sarana_jml_lainnyaAttrib);
			?>  buah
		</td>
	</tr>
	

</table>
</div> 
<!--End UMUM-->

<!-- DATA PERSONIL -->
<div id="tabs-2"> 
<table width="100%" border="0" cellpadding="0" cellspacing="1" class="std">
	<tr>
		<td colspan="2" align="right" >1. Kepala Kelurahan (Lurah)</td>
		<td></td>
	</tr>
	
	<tr>
		<td align="right" >&nbsp;&nbsp;&nbsp; a. Nama:</td>
		<td>
			<? 
				$nama_lurahAttrib = array("size" => 50,"maxlength" => 50,"required"=>"required");
				echo $ctrlFrm->formText("nama_lurah",  $this->detailPersonil['nama_lurah'], $nama_lurahAttrib);
			?>
		</td>
	</tr>
	
	<tr>
		<td align="right" >&nbsp;&nbsp;&nbsp; b. Pangkat / Golongan:</td>
		<td>	
			<? 
				$gol_lurahAttrib = array("size" => 50,"maxlength" => 50,"required"=>"required");
				echo $ctrlFrm->formText("gol_lurah", $this->detailPersonil['gol_lurah'], $gol_lurahAttrib);
			?>
		</td>
	</tr>
	
	<tr>
		<td align="right" >&nbsp;&nbsp;&nbsp; c. NIP:</td>
		<td>	
			<? 
				$nip_lurahAttrib = array("size" => 50,"maxlength" => 50,"required"=>"required");
				echo $ctrlFrm->formText("nip_lurah", $this->detailPersonil['nip_lurah'], $nip_lurahAttrib);
			?>
		</td>
	</tr>
	
	<tr>
		<td align="right" >&nbsp;&nbsp;&nbsp; d. Pendidikan:</td>
		<td>	
			<select name="id_pendidikan_lurah">
				<?php foreach($this->pendidikan as $data): ?>
					<?php if(($this->detailPersonil['id_pendidikan_lurah'])== $this->escape($data->id_pendidikan)){ ?> 
						<option value="<?php echo $this->escape($data->id_pendidikan); ?>" selected><?php echo $this->escape($data->pendidikan); ?> </option>
				<?php }else{?>
				<option value="<?php echo $this->escape($data->id_pendidikan); ?>"><?php echo $this->escape($data->pendidikan); ?> </option>
				 <?php }
				 endforeach; ?>
			</select>
		</td>
	</tr>
	
	<tr>
		<td align="right" >&nbsp;&nbsp;&nbsp; e. TMT Masa Jabatan:</td>
		<td>	
			<? 
				$tmt_jabatan_lurahAttrib = array("size" => 50,"maxlength" => 50,"required"=>"required");
				echo $ctrlFrm->formText("tmt_jabatan_lurah", $this->detailPersonil['tmt_jabatan_lurah'], $tmt_jabatan_lurahAttrib);
			?>
		</td>
	</tr>
	
	<tr>
		<td align="right" >&nbsp;&nbsp;&nbsp; f. Riwayat Jabatan:</td>
		<td>	
			<? 
				$riwayat_jabatan1Attrib = array("size" => 50,"maxlength" => 50,"required"=>"required");
				echo $ctrlFrm->formText("riwayat_jabatan1", $this->detailPersonil['riwayat_jabatan1'], $riwayat_jabatan1Attrib);
			?>
		</td>
	</tr>
	
	<tr>
		<td align="right" >&nbsp;&nbsp;&nbsp; g. Jenis Kelamin:</td>
			<td>	
				<select name="id_jenkel_lurah">
					<?php foreach($this->jenkel as $data): ?>
						<?php if(($this->detailPersonil['id_jenkel_lurah'])== $this->escape($data->id_jenkel)){ ?> 
							<option value="<?php echo $this->escape($data->id_jenkel); ?>" selected><?php echo $this->escape($data->jenkel); ?> </option>
					<?php }else{?>
					<option value="<?php echo $this->escape($data->id_jenkel); ?>"><?php echo $this->escape($data->jenkel); ?> </option>
					 <?php }
					 endforeach; ?>
				</select>
			</td>	
	</tr>
				
	<tr>
		<td colspan="2" align="right" >2. Sekretaris Kelurahan</td>
		<td></td>
	</tr>
	
	<tr>
		<td align="right" >&nbsp;&nbsp;&nbsp; a. Nama:</td>
		<td>
			<? 
				$nama_lurahAttrib = array("size" => 50,"maxlength" => 50,"required"=>"required");
				echo $ctrlFrm->formText("nama_seklur", $this->detailPersonil['nama_seklur'], $nama_seklurAttrib);
			?>
		</td>
	</tr>
	
	<tr>
		<td align="right" >&nbsp;&nbsp;&nbsp; b. Pangkat / Golongan:</td>
		<td>	
			<? 
				$gol_lurahAttrib = array("size" => 50,"maxlength" => 50,"required"=>"required");
				echo $ctrlFrm->formText("gol_seklur", $this->detailPersonil['gol_seklur'], $gol_seklurAttrib);
			?>
		</td>
	</tr>
	
	<tr>
		<td align="right" >&nbsp;&nbsp;&nbsp; c. NIP:</td>
		<td>	
			<? 
				$nip_lurahAttrib = array("size" => 50,"maxlength" => 50,"required"=>"required");
				echo $ctrlFrm->formText("nip_seklur", $this->detailPersonil['nip_seklur'], $nip_seklurAttrib);
			?>
		</td>
	</tr>
	
	<tr>
		<td align="right" >&nbsp;&nbsp;&nbsp; d. Pendidikan:</td>
		<td>	
			<select name="id_pendidikan_seklur">
				<?php foreach($this->pendidikan as $data): ?>
					<?php if(($this->detailPersonil['id_pendidikan_seklur'])== $this->escape($data->id_pendidikan)){ ?> 
						<option value="<?php echo $this->escape($data->id_pendidikan); ?>" selected><?php echo $this->escape($data->pendidikan); ?> </option>
				<?php }else{?>
				<option value="<?php echo $this->escape($data->id_pendidikan); ?>"><?php echo $this->escape($data->pendidikan); ?> </option>
				 <?php }
				 endforeach; ?>
			</select>
		</td>
	</tr>
	
	<tr>
		<td align="right" >&nbsp;&nbsp;&nbsp; e. TMT Masa Jabatan:</td>
		<td>	
			<? 
				$tmt_jabatan_lurahAttrib = array("size" => 50,"maxlength" => 50,"required"=>"required");
				echo $ctrlFrm->formText("tmt_jabatan_seklur", $this->detailPersonil['tmt_jabatan_seklur'], $tmt_jabatan_seklurAttrib);
			?>
		</td>
	</tr>
	
	<tr>
		<td align="right" >&nbsp;&nbsp;&nbsp; f. Riwayat Jabatan:</td>
		<td>	
			<? 
				$riwayat_jabatan1Attrib = array("size" => 50,"maxlength" => 50,"required"=>"required");
				echo $ctrlFrm->formText("riwayat_jabatan1", $this->detailPersonil['riwayat_jabatan1'], $riwayat_jabatan1Attrib);
			?>
		</td>
	</tr>
	
	<tr>
		<td align="right" >&nbsp;&nbsp;&nbsp; g. Jenis Kelamin:</td>
		<td>	
			<select name="id_jenkel_seklur">
				<?php foreach($this->jenkel as $data): ?>
					<?php if(($this->detailPersonil['id_jenkel_seklur'])== $this->escape($data->id_jenkel)){ ?> 
						<option value="<?php echo $this->escape($data->id_jenkel); ?>" selected><?php echo $this->escape($data->jenkel); ?> </option>
				<?php }else{?>
				<option value="<?php echo $this->escape($data->id_jenkel); ?>"><?php echo $this->escape($data->jenkel); ?> </option>
				 <?php }
				 endforeach; ?>
			</select>
		</td>
	</tr>
	
	<tr>
		<td colspan="2" align="right" >3. Jumlah Aparat Kantor Kelurahan</td>
		<td></td>
	</tr>
	
	<tr>
		<td align="right" >&nbsp;&nbsp;&nbsp; a. Golongan I:</td>
		<td>
			<? 
				$jumlah_aparat_gol1Attrib = array("placeholder"=>"Diisi hanya dengan angka. Misal: 5000000",  "size" => 25,"maxlength" => 25,"required"=>"required");
				echo $ctrlFrm->formText("jumlah_aparat_gol1", $this->detailPersonil['jumlah_aparat_gol1'], $jumlah_aparat_gol1Attrib);
			?>  orang
		
		</td>
	</tr>
	
	<tr>
		<td align="right" >&nbsp;&nbsp;&nbsp; b.  Golongan II:</td>
		<td>	
			<? 
				$jumlah_aparat_gol2Attrib = array("placeholder"=>"Diisi hanya dengan angka. Misal: 5000000",  "size" => 25,"maxlength" => 25,"required"=>"required");
				echo $ctrlFrm->formText("jumlah_aparat_gol2", $this->detailPersonil['jumlah_aparat_gol2'], $jumlah_aparat_gol2Attrib);
			?>  orang
		</td>
	</tr>
	
	<tr>
		<td align="right" >&nbsp;&nbsp;&nbsp; c.  Golongan III:</td>
		<td>	
			<? 
				$jumlah_aparat_gol3Attrib = array("placeholder"=>"Diisi hanya dengan angka. Misal: 5000000",  "size" => 25,"maxlength" => 25,"required"=>"required");
				echo $ctrlFrm->formText("jumlah_aparat_gol3", $this->detailPersonil['jumlah_aparat_gol3'], $jumlah_aparat_gol3Attrib);
			?>  orang
		</td>
	</tr>
	
	<tr>
		<td align="right" >&nbsp;&nbsp;&nbsp; d.  Golongan IV:</td>
		<td>	
			<? 
				$jumlah_aparat_gol4Attrib = array("placeholder"=>"Diisi hanya dengan angka. Misal: 5000000",  "size" => 25,"maxlength" => 25,"required"=>"required");
				echo $ctrlFrm->formText("jumlah_aparat_gol4", $this->detailPersonil['jumlah_aparat_gol4'], $jumlah_aparat_gol4Attrib);
			?>  orang
		</td>
	</tr>		
</table>
</div>
<!--End Personil-->

<!--Kewenangan-->
<div id="tabs-3">
<table width="100%" border="0" cellpadding="0" cellspacing="1" class="std">
	<tr>
		<td colspan="2" align="right" >1. Jumlah urusan yang dilimpahkan kabupaten/kota</td>
		<td></td>
		<td>
			<? 
				$n_fesesAttrib = array("size" => 25,"maxlength" => 25,"required"=>"required");
				echo $ctrlFrm->formText("n_feses", $this->detailKelurahan->n_feses, $n_fesesAttrib);
			?>  buah</td>
	</tr>
	
	<tr>
		<td colspan="2" align="right" >2. Urusan yang dilimpahkan oleh kabupaten/kota</td>
		<td></td>
		<td>
			<? 
				$n_fesesAttrib = array("size" => 25,"maxlength" => 25,"required"=>"required");
				echo $ctrlFrm->formText("n_feses", $this->detailKelurahan->n_feses, $n_fesesAttrib);
			?>  buah</td>
	</tr>
	
	<tr>
		<td align="right" >&nbsp;&nbsp;&nbsp; a. Urusan Wajib</td>
		<td></td>
	</tr>
	
	<tr>
		<td align="right" >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  - Bidang</td>
			<td> 
				<div class="input_fields_wajib_bidang">
					<button class="add_field_wajib_bidang btn btn-info">Tambahkan kolom</button>
						<div><input type="text" name="wajib_bidang[]"></div>
				</div>
			</td>
	</tr>
	
	<tr>
		<td align="right" >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  - Urusan</td>
			<td> 
				<div class="input_fields_wajib_urusan">
					<button class="add_field_wajib_urusan btn btn-info">Tambahkan kolom</button>
						<div><input type="text" name="wajib_urusan[]"></div>
				</div>
			</td>
	</tr>
	
	<tr>
		<td align="right" >&nbsp;&nbsp;&nbsp; b.  Golongan II:</td>
		<td>	
			<? 
				$n_fesesAttrib = array("size" => 25,"maxlength" => 25,"required"=>"required");
				echo $ctrlFrm->formText("n_feses", $this->detailKelurahan->n_feses, $n_fesesAttrib);
			?>  orang
		</td>
	</tr>
	
	<tr>
		<td align="right" >&nbsp;&nbsp;&nbsp; c.  Golongan III:</td>
		<td>	
			<? 
				$n_fesesAttrib = array("size" => 25,"maxlength" => 25,"required"=>"required");
				echo $ctrlFrm->formText("n_feses", $this->detailKelurahan->n_feses, $n_fesesAttrib);
			?>  orang
		</td>
	</tr>
	
	<tr>
		<td align="right" >&nbsp;&nbsp;&nbsp; d.  Golongan IV:</td>
		<td>	
			<? 
				$n_fesesAttrib = array("size" => 25,"maxlength" => 25,"required"=>"required");
				echo $ctrlFrm->formText("n_feses", $this->detailKelurahan->n_feses, $n_fesesAttrib);
			?>  orang
		</td>
	</tr>



</table>
</div>
<!--End Kewenangan-->

<!-- DATA KEUANGAN -->
<div id="tabs-4">
<table width="100%" border="0" cellpadding="0" cellspacing="1" class="std">

	<tr>
		<td align="right"> 1. Anggaran Kelurahan dari APBD kabupaten/kota</td>
		<td> RP &nbsp;
			<? 
				$anggaran_apbdAttrib = array("placeholder"=>"Diisi hanya dengan angka. Misal: 5000000",  "size" => 25,"maxlength" => 25,"required"=>"required");
				echo $ctrlFrm->formText("anggaran_apbd", $this->detailKeuangan['anggaran_apbd'], $anggaran_apbdAttrib);
			?>  </td>
	</tr>
	
	<tr>
		<td align="right" > 2. SKPD</td>
		<td> 
			<input type="radio" name="is_skpd" id="is_skpd"> Sudah /
			<input type="radio" name="is_skpd" id="is_skpd"> Belum
		</td>
	</tr>
	
	<tr>
		<td colspan="2" align="right" >3. Bantuan yang diterima kelurahan</td>
		<td></td>
		
	</tr>
	
	<tr>
		<td align="right" >&nbsp;&nbsp;&nbsp; a. Pemerintah Pusat:</td>
		<td > 
		RP &nbsp;
			<? 
				$bantuan_pusatAttrib = array("placeholder"=>"Diisi hanya dengan angka. Misal: 5000000",  "size" => 50,"maxlength" => 50,"required"=>"required");
				echo $ctrlFrm->formText("bantuan_pusat", $this->detailKeuangan['bantuan_pusat'], $bantuan_pusatAttrib);
			?>  
		</td>
	</tr>
	
	<tr>
		<td align="right" >&nbsp;&nbsp;&nbsp; b.  Pemerintah Provinsi:</td>
		<td> RP &nbsp;
			<? 
				$bantuan_provAttrib = array("placeholder"=>"Diisi hanya dengan angka. Misal: 5000000",  "size" => 50,"maxlength" => 50,"required"=>"required");
				echo $ctrlFrm->formText("bantuan_prov", $this->detailKeuangan['bantuan_prov'], $bantuan_provAttrib);
			?>  
		</td>
	</tr>
	
	<tr>
		<td align="right" >&nbsp;&nbsp;&nbsp; c.  Pemerintah Kabupaten / Kota:</td>
		<td> RP &nbsp;
			<? 
				$bantuan_kotaAttrib = array("placeholder"=>"Diisi hanya dengan angka. Misal: 5000000",  "size" => 50,"maxlength" => 50,"required"=>"required");
				echo $ctrlFrm->formText("bantuan_kota", $this->detailKeuangan['bantuan_kota'], $bantuan_kotaAttrib);
			?> 
		</td>
	</tr>
	
	<tr>
		<td align="right" >&nbsp;&nbsp;&nbsp; d. Hibah / Bantuan Luar Negeri:</td>
		<td> RP &nbsp;
			<? 
				$hibahAttrib = array("placeholder"=>"Diisi hanya dengan angka. Misal: 5000000",  "size" => 50,"maxlength" => 50,"required"=>"required");
				echo $ctrlFrm->formText("hibah", $this->detailKeuangan['hibah'], $hibahAttrib);
			?> 
		</td>
	</tr>
				
	<tr>
		<td align="right" >&nbsp;&nbsp;&nbsp; e.  Sumbangan / Bantuan Lain tidak mengikat:</td>
		<td> RP &nbsp;
			<? 
				$sumbanganAttrib = array("placeholder"=>"Diisi hanya dengan angka. Misal: 5000000",  "size" => 50,"maxlength" => 50,"required"=>"required");
				echo $ctrlFrm->formText("sumbangan", $this->detailKeuangan['sumbangan'], $sumbanganAttrib);
			?> 
		</td>
	</tr>
	
	<tr>
		<td align="right" >&nbsp;&nbsp;&nbsp; f. Swadaya / Gotong Royong:</td>
		<td> RP &nbsp;
			<? 
				$swadayaAttrib = array("placeholder"=>"Diisi hanya dengan angka. Misal: 5000000",  "size" => 50,"maxlength" => 50,"required"=>"required");
				echo $ctrlFrm->formText("swadaya", $this->detailKeuangan['swadaya'], $swadayaAttrib);
			?> 
		</td>
	</tr>
</table>
</div>
<!--End Keuangan-->

<!-- KELEMBAGAAN -->
<div id="tabs-5"> 
<table width="100%" border="0" cellpadding="0" cellspacing="1" class="std">

	<tr>
		<td colspan="3" align="right" >1. Lembaga Pemberdayaan Masyarakat (LPM) atau sebutan lain:</td>
		<td></td>
		<td></td>
		
	</tr>
	
	<tr>
		<td align="right" >&nbsp;&nbsp;&nbsp; a. Jumlah Pengurus:</td>
		<td> 
			<? 
				$lpmp_jml_pengurusAttrib = array("placeholder"=>"Diisi hanya dengan angka. Misal: 5000000",  "size" => 25,"maxlength" => 25,"required"=>"required");
				echo $ctrlFrm->formText("lpmp_jml_pengurus", $this->detailKelembagaan['lpmp_jml_pengurus'], $lpmp_jml_pengurusAttrib);
			?> orang 
		</td>
	</tr>
	
	<tr>
		<td align="right" >&nbsp;&nbsp;&nbsp; b. Jumlah Anggota:</td>
		<td> 
			<? 
				$lpmp_jml_anggotaAttrib = array("placeholder"=>"Diisi hanya dengan angka. Misal: 5000000",  "size" => 25,"maxlength" => 25,"required"=>"required");
				echo $ctrlFrm->formText("lpmp_jml_anggota", $this->detailKelembagaan['lpmp_jml_anggota'], $lpmp_jml_anggotaAttrib);
			?>  orang
		</td>
	</tr>
	
	<tr>
		<td align="right" >&nbsp;&nbsp;&nbsp; c.  Jumlah Kegiatan perbulan:</td>
		<td> 
			<? 
				$lpmp_jml_keg_perbulanAttrib = array("placeholder"=>"Diisi hanya dengan angka. Misal: 5000000",  "size" => 25,"maxlength" => 25,"required"=>"required");
				echo $ctrlFrm->formText("lpmp_jml_keg_perbulan", $this->detailKelembagaan['lpmp_jml_keg_perbulan'], $lpmp_jml_keg_perbulanAttrib);
			?>  kegiatan
		</td>
	</tr>
	
	<tr>
		<td align="right" >&nbsp;&nbsp;&nbsp; d. Jumlah dana yang dikelola:</td>
		<td> RP &nbsp;
			<? 
				$lpmp_jml_danaAttrib = array("placeholder"=>"Diisi hanya dengan angka. Misal: 5000000",  "size" => 25,"maxlength" => 25,"required"=>"required");
				echo $ctrlFrm->formText("lpmp_jml_dana", $this->detailKelembagaan['lpmp_jml_dana'], $lpmp_jml_danaAttrib);
			?> 
		</td>
	</tr>

	<tr>
		<td colspan="3" align="right" >2. PKK:</td>
		<td></td>
		<td></td>
		
	</tr>
	
	<tr>
		<td align="right" >&nbsp;&nbsp;&nbsp; a. Jumlah Pengurus:</td>
		<td> 
			<? 
				$pkk_jml_pengurusAttrib = array("placeholder"=>"Diisi hanya dengan angka. Misal: 5000000",  "size" => 25,"maxlength" => 25,"required"=>"required");
				echo $ctrlFrm->formText("pkk_jml_pengurus", $this->detailKelembagaan['pkk_jml_pengurus'], $pkk_jml_pengurusAttrib);
			?> orang 
		</td>
	</tr>
	
	<tr>
		<td align="right" >&nbsp;&nbsp;&nbsp; b. Jumlah Anggota:</td>
		<td> 
			<? 
				$pkk_jml_anggotaAttrib = array("placeholder"=>"Diisi hanya dengan angka. Misal: 5000000",  "size" => 25,"maxlength" => 25,"required"=>"required");
				echo $ctrlFrm->formText("pkk_jml_anggota", $this->detailKelembagaan['pkk_jml_anggota'], $pkk_jml_anggotaAttrib);
			?>  orang
		</td>
	</tr>
	
	<tr>
		<td align="right" >&nbsp;&nbsp;&nbsp; c.  Jumlah Kegiatan perbulan:</td>
		<td> 
			<? 
				$pkk_jml_keg_perbulanAttrib = array("placeholder"=>"Diisi hanya dengan angka. Misal: 5000000",  "size" => 25,"maxlength" => 25,"required"=>"required");
				echo $ctrlFrm->formText("pkk_jml_keg_perbulan", $this->detailKelembagaan['pkk_jml_keg_perbulan'], $pkk_jml_keg_perbulanAttrib);
			?>  kegiatan
		</td>
	</tr>
	
	<tr>
		<td align="right" >&nbsp;&nbsp;&nbsp; d.  Jumlah buku administrasi yang dikelola:</td>
		<td> 
			<? 
				$pkk_jml_buku_administrasiAttrib = array("placeholder"=>"Diisi hanya dengan angka. Misal: 5000000",  "size" => 25,"maxlength" => 25,"required"=>"required");
				echo $ctrlFrm->formText("pkk_jml_buku_administrasi", $this->detailKelembagaan['pkk_jml_buku_administrasi'], $pkk_jml_buku_administrasiAttrib);
			?>  kegiatan
		</td>
	</tr>
	
	<tr>
		<td align="right" >&nbsp;&nbsp;&nbsp; e. Jumlah dana yang dikelola:</td>
		<td> RP &nbsp;
			<? 
				$pkk_jml_danaAttrib = array("placeholder"=>"Diisi hanya dengan angka. Misal: 5000000",  "size" => 25,"maxlength" => 25,"required"=>"required");
				echo $ctrlFrm->formText("pkk_jml_dana", $this->detailKelembagaan['pkk_jml_dana'], $pkk_jml_danaAttrib);
			?> 
		</td>
	</tr>
	
	<tr>
		<td colspan="3" align="right" >3. Karang Taruna:</td>
		<td></td>
		<td></td>
		
	</tr>
	
	<tr>
		<td align="right" >&nbsp;&nbsp;&nbsp; a. Jumlah Karang Taruna:</td>
		<td> 
			<? 
				$taruna_jmlAttrib = array("placeholder"=>"Diisi hanya dengan angka. Misal: 5000000",  "size" => 25,"maxlength" => 25,"required"=>"required");
				echo $ctrlFrm->formText("taruna_jml", $this->detailKelembagaan['taruna_jml'], $taruna_jmlAttrib);
			?> buah 
		</td>
	</tr>
	
	<tr>
		<td align="right" >&nbsp;&nbsp;&nbsp; b. Jenis Karang Taruna:</td>
		<td> 
			<? 
				$taruna_jenisAttrib = array("placeholder"=>"Diisi hanya dengan angka. Misal: 5000000",  "size" => 25,"maxlength" => 25,"required"=>"required");
				echo $ctrlFrm->formText("taruna_jenis", $this->detailKelembagaan['taruna_jenis'], $taruna_jenisAttrib);
			?>  orang
		</td>
	</tr>
	
	<tr>
		<td align="right" >&nbsp;&nbsp;&nbsp; c.  Jumlah Pengurus (rata-rata):</td>
		<td> 
			<? 
				$taruna_jml_pengurusAttrib = array("placeholder"=>"Diisi hanya dengan angka. Misal: 5000000",  "size" => 25,"maxlength" => 25,"required"=>"required");
				echo $ctrlFrm->formText("taruna_jml_pengurus", $this->detailKelembagaan['taruna_jml_pengurus'], $taruna_jml_pengurusAttrib);
			?>  
		</td>
	</tr>
	
	<tr>
		<td colspan="3" align="right" >4. RT / RW:</td>
		<td></td>
		<td></td>
		
	</tr>
	
	<tr>
		<td align="right" >&nbsp;&nbsp;&nbsp; a. Jumlah RW:</td>
		<td> 
			<? 
				$jml_rwAttrib = array("placeholder"=>"Diisi hanya dengan angka. Misal: 5000000",  "size" => 25,"maxlength" => 25,"required"=>"required");
				echo $ctrlFrm->formText("jml_rw", $this->detailKelembagaan['jml_rw'], $jml_rwAttrib);
			?> buah 
		</td>
	</tr>
	
	<tr>
		<td align="right" >&nbsp;&nbsp;&nbsp; b. Jumlah RT:</td>
		<td> 
			<? 
				$jml_rtAttrib = array("placeholder"=>"Diisi hanya dengan angka. Misal: 5000000",  "size" => 25,"maxlength" => 25,"required"=>"required");
				echo $ctrlFrm->formText("jml_rt", $this->detailKelembagaan['jml_rt'], $jml_rtAttrib);
			?>  buah
		</td>
	</tr>
	
	<tr>
		<td colspan="2" align="right" >&nbsp;&nbsp;&nbsp; c.  Rata-rata penghasilan Ketua RW dalam Sebulan:</td>
		<td> Rp 
			<? 
				$rata_penghasilan_rwAttrib = array("placeholder"=>"Diisi hanya dengan angka. Misal: 5000000",  "size" => 25,"maxlength" => 25,"required"=>"required");
				echo $ctrlFrm->formText("rata_penghasilan_rw", $this->detailKelembagaan['rata_penghasilan_rw'], $rata_penghasilan_rwAttrib);
			?>  
		</td>
	</tr>
	
	<tr>
		<td colspan="2" align="right" >&nbsp;&nbsp;&nbsp; d.  Rata-rata penghasilan Ketua RT dalam Sebulan:</td>
		<td> Rp 
			<? 
				$rata_penghasilan_rtAttrib = array("placeholder"=>"Diisi hanya dengan angka. Misal: 5000000",  "size" => 25,"maxlength" => 25,"required"=>"required");
				echo $ctrlFrm->formText("rata_penghasilan_rt", $this->detailKelembagaan['rata_penghasilan_rt'], $rata_penghasilan_rtAttrib);
			?>  
		</td>
	</tr>
	
	<tr>
		<td colspan="3" align="right" >5. Lembaga Kemasyarakatan Lainnya:</td>
		<td></td>
		<td></td>
		
	</tr>
	
	<tr>
		<td align="right" >&nbsp;&nbsp;&nbsp; a. Jumlah:</td>
		<td> 
			<? 
				$jml_lembaga_lainAttrib = array("placeholder"=>"Diisi hanya dengan angka. Misal: 5000000",  "size" => 25,"maxlength" => 25,"required"=>"required");
				echo $ctrlFrm->formText("jml_lembaga_lain", $this->detailKelembagaan['jml_lembaga_lain'], $jml_lembaga_lainAttrib);
			?> buah 
		</td>
	</tr>
</table>
</div>
<!--End Kelembagaan-->

<!-- KEAMANAN DAN KETERTIBAN-->
<div id="tabs-6"> 
<table width="100%" border="0" cellpadding="0" cellspacing="1" class="std">
	<tr>
		<td align="right" >1. Jumlah Anggota Linmas:</td>
		<td>
			<? 
				$jml_anggota_linmasAttrib = array("placeholder"=>"Diisi hanya dengan angka. Misal: 5000000",  "size" => 25,"maxlength" => 25,"required"=>"required");
				echo $ctrlFrm->formText("jml_anggota_linmas", $this->detailTrantib['jml_anggota_linmas'], $jml_anggota_linmasAttrib);
			?> orang
		</td>
	</tr>
	
	<tr>
		<td align="right" >2. Jumlah Pos kamling:</td>
		<td>
			<? 
				$jml_pos_kamlingAttrib = array("placeholder"=>"Diisi hanya dengan angka. Misal: 5000000",  "size" => 25,"maxlength" => 25,"required"=>"required");
				echo $ctrlFrm->formText("jml_pos_kamling", $this->detailTrantib['jml_pos_kamling'], $jml_pos_kamlingAttrib);
			?> pos
		</td>
	</tr>
	
	<tr>
		<td align="right" >3. Jumlah Operasi Penertiban:</td>
		<td>
			<? 
				$jml_ops_penertibanAttrib = array("placeholder"=>"Diisi hanya dengan angka. Misal: 5000000",  "size" => 25,"maxlength" => 25,"required"=>"required");
				echo $ctrlFrm->formText("jml_ops_penertiban", $this->detailTrantib['jml_ops_penertiban'], $jml_ops_penertibanAttrib);
			?> kali
		</td>
	</tr>
	
	<tr>
		<td align="right" >4. Jumlah Kejadian Kriminal:</td>
		<td></td>
	</tr>
	
	<tr>
		<td align="right" >&nbsp;&nbsp;&nbsp; a. Pencurian:</td>
		<td> 
			<? 
				$jml_pencurianAttrib = array("placeholder"=>"Diisi hanya dengan angka. Misal: 5000000",  "size" => 25,"maxlength" => 25,"required"=>"required");
				echo $ctrlFrm->formText("jml_pencurian", $this->detailTrantib['jml_pencurian'], $jml_pencurianAttrib);
			?> kali 
		</td>
	</tr>
	
	<tr>
		<td align="right" >&nbsp;&nbsp;&nbsp; b. Perkosaan:</td>
		<td> 
			<? 
				$jml_perkosaanAttrib = array("placeholder"=>"Diisi hanya dengan angka. Misal: 5000000",  "size" => 25,"maxlength" => 25,"required"=>"required");
				echo $ctrlFrm->formText("jml_perkosaan", $this->detailTrantib['jml_perkosaan'], $jml_perkosaanAttrib);
			?> kali 
		</td>
	</tr>
	
	<tr>
		<td align="right" >&nbsp;&nbsp;&nbsp; c. Kenakalan Remaja:</td>
		<td> 
			<? 
				$jml_kenakalan_remajaAttrib = array("placeholder"=>"Diisi hanya dengan angka. Misal: 5000000",  "size" => 25,"maxlength" => 25,"required"=>"required");
				echo $ctrlFrm->formText("jml_kenakalan_remaja", $this->detailTrantib['jml_kenakalan_remaja'], $jml_kenakalan_remajaAttrib);
			?> kali 
		</td>
	</tr>
	
	<tr>
		<td align="right" >&nbsp;&nbsp;&nbsp; d. Pembunuhan:</td>
		<td> 
			<? 
				$jml_pembunuhanAttrib = array("placeholder"=>"Diisi hanya dengan angka. Misal: 5000000",  "size" => 25,"maxlength" => 25,"required"=>"required");
				echo $ctrlFrm->formText("jml_pembunuhan", $this->detailTrantib['jml_pembunuhan'], $jml_pembunuhanAttrib);
			?> kali 
		</td>
	</tr>
	
	<tr>
		<td align="right" >&nbsp;&nbsp;&nbsp; e. Perampokan:</td>
		<td> 
			<? 
				$jml_perampokanAttrib = array("placeholder"=>"Diisi hanya dengan angka. Misal: 5000000",  "size" => 25,"maxlength" => 25,"required"=>"required");
				echo $ctrlFrm->formText("jml_perampokan", $this->detailTrantib['jml_perampokan'], $jml_perampokanAttrib);
			?> kali 
		</td>
	</tr>
	
	<tr>
		<td align="right" >&nbsp;&nbsp;&nbsp; f. Penipuan:</td>
		<td> 
			<? 
				$jml_penipuanAttrib = array("placeholder"=>"Diisi hanya dengan angka. Misal: 5000000",  "size" => 25,"maxlength" => 25,"required"=>"required");
				echo $ctrlFrm->formText("jml_penipuan", $this->detailTrantib['jml_penipuan'], $jml_penipuanAttrib);
			?> kali 
		</td>
	</tr>
	
	<tr>
		<td align="right" >5. Jumlah Kejadian Alam:</td>
		<td> 
			<? 
				$jml_bencanaAttrib = array("placeholder"=>"Diisi hanya dengan angka. Misal: 5000000",  "size" => 25,"maxlength" => 25,"required"=>"required");
				echo $ctrlFrm->formText("jml_bencana", $this->detailTrantib['jml_bencana'], $jml_bencanaAttrib);
			?> kali 
		</td>
	</tr>
	
	<tr>
		<td align="right" >6. Jumlah Pos Bencana Alam:</td>
		<td> 
			<? 
				$jml_pos_bencanaAttrib = array("placeholder"=>"Diisi hanya dengan angka. Misal: 5000000",  "size" => 25,"maxlength" => 25,"required"=>"required");
				echo $ctrlFrm->formText("jml_pos_bencana", $this->detailTrantib['jml_pos_bencana'], $jml_pos_bencanaAttrib);
			?> pos 
		</td>
	</tr>

	
	<tr>
		<td align="right" >7. Jumlah Pembalakan Liar:</td>
		<td> 
			<? 
				$jml_pembalakan_liarAttrib = array("placeholder"=>"Diisi hanya dengan angka. Misal: 5000000",  "size" => 25,"maxlength" => 25,"required"=>"required");
				echo $ctrlFrm->formText("jml_pembalakan_liar", $this->detailTrantib['jml_pembalakan_liar'], $jml_pembalakan_liarAttrib);
			?> kali 
		</td>
	</tr>

	
	<tr>
		<td align="right" >8. Jumlah Pos Hutan Lindung:</td>
		<td> 
			<? 
				$jml_pos_hutan_lindungAttrib = array("placeholder"=>"Diisi hanya dengan angka. Misal: 5000000",  "size" => 25,"maxlength" => 25,"required"=>"required");
				echo $ctrlFrm->formText("jml_pos_hutan_lindung", $this->detailTrantib['jml_pos_hutan_lindung'], $jml_pos_hutan_lindungAttrib);
			?> pos 
		</td>
	</tr>
	
</table>
</div>
<!--End Ketentraman Ketertiban-->
</div>
	<tr>
		<td></td>
		<td>
		<div class="right">
		<input type="button" value="Kembali" onclick="rekamkelurahanlist();"> 
		<input type="reset" value="Ulangi"> 
		<input   type="submit" value="Simpan">
		</div>
		</td>
	</tr>
				<tr>
				    <td>* Harus Diisi</td>
				    <td></td>
				</tr>
			</table>

</form>


</div>

<style>
.btn-info {
	color: #ffffff;
	background-color: #5bc0de;
	border-color: #46b8da;
}
.btn-info: hover {
	background-color: #2693FF;
	border-color: #007FFF;
}

.btn{
	padding-right: 40px;
	float:right;
	display: inline-block;
	margin-bottom: 0;
	text-align: center;
	vertical-align: middle;
	cursor: pointer;
	background-image: none;
	border: 1px solid transparent;
	white-space: nowrap;
	padding: 5px 15px;
	border-radius: 4px;
	-webkit-user-select: none;
	-moz-user-select: none;
	-ms-user-select: none;
	-o-user-select: none;
	font-size: 0.80em;
	text-transform: uppercase;
	text-shadow: 1px 1px 1px rgba(0, 0, 0, 0.22);
	margin-bottom: 10px;
}
</style>
<script>
$(document).ready(function() {
    var max_fields      = 10; //maximum input boxes allowed
    var wrapper         = $(".input_fields_wajib_bidang"); //Fields wrapper
    var add_button      = $(".add_field_wajib_bidang"); //Add button ID
    
    var x = 1; //initlal text box count
    $(add_button).click(function(e){ //on add input button click
        e.preventDefault();
        if(x < max_fields){ //max input box allowed
            x++; //text box increment
            $(wrapper).append('<div><input type="text" name="wajib_bidang[]"/></div>'); //add input box
        }
    });
    
    $(wrapper).on("click",".remove_field", function(e){ //user click on remove text
        e.preventDefault(); $(this).parent('div').remove(); x--;
    })
});
</script>

<script>
$(document).ready(function() {
    var max_fields      = 10; //maximum input boxes allowed
    var wrapper         = $(".input_fields_wajib_urusan"); //Fields wrapper
    var add_button      = $(".add_field_wajib_urusan"); //Add button ID
    
    var x = 1; //initlal text box count
    $(add_button).click(function(e){ //on add input button click
        e.preventDefault();
        if(x < max_fields){ //max input box allowed
            x++; //text box increment
            $(wrapper).append('<div><input type="text" name="wajib_urusan[]"/></div>'); //add input box
        }
    });
    
    $(wrapper).on("click",".remove_field", function(e){ //user click on remove text
        e.preventDefault(); $(this).parent('div').remove(); x--;
    })
});
</script>


<script>
	$(document).ready(function() {
	$(".validasi").validate();
});
</script>

<script>

 	$(function() {
		$("#d_medrec").datepicker();
	});


function showDialog(val) {      
    $( "#dialog-browse" ).dialog({
      autoOpen: false,
      height: 380,
      width: 640,
      modal: true,
      resizable:false,
      title: "Data Pasien"
    });
    if(val =='pasien'){pasienlist();}  
    return false;
  }

</script>

<script language="JavaScript">
    webcam.set_api_url( 'test.php' );
		webcam.set_quality( 90 ); // JPEG quality (1 - 100)
		webcam.set_shutter_sound( true ); // play shutter click sound
		webcam.set_hook( 'onComplete', 'my_completion_handler' );

		function take_snapshot(){
			// take snapshot and upload to server
			document.getElementById('upload_results').innerHTML = '<h1>Uploading...</h1>';
			webcam.snap();
		}

		function my_completion_handler(msg) {
			// extract URL out of PHP output
			if (msg.match(/(http\:\/\/\S+)/)) {
				// show JPEG image in page
				document.getElementById('upload_results').innerHTML ='<h1>Upload Successful!</h1>';
				// reset camera for another shot
				webcam.reset();
			}
			else {alert("PHP Error: " + msg);}
		}
	</script>