<?php
	
	//Format Tanggal Berbahasa Indonesia 
	// Array Hari
	$array_hari = array(1=>'Senin','Selasa','Rabu','Kamis','Jumat', 'Sabtu','Minggu');
	$hari = $array_hari[date('N')];

	//Format Tanggal 
	$tanggal = date ('j');

	//Array Bulan 
	$array_bulan = array(1=>'Januari','Februari','Maret', 'April', 'Mei', 'Juni','Juli','Agustus','September','Oktober', 'November','Desember'); 
	$bulan = $array_bulan[date('n')];
	 
	//Format Tahun 
	$tahun = date('Y');

	 
	// Include the PHPWord.php, all other classes were loaded by an autoloader
	include '../etc/libs/PHPWord.php';

	// Create a new PHPWord Object
	$PHPWord = new PHPWord();		
	$document = $PHPWord->loadTemplate('../etc/data/monografiTemplate.docx');
	
	// $document = file_get_contents("../etc/data/monografiTemplate.doc");
	
	$bulan = strtoupper($array_bulan[$this->bulan]);
	$document->setValue('bulan', $bulan);
	$document->setValue('tahun', $this->tahun);
	
	//awal
	$document->setValue('namaKelurahan', $this->detailKelurahan->kelurahan);
	$document->setValue('tahunPembentukan', $this->detailKelurahan->tahun_pembentukan);
	$document->setValue('dasarHukumPembentukan', $this->detailKelurahan->dasar_hukum_pembentukan);
	$document->setValue('KodeWilayah', $this->detailKelurahan->kode_wilayah);
	$document->setValue('KodePos', $this->detailKelurahan->kode_pos);
	$document->setValue('kecamatan', $this->detailKelurahan->kecamatan);
	$document->setValue('kabupaten', $this->detailKelurahan->kabupaten);
	$document->setValue('provinsi', $this->detailKelurahan->provinsi);
	
	//A. Data Umum
	$document->setValue('tipologi', $this->detailUmum['tipologi']);
	$document->setValue('luasWilayah', $this->detailKelurahan->luas_wilayah);
	$document->setValue('batasUtara', $this->detailKelurahan->batas_utara);
	$document->setValue('batasSelatan', $this->detailKelurahan->batas_selatan);
	$document->setValue('batasBarat', $this->detailKelurahan->batas_barat);
	$document->setValue('batasTimur', $this->detailKelurahan->batas_timur);
	$document->setValue('jarakDariKecamatan', $this->detailKelurahan->jarak_dari_kecamatan);
	$document->setValue('jarakDariKota', $this->detailKelurahan->jarak_dari_kota);
	$document->setValue('jarakDariIbukotaKota', $this->detailKelurahan->jarak_dari_ibukota_kota);
	$document->setValue('jarakDariIbuKotaProv', $this->detailKelurahan->jarak_dari_ibukota_prov);
	$document->setValue('jmlJiwa', $this->detailUmum['jml_jiwa']);
	$document->setValue('jmlKk', $this->detailUmum['jml_kk']);
	$document->setValue('jmlLaki', $this->detailUmum['jml_laki']);
	$document->setValue('jmlPerempuan', $this->detailUmum['jml_perempuan']);
	$document->setValue('jml015', $this->detailUmum['jml_0_15']);
	$document->setValue('jml1565', $this->detailUmum['jml_15_65']);
	$document->setValue('jml65Keatas', $this->detailUmum['jml_65_keatas']);
	$document->setValue('mayoritasPekerjaan', $this->detailUmum['mayoritas_pekerjaan']);
	$document->setValue('jmlPns', $this->detailUmum['jml_pns']);
	$document->setValue('jmlAbri', $this->detailUmum['jml_abri']);
	$document->setValue('jmlSwasta', $this->detailUmum['jml_swasta']);
	$document->setValue('jmlWiraswasta', $this->detailUmum['jml_wiraswasta']);
	$document->setValue('jmlTani', $this->detailUmum['jml_tani']);
	$document->setValue('jmlPertukangan', $this->detailUmum['jml_pertukangan']);
	$document->setValue('jmlBuruhTani', $this->detailUmum['jml_buruh_tani']);		
	$document->setValue('jmlPensiunan', $this->detailUmum['jml_pensiunan']);		
	$document->setValue('jmlNelayan', $this->detailUmum['jml_nelayan']);		
	$document->setValue('jmlPemulung', $this->detailUmum['jml_pemulung']);		
	$document->setValue('jmlJasa', $this->detailUmum['jml_jasa']);		
	$document->setValue('jmlLulusanTk', $this->detailUmum['jml_lulusan_tk']);		
	$document->setValue('jmlLulusanSd', $this->detailUmum['jml_lulusan_sd']);		
	$document->setValue('jmlLulusanSmp', $this->detailUmum['jml_lulusan_smp']);		
	$document->setValue('jmlLulusanSma', $this->detailUmum['jml_lulusan_sma']);		
	$document->setValue('jmlLulusanDiploma', $this->detailUmum['jml_lulusan_diploma']);		
	$document->setValue('jmlLulusanSarjana', $this->detailUmum['jml_lulusan_sarjana']);		
	$document->setValue('jmlLulusanPascasarjana', $this->detailUmum['jml_lulusan_pascasarjana']);		
	$document->setValue('jmlLulusanPontren', $this->detailUmum['jml_lulusan_pontren']);		
	$document->setValue('jmlLulusanKeagamaan', $this->detailUmum['jml_lulusan_keagamaan']);		
	$document->setValue('jmlLulusanSlb', $this->detailUmum['jml_lulusan_slb']);		
	$document->setValue('jmlLulusanKursus', $this->detailUmum['jml_lulusan_kursus']);		
	$document->setValue('jmlJiwaMiskin', $this->detailUmum['jml_jiwa_miskin']);		
	$document->setValue('jmlJiwaKk', $this->detailUmum['jml_jiwa_kk']);		
	$document->setValue('umr', $this->detailUmum['umr']);		
	$document->setValue('saranaKantor', $this->detailUmum['sarana_kantor']);		
	$document->setValue('saranaPuskesmas', $this->detailUmum['sarana_puskesmas']);		
	$document->setValue('saranaJmlPosyandu', $this->detailUmum['sarana_jml_posyandu']);		
	$document->setValue('saranaJmlPoliklinik', $this->detailUmum['sarana_jml_poliklinik']);		
	$document->setValue('saranaJmlPaud', $this->detailUmum['sarana_jml_paud']);		
	$document->setValue('saranaJmlTk', $this->detailUmum['sarana_jml_tk']);		
	$document->setValue('saranaJmlSd', $this->detailUmum['sarana_jml_sd']);		
	$document->setValue('saranaJmlSmp', $this->detailUmum['sarana_jml_smp']);		
	$document->setValue('saranaJmlSma', $this->detailUmum['sarana_jml_sma']);		
	$document->setValue('saranaJmlPt', $this->detailUmum['sarana_jml_pt']);		
	$document->setValue('saranaJmlMasjid', $this->detailUmum['sarana_jml_masjid']);		
	$document->setValue('saranaJmlMushola', $this->detailUmum['sarana_jml_mushola']);		
	$document->setValue('saranaJmlGereja', $this->detailUmum['sarana_jml_gereja']);		
	$document->setValue('saranaJmlPura', $this->detailUmum['sarana_jml_pura']);		
	$document->setValue('saranaJmlVihara', $this->detailUmum['sarana_jml_viharaj']);		
	$document->setValue('saranaJmlKlenteng', $this->detailUmum['sarana_jml_klenteng']);		
	$document->setValue('saranaJmlOlahraga', $this->detailUmum['sarana_jml_olahraga']);		
	$document->setValue('saranaJmlKesenian', $this->detailUmum['sarana_jml_kesenian']);		
	$document->setValue('saranaJmlBalaiPertemuan', $this->detailUmum['sarana_jml_balai_pertemuan']);		
	$document->setValue('saranaJmlLainnya', $this->detailUmum['sarana_jml_lainnya']);		
				
	//B. Data Personil
	$document->setValue('namaLurah', $this->detailPersonil['nama_lurah']);		
	$document->setValue('namaSeklur', $this->detailPersonil['nama_seklur']);		
	$document->setValue('jumlahAparatGol1', $this->detailPersonil['jumlah_aparat_gol1']);		
	$document->setValue('jumlahAparatGol2', $this->detailPersonil['jumlah_aparat_gol2']);		
	$document->setValue('jumlahAparatGol3', $this->detailPersonil['jumlah_aparat_gol3']);		
	$document->setValue('jumlahAparatGol4', $this->detailPersonil['jumlah_aparat_gol4']);
	
	//C. Data Kewenangan
	$document->setValue('pemerintahPusat', $this->detailKewenangan['jml_pemerintah_pusat']);		
	$document->setValue('provinsi', $this->detailKewenangan['jml_provinsi']);		
	$document->setValue('kabupaten', $this->detailKewenangan['jml_kabupaten']);
	
	//D. Data Keuangan
	$document->setValue('anggaranApbd', $this->detailKeuangan['anggaran_apbd']);		
	$document->setValue('isSkpd', $this->detailKeuangan['is_skpd']);		
	$document->setValue('bantuanPusat', $this->detailKeuangan['bantuan_pusat']);
	$document->setValue('bantuanProv', $this->detailKeuangan['bantuan_prov']);
	$document->setValue('bantuanKota', $this->detailKeuangan['bantuan_kota']);
	$document->setValue('hibah', $this->detailKeuangan['hibah']);
	$document->setValue('sumbangan', $this->detailKeuangan['sumbangan']);
	$document->setValue('swadaya', $this->detailKeuangan['swadaya']);
	
	//E. Kelembagaan
	$document->setValue('lpmJmlPengurus', $this->detailKelembagaan['lpm_jml_pengurus']);		
	$document->setValue('lpmJmlKegPerbulan', $this->detailKelembagaan['lpm_jml_keg_perbulan']);		
	//$document->setValue('lpmJmlBukuAdministrasi', $this->detailKelembagaan['lpm_jml_buku_administrasi']);
	$document->setValue('lpmJmlDana', $this->detailKelembagaan['lpm_jml_dana']);
	//$document->setValue('lembagaAdat', $this->detailKelembagaan['lembaga_adat']);
	$document->setValue('pkkJmlPengurus', $this->detailKelembagaan['pkk_jml_pengurus']);
	$document->setValue('pkkJmlKegPerbulan', $this->detailKelembagaan['pkk_jml_keg_perbulan']);
	$document->setValue('pkkJmlBukuAdministrasi', $this->detailKelembagaan['pkk_jml_buku_administrasi']);
	//$document->setValue('pkkJmlDana', $this->detailKelembagaan['pkk_jml_dana']);
	$document->setValue('jmlRw', $this->detailKelembagaan['jml_rw']);
	$document->setValue('jmlRt', $this->detailKelembagaan['jml_rt']);
	$document->setValue('rataPenghasilanRw', $this->detailKelembagaan['rata_penghasilan_rw']);
	$document->setValue('rataPenghasilanRt', $this->detailKelembagaan['rata_penghasilan_rt']);
	$document->setValue('tarunaJml', $this->detailKelembagaan['taruna_jml']);
	$document->setValue('tarunaJmlPengurus', $this->detailKelembagaan['taruna_jml_pengurus']);
	$document->setValue('jmlLembagaLain', $this->detailKelembagaan['jml_lembaga_lain']);	
	
	
	//nama file dokumen
	$namafile = "Laporan Monografi Kelurahan ". $this->detailKelurahan->kelurahan. " ".$this->bulan." ". $this->tahun ." .doc";
	
	// $document->save('E:\\'.$namafile);
	
	// At least write the document to webspace:
	$objWriter = PHPWord_IOFactory::createWriter($PHPWord, 'Word2007');
	
	
	

	
	// // save as a random file in temp file
	$temp_file = tempnam(sys_get_temp_dir(), 'PHPWord');
	$document->save($temp_file);
	
	// Your browser will name the file "myFile.docx"
	// regardless of what it's named on the server 
	header('Content-Type: application/octet-stream');
	header('Content-Disposition: attachment; filename="' . $namafile . '"');
	header('Content-Transfer-Encoding: binary');
	header('Cache-Control: must-revalidate, post-check=0, pre-check=0');
	header('Expires: 0');
	header('Pragma: public');
	flush();
	readfile($temp_file); // or echo file_get_contents($temp_file);
	unlink($temp_file);  // remove temp file
	
?>