<?
require_once 'Zend/View.php';
require_once 'share/format_date.php'; 
require_once 'share/format_page.php';
require_once "share/share_message.php";
require_once "share/oa_dec_cur_conv.php";

$ctrlFrm = new Zend_View();
$pesan = new share_message();
$halaman = new format_page();
$dec_cur = new oa_dec_cur_conv();
$format_date = new format_date();


$currentPage = $this->currentPage;
$numToDisplay = $this->numToDisplay;
?>
<div class="navlink">
<a href="#" onclick="open_url_to_home('<?php echo $this->basePath; ?>/home/index/depan','<?php echo $this->basePath; ?>/home/index/main');">Halaman Utama</a>
>>  Data Rekam Kelurahan
</div>
<div class="panel">
	<div class="inner">
		<span class="corners-top"><span></span></span>
		<h2 class="title">Data Kelurahan <strong><?php echo strtoupper($this->detailKelurahan->kelurahan) ?></strong></h2>
		
			<form method="post" id="frmcarirekamkelurahan" name="frmcarirekamkelurahan">
				<input name="kd_kel" id="kd_kel" type="hidden" value="<?echo $this->kd_kel;?>" />
				Filter :
					<?
						$kategoriCari = array("P.tahun" => "Tahun", "P.bulan" => "Bulan");
						echo $ctrlFrm->formSelect('kategoriCari', $this->kategoriCari, null, $kategoriCari);						
					?>
					<input type="text" name="carii" id="carii" align="center" value ="<? echo $this->carii;?>">
					<?
						$atribSubmit = array("onclick"=>"javascript:carirekamkelurahan();");
						echo $ctrlFrm->formSubmit('cari', 'Search', $atribSubmit)."&nbsp;";
					?>
			</form>
		
<fieldset class="fields"> 
<? 
$status = $this->hasil;
$proses = $this->proses;
$pesan->show_message($proses, $this->detailKelurahan->kelurahan." bulan ".$this->bulan ." tahun ".$this->tahun, "$status" ); 
?>

<table width="100%" border="0" cellpadding="0" cellspacing="1" class="std">
				</table>
<div class="add" title="Tambah Data" ></div>	

<table id="sorter" class="sortable" cellspacing="0" cellpadding="2" border="0" align="center">
				<th >No</th>
				<th >Bulan</th>
				<th >Tahun</th> 
				<th >Nama Lurah</th> 
				<th >NIP Lurah</th>
				<th colspan="2" class="nosort">Cetak</th>
				<th colspan="2" class="nosort">FUNGSI</th>
				
				<?
				if (count($this->rekamkelurahanlist) == 0){ 
				?>
					<tr class="event2"><td colspan="8"  style="color:#8C0000; font-weight:bold; background-color: #FF9999">Data Tidak Ditemukan</td></tr>
				<?} else {
						
						
						foreach ($this->rekamkelurahanlist as $key => $val): 
						if ($key%2==0) { ?>
							<tr class="event">
						<? } else if ($key%2==1) { ?>
							<tr class="event2">
						<? }
						$kd_kel	= $this->escape($val['kd_kel']);						
						$tahun	= $this->escape($val['tahun']); 
						$bulan	= $this->escape($val['bulan']); 
						
						//Array Bulan 
						$array_bulan = array(1=>'Januari','Februari','Maret', 'April', 'Mei', 'Juni','Juli','Agustus','September','Oktober', 'November','Desember'); 
						$bulan1 = $array_bulan[$this->escape($val['bulan'])];
						$nama_lurah	= $this->escape($val['nama_lurah']);
						$nip_lurah	= $this->escape($val['nip_lurah']);
						
						$noUrut = (($currentPage -1)* $numToDisplay) + $key +1;
						echo $ctrlFrm->formHidden('kd_kel', $kd_kel, null);
						
						?>
							
						<td align="center"><? echo $noUrut;?></td>
						<td align="center"><? echo $bulan1;?></td>
						<td align="center"><? echo $tahun;?></td>
						<td class="clleft"><? echo $nama_lurah;?></td>
						<td class="clleft"><? echo $nip_lurah;?></td>
						


<td><a  href="<?php echo $this->basePath; ?>/kelurahan/rekamkelurahan/rekamkelurahancetak?kd_kel=<?echo $kd_kel;?>&bulan=<?echo $bulan;?>&tahun=<?echo $tahun;?>"><div class="buku" title= "cetak buku <?php echo $this->detailKelurahan->kelurahan?>"></div></a> </td>
<td><div onClick="rekamkelurahanForm('update','<? echo $kd_kel;?>','<? echo $bulan;?>','<? echo $tahun;?>');" class="edit1" title="Ubah Data"></div></td>
<td><div onClick="rekamkelurahanHapus('<? echo $kd_kel;?>','<? echo $this->detailKelurahan->kelurahan ;?>','<? echo $tahun;?>','<? echo $bulan;?>');" class="delete" title="Hapus Data"></div>
						</td>
						
					
						</tr>
					<?
					endforeach;
				}
				?>
			</table>

			<?	
			$totalData = $this->totRekamkelurahanList;
			$modul = $this->basePath."/kelurahan/rekamkelurahan/rekamkelurahanlist";
			// $param1 = $this->cabang;$param2 = $this->tahun;$param3 = $this->bulan;$param4 = $this->jenis;$param5 = $this->status;
			echo $halaman->showPage($totalData, $numToDisplay, $currentPage, 'tableview', $modul, $param1, $param2, $param3, $param4);		
			
			?>
		</fieldset>		 
		
		<span class="corners-bottom"><span></span></span>
	</div>
</div>
<script type="text/javascript">

  
var sorter=new table.sorter("sorter");
sorter.init("sorter",0);
</script>

 <style>
    	.box {
			  width: 600px;
			  height: 200px;
			  background-color: #2c3e50;
			  border-radius: 5px;
			  position: absolute;
			  left: 50%;
			  margin-top: -150px;
			  margin-left: -300px;
			  top: -9999px;
			  z-index: 1000;
			  box-shadow: 0 1px 1px rgba(0, 0, 0, 0.4) inset, 0 1px 0 rgba(255, 255, 255, 0.2);
		}
		.box .pesan {
			  position: absolute;
			  top: 30px;
			  right: 10px;
			  bottom: 10px;
			  left: 10px;
			  padding: 5px 10px;
			  overflow: auto;
			  background-color: #1abc9c;
			  color: #fff;
			  text-align: left;
			  line-height: 1.5em;
			  font-size: 14px;
			  border-radius: 0 0 5px 5px;
			}
		.pesan .ttd:after {
			  content: "";
			  position: relative;
			  float: right;
			}
		.close:after {
		  content: url('<? echo $this->basePath;?>/icon/delete4.png');
		  position: absolute;
		  top: -10px;
		  right: -10px;
		  background: #ecf0f1;
		  border-radius: 100%;
		  padding: 10px;
		  z-index: 1000;
		  cursor: pointer;
		}

    </style>


<div class='box'>
  <div class='pesan'>
		<h2>
			* Pilih Periode Bulan dan Tahun untuk disalin
		</h2>
			<br />
				<select name="bulan" id="bulan" class="autowidth">
					<option selected="selected">Bulan</option>
					<?php
					
					$bulan_ind=array("Januari","Februari","Maret","April","Mei","Juni","Juli","Agustus","September","Oktober","November","Desember");
					$bulan=array("1","2","3","4","5","6","7","8","9","10","11","12");
					$jlh_bln=count($bulan_ind);
					for($c=0; $c<$jlh_bln; $c+=1){
						
						echo"<option value=$bulan[$c]> $bulan_ind[$c] </option>";
					}
					?>
					</select>
					<select name="tahun" id="tahun"  class="autowidth">
					<option selected="selected">Tahun</option>
					<?php
					for($i=date('Y'); $i>=2010; $i-=1){
						
					echo"<option value=$i> $i </option>";
					}
					?>
					</select>
		<input type="submit" value="Pilih" onClick="rekamkelurahanFormCopy('insert','<? echo $this->kd_kel;?>','','');"/>
 <span class='ttd'></span>
  </div>
<div class='close'></div>
</div>



<script type='text/javascript'>
//<![CDATA[
$(document).ready(function () {
//tampilkan kotak dialog saat muncul dengan class info
    $('.add').click(function () {
        $('.box').fadeIn(9000).css({top: '50%',position: 'fixed'})
        // $('body').css({background: '#123',transition: 'all 5s'}) //efect body berubah warna
    });
//sembunyikan kotak dialog dengan class close
    $('.close').click(function () {
		$('.box').fadeOut().delay(9000);
        // $('body').css({background: '#ecf0f1',transition: 'all 5s'}) //efect body berubah warna
    })
});
//]]>
</script>