
function cariListshoutbox(){
	var cat=document.getElementById('cat').value;
	var key=document.getElementById('key').value;
	var url = '<?php echo $this->basePath; ?>/cmsmodule/shoutbox/listshoutbox';	
	var param = {cat:cat,key:key};
		jQuery.get(url, param, function(data) {
			jQuery("#tableview").html(data);
		});
} 

function shoutboxM(par,id){

	var url = '<?php echo $this->basePath;?>/cmsmodule/shoutbox/shoutbox';	
	var param = {par:par,id:id};
		jQuery.get(url, param, function(data) {
			jQuery("#tableview").html(data);
			jQuery("#formshoutbox").ajaxForm(maintain_shoutbox);
		});
}
function insertshoutbox(){
	jQuery("#formshoutbox").ajaxForm(maintain_shoutbox);
}
var maintain_shoutbox = {
	target:'#tableview',
	beforeSubmit: function() {		
		aobj= document.formshoutbox;
		astr= "document.formshoutbox";
		var cekVal="";
		with(aobj){      
			var Proceed = 1;
			while (Proceed == 1)
			{
				/*sdmValidasiData (navigation.js)
				if((!title.value)){cekVal = sdmValidasiData(astr,"i_peg_nip","Judul shoutbox harus diisi....!");return false;break;}*/
				break;
			}
			
		}
		
		//if (cekVal == false) {return false;}
	
	}, 
	success:function(){
		location.href="#top";
		doCounter(5);
		jQuery("#formshoutbox").ajaxForm(maintain_shoutbox);
	},
	url: '<?php echo $this->basePath; ?>/cmsmodule/shoutbox/maintaindata',
	type: 'post',
	resetForm: false
};



function HapusDatashoutbox(id,jdl)
{
	var where_to= confirm("Yakin anda akan hapus data shoutbox :"+jdl);
	 if (where_to== true)
	 {
		url = "<?php echo $this->basePath; ?>/cmsmodule/shoutbox/hapusdata"
		 
		var opt = {id:id};
		jQuery.get(url,opt,function(data) {
			jQuery("#tableview").html(data);
				location.href="#top";
				doCounter(5);
			});
	 }
}

