<? require_once 'Zend/View.php';
    require_once 'share/halaman_list_portal.php';
    require_once 'share/Portalconf.php';
  
   $ctrlFrm = new Zend_View();
   $halaman = new halaman_list(); 
  
    $jmlpengumumanList = count($this->pengumumanList);
	//echo $jmlpengumumanList;
   for ($j = 0; $j < $jmlpengumumanList; $j++) {
     $pengumuman[$j] = array("c_pengumuman"  		=>(string)$this->pengumumanList[$j]['c_pengumuman'],
						"n_judul"      		=>(string)$this->pengumumanList[$j]['n_judul'],
						 "n_detil"  		=>(string)$this->pengumumanList[$j]['n_detil'],
						  "c_status"  		=>(string)$this->pengumumanList[$j]['c_status'],
						  "d_pengumuman"  		=>(string)$this->pengumumanList[$j]['d_pengumuman']);
   } 
$tgl=$_REQUEST['tgl'];
$bln=$_REQUEST['bln'];
$thn=date(Y);
$thnx=$_REQUEST['thn'];
if ($thnx=='') $thn=$thn;
else $thn=$thnx;
$key=$_REQUEST['key'];
?>
<div class="widget">
	<h4 class="widgettitle">Konten</h4>
<div class="content">
	<h2 class="title">Arsip Pengumuman</h2>

	<ul class="nostyle">


<? 		if ($jmlpengumumanList == 0) {?>
<span class="highlight">Data pengumuman tidak ditemukan !</span><br>
<a class="all" href="#indexpengumuman" onclick="goExec_Script('<?php echo $this->basePath; ?>/portalmodule/pengumuman/indekspengumuman','<?php echo $this->basePath; ?>/portalmodule/pengumuman/pengumumanjs', 'Pengumuman')">Kembali</a>

<?}else{
?>
<fieldset class="searchpanel center">
				<form id="frmSearch" method="post" name="frmSearch">
					<select size="1" name="tgl" id="tgl">  
<?

  echo "<option value=''>Tgl</option>";
  for ($i=1; $i<=31; $i++) {
    if($i<10) $i='0'.$i;
    echo "<option value=$i";
    if ($tgl==$i) echo " selected";
    echo ">$i</option>";
  }
?>
  </select>
  <select size="1" name="bln" id="bln">  
<?
  echo "<option value=''>Bln</option>";
  while(list($x,$v)=each($BULAN)) {
    if($x<10) $x='0'.$x;
    echo "<option value=$x";
    if ($bln==$x) echo " selected";
    echo ">$v</option>";
  }
?>
</select>
					<input id="thn" type="text" name="thn" class="inputbox" size="4" maxlength="4" value="<?=$thn?>">
					<input id="key" type="text" name="key" class="inputbox" value="<?=$key?>" size="40">
					<input type="button" class="button2" value="Cari" onclick="javascript:cariListPengumuman();">		   
				</form>						
	</fieldset>	
<?php	
				foreach ($pengumuman as $key => $val): 
				$noUrut = (($this->currentPage -1)* $this->numToDisplay) + $key +1;
				$date=formatDate3($this->escape($val['d_pengumuman']));
				
				?>

	<li><span class="date"><?php echo $date ?></span>
      <h3><a href="#" onclick="showDetilmed('<?php echo $this->basePath; ?>/portalmodule/pengumuman/pengumumandetil','<?=$this->escape($val['c_pengumuman'])?>','<?php echo $this->basePath; ?>/portalmodule/pengumuman/indekspengumuman','<?php echo $this->basePath; ?>/portalmodule/pengumuman/pengumumanjs','Pengumuman');"><?php echo $this->escape($val['n_judul']);?></a></h3></li>

				<?php endforeach;}?>
</ul>				

	<div class="space"></div>
<div id="targetdetil"></div>

<?
$modul = $this->basePath."/portalmodule/pengumuman/indekspengumuman";
if ($jmlPengumumanList != 0) echo $halaman->halamanList($this->totalpengumumanList, $this->numToDisplay, $this->currentPage, $modul)
?>	

	<div class="space"></div>
</div>
