<?php 
require_once 'Zend/View.php';
require_once "share/tanggal.php";  
require_once 'share/Portalconf.php'; 

/*$vFoto = $this->basePath."../data/sdm/photo/".trim($this->i_peg_nip).".jpg";

	if (!file_exists($vFoto)) {
		$vFoto = $this->basePath."../images/nophoto.jpg";
	} 
*/
?>
<div class="widget">
	<h4 class="widgettitle">Konten</h4>
	<div class="content">		
		<h2 class="title"><?=$this->jdlpengumuman?></h2>
		<span class="date"><?=formatDate3($this->tglpengumuman)?></span><br>
		<?=$this->detilpengumuman?>
		<div class="hr"></div>
		<a class="all" href="#indexpengumuman" onclick="goExec_Script('<?php echo $this->basePath; ?>/portalmodule/pengumuman/indekspengumuman','<?php echo $this->basePath; ?>/portalmodule/pengumuman/pengumumanjs', 'pengumuman')">Arsip Pengumuman</a>		
	</div>
</div>
