<?
require_once 'Zend/View.php';
require_once 'share/format_date.php'; 
require_once 'share/format_page.php';
require_once "share/share_message.php";
require_once "share/oa_dec_cur_conv.php";

$ctrlFrm = new Zend_View();
$pesan = new share_message();
$halaman = new format_page();
$dec_cur = new oa_dec_cur_conv();
$format_date = new format_date();

$currentPage = $this->currentPage;
$numToDisplay = $this->numToDisplay;
?>
<div class="navlink">
<a href="#" onclick="open_url_to_home('<?php echo $this->basePath; ?>/home/index/depan','<?php echo $this->basePath; ?>/home/index/main');">Halaman Utama</a>
>> Data Pasien
</div>

<div id="dialog-browse">  
</div>

<div class="panel">
	<div class="inner">
		<span class="corners-top"><span></span></span>
		<h2 class="title">FORM DATA PASIEN</h2>
	    <div class="spacer"></div> 
		
		<? if(strtolower($this->jenisForm) == 'insert') {$namaForm = 'frmtambahpendaftaran'; }
			else if (strtolower($this->jenisForm) == 'update') {$namaForm = 'frmubahpendaftaran'; }
			else {$namaForm = 'frmhapuspendaftaran'; }
		?>

		<form method="post" name="<? echo $namaForm;?>" id="<? echo $namaForm;?>">
<?
	$status = $this->hasil;
	$proses = $this->proses;
	$keterangan = $this->keterangan;
	$pesan->show_message($proses, $keterangan, "$status" ); 
?>
			<table width="100%" border="0" cellpadding="0" cellspacing="1" class="std">
<input name="id" id="id" type="hidden" value="<?echo $this->id;?>" />
<input name="kategoriCari" id="kategoriCari" type="hidden" value="<?echo $this->kategoriCari;?>" />
<input name="carii" id="carii" type="hidden" value="<?echo $this->carii;?>" />
<input name="id_user" id="id_user" type="hidden" value="<?echo $this->detailPendaftaran['id_user'];?>" />

				
				
				<tr>
				    <td align="right" width="180">* noreg :</td>
					<td>	
	<? 
	$c_noregAttrib = array("size" => 50,"maxlength" => 50);
	echo $ctrlFrm->formText("c_noreg", $this->detailPendaftaran['c_noreg'], $c_noregAttrib);
	?>
				</td>
				</tr>

				
				
				<tr>
				    <td align="right" width="180">* Nama :</td>
					<td>	
	<? 
	$n_namaAttrib = array("size" => 50,"maxlength" => 50);
	echo $ctrlFrm->formText("n_nama", $this->detailPendaftaran['n_nama'], $n_namaAttrib);
	?>
				</td>
				</tr>

				<tr>
				    <td align="right" width="180">* Jenis Kelamin :</td>
					<td>
	<?
	$genderList['-'] = '--Pilih--';
	$genderList['L'] = 'Laki-Laki';
	$genderList['P'] = 'Perempuan';
	$jenis_pendAtrib = array("id"=>"c_kelamin", "tabindex"=>"17");
	echo $ctrlFrm->formSelect('c_kelamin', trim($this->detailPendaftaran['c_kelamin']), $genderAtrib, $genderList);
	?>
					</td>
				</tr>

				<tr>
				    <td align="right" width="180">* waktu :</td>
					<td>	
	<? 
	$t_waktuAttrib = array("size" => 50,"maxlength" => 50);
	echo $ctrlFrm->formText("t_waktu", $this->detailPendaftaran['t_waktu'], $t_waktuAttrib);
	?>
				</td>
				</tr>
				
				<tr>
				    <td align="right" width="180">* tempat :</td>
					<td>	
	<? 
	$n_tempatAttrib = array("size" => 50,"maxlength" => 50);
	echo $ctrlFrm->formText("n_tempat", $this->detailPendaftaran['n_tempat'], $n_tempatAttrib);
	?>
				</td>
				</tr>
				
				<tr>
				    <td align="right" width="180">* berat :</td>
					<td>	
	<? 
	$t_beratAttrib = array("size" => 50,"maxlength" => 50);
	echo $ctrlFrm->formText("t_berat", $this->detailPendaftaran['t_berat'], $t_beratAttrib);
	?>
				</td>
				</tr>
				
				
				</td>
				</tr>

				<tr>
				    <td align="right" width="180">* tinggi :</td>
					<td>	
	<? 
	$t_tinggiAttrib = array("size" => 50,"maxlength" => 50);
	echo $ctrlFrm->formText("t_tinggi", $this->detailPendaftaran['t_tinggi'], $t_tinggiAttrib);
	?>
				</td>
				</tr>
				
				<tr>
				    <td align="right" width="180">* tekanan :</td>
					<td>	
	<? 
	$t_tekananAttrib = array("size" => 50,"maxlength" => 50);
	echo $ctrlFrm->formText("t_tekanan", $this->detailPendaftaran['t_tekanan'], $t_tekananAttrib);
	?>
				</td>
				</tr>
				
				<tr>
				    <td align="right" width="180">* denyut :</td>
					<td>	
	<? 
	$t_denyutAttrib = array("size" => 50,"maxlength" => 50);
	echo $ctrlFrm->formText("t_denyut", $this->detailPendaftaran['t_denyut'], $t_denyutAttrib);
	?>
				</td>
				</tr>
				
				</td>
				</tr>

				<tr>
				    <td align="right" width="180">* frequensi :</td>
					<td>	
	<? 
	$t_frequensiAttrib = array("size" => 50,"maxlength" => 50);
	echo $ctrlFrm->formText("t_frequensi", $this->detailPendaftaran['t_frequensi'], $t_frequensiAttrib);
	?>
				</td>
				</tr>
				
				<tr>
				    <td align="right" width="180">* suhu :</td>
					<td>	
	<? 
	$t_suhuAttrib = array("size" => 50,"maxlength" => 50);
	echo $ctrlFrm->formText("t_suhu", $this->detailPendaftaran['t_suhu'], $t_suhuAttrib);
	?>
				</td>
				</tr>
				
				<tr>
				    <td align="right" width="180">* mata :</td>
					<td>	
	<? 
	$n_mataAttrib = array("size" => 50,"maxlength" => 50);
	echo $ctrlFrm->formText("n_mata", $this->detailPendaftaran['n_mata'], $n_mataAttrib);
	?>
				</td>
				</tr>
				
				<tr>
				    <td align="right" width="180">* tht :</td>
					<td>	
	<? 
	$n_thtAttrib = array("size" => 50,"maxlength" => 50);
	echo $ctrlFrm->formText("n_tht", $this->detailPendaftaran['n_tht'], $n_thtAttrib);
	?>
				</td>
				</tr>
				
				<tr>
				    <td align="right" width="180">* gigi :</td>
					<td>	
	<? 
	$n_gigiAttrib = array("size" => 50,"maxlength" => 50);
	echo $ctrlFrm->formText("n_gigi", $this->detailPendaftaran['n_gigi'], $n_gigiAttrib);
	?>
				</td>
				</tr>
				
				<tr>
				    <td align="right" width="180">* leher :</td>
					<td>	
	<? 
	$n_leherAttrib = array("size" => 50,"maxlength" => 50);
	echo $ctrlFrm->formText("n_leher", $this->detailPendaftaran['n_leher'], $n_leherAttrib);
	?>
				</td>
				</tr>
				
				<tr>
				    <td align="right" width="180">* jantung :</td>
					<td>	
	<? 
	$n_jantungAttrib = array("size" => 50,"maxlength" => 50);
	echo $ctrlFrm->formText("n_jantung", $this->detailPendaftaran['n_jantung'], $n_jantungAttrib);
	?>
				</td>
				</tr>
				
				<tr>
				    <td align="right" width="180">* paru :</td>
					<td>	
	<? 
	$n_paruAttrib = array("size" => 50,"maxlength" => 50);
	echo $ctrlFrm->formText("n_paru", $this->detailPendaftaran['n_paru'], $n_paruAttrib);
	?>
				</td>
				</tr>
				
				<tr>
				    <td align="right" width="180">* perut :</td>
					<td>	
	<? 
	$n_perutAttrib = array("size" => 50,"maxlength" => 50);
	echo $ctrlFrm->formText("n_perut", $this->detailPendaftaran['n_perut'], $n_perutAttrib);
	?>
				</td>
				</tr>
				
				<tr>
				    <td align="right" width="180">* gerak :</td>
					<td>	
	<? 
	$n_gerakAttrib = array("size" => 50,"maxlength" => 50);
	echo $ctrlFrm->formText("n_gerak", $this->detailPendaftaran['n_gerak'], $n_gerakAttrib);
	?>
				</td>
				</tr>
				
				<tr>
				    <td align="right" width="180">* gizi :</td>
					<td>	
	<? 
	$n_giziAttrib = array("size" => 50,"maxlength" => 50);
	echo $ctrlFrm->formText("n_gizi", $this->detailPendaftaran['n_gizi'], $n_giziAttrib);
	?>
				</td>
				</tr>
				
				<tr>
				    <td align="right" width="180">* potensi :</td>
					<td>	
	<? 
	$n_potensiAttrib = array("size" => 50,"maxlength" => 50);
	echo $ctrlFrm->formText("n_potensi", $this->detailPendaftaran['n_potensi'], $n_potensiAttrib);
	?>
				</td>
				</tr>
				
				<tr>
				    <td align="right" width="180">* mental :</td>
					<td>	
	<? 
	$n_mentalAttrib = array("size" => 50,"maxlength" => 50);
	echo $ctrlFrm->formText("n_mental", $this->detailPendaftaran['n_mental'], $mentalAttrib);
	?>
				</td>
				</tr>
				
				<tr>
				    <td align="right" width="180">* reproduksi :</td>
					<td>	
	<? 
	$n_reproduksiAttrib = array("size" => 50,"maxlength" => 50);
	echo $ctrlFrm->formText("n_reproduksi", $this->detailPendaftaran['n_reproduksi'], $n_giziAttrib);
	?>
				</td>
				</tr>
				
				<tr>
				    <td align="right" width="180">* kematangan :</td>
					<td>	
	<? 
	$n_kematanganAttrib = array("size" => 50,"maxlength" => 50);
	echo $ctrlFrm->formText("n_kematangan", $this->detailPendaftaran['n_kematangan'], $n_kematanganAttrib);
	?>
				</td>
				</tr>
				
				<tr>
				    <td align="right" width="180">* hb :</td>
					<td>	
	<? 
	$n_hbAttrib = array("size" => 50,"maxlength" => 50);
	echo $ctrlFrm->formText("n_hb", $this->detailPendaftaran['n_hb'], $n_hbAttrib);
	?>
				</td>
				</tr>
				
				
				<tr>
				    <td align="right" width="180">* feses :</td>
					<td>	
	<? 
	$n_fesesAttrib = array("size" => 50,"maxlength" => 50);
	echo $ctrlFrm->formText("n_feses", $this->detailPendaftaran['n_feses'], $n_fesesAttrib);
	?>
				</td>
				</tr>
				
				<tr>
				    <td align="right" width="180">* jasmani :</td>
					<td>	
	<? 
	$n_jasmaniAttrib = array("size" => 50,"maxlength" => 50);
	echo $ctrlFrm->formText("n_jasmani", $this->detailPendaftaran['n_jasmani'], $n_jasmaniAttrib);
	?>
				
				
				<tr>
				    <td align="right" width="180">* Imunisasi saat bayi :</td>
					<td align="center">
							<input type="checkbox" name="c_bayi" id="c_bayi" value="tidak">
						</td>
				</tr>
				<tr>
				    <td align="right" width="180">* Imunisasi kelas 1 :</td>
					<td align="center">
							<input type="checkbox" name="c_imunisasi1" id="c_imunisasi1" value="tidak">
						</td>
				</tr>
				
				    <td align="right" width="180">* Imunisasi kelas 2 :</td>
					<td align="center">
							<input type="checkbox" name="c_imunisasi2" id="c_imunisasi2" value="tidak">
						</td>
				</tr>
				
				    <td align="right" width="180">* Imunisasi kelas 3 :</td>
					<td align="center">
							<input type="checkbox" name="c_imunisasi3" id="c_imunisasi3" value="tidak">
						</td>
				</tr>
				
				
				
					
				<tr>
				    <td></td>
				    <td>
						<div class="right">
<input type="button" value="Batal" onclick="pendaftaranlist()"> 
<input type="reset" value="Ulangi"> 
<input   type="submit" value="Simpan">


						</div>
					</td>
				</tr>
				<tr>
				    <td>* Harus Diisi</td>
				    <td></td>
				</tr>
			</table>
		</form>
	</div>
</div>

<script>

 	$(function() {
		$("#d_lahir").datepicker();
	});


function showDialog(val,jum) {      
    $( "#dialog-browse" ).dialog({
      autoOpen: false,
      height: 380,
      width: 640,
      modal: true,
      resizable:false,
      title: "Data"
    });
    if(val =='dosen'){dosenlist(jum);}  
    if(val =='prodi'){prodilist();}  
    return false;
  }

</script>

