
function cariListagenda(){
	var status=document.getElementById('status').value;
	var key=document.getElementById('key').value;
	var url = '<?php echo $this->basePath; ?>/cmsmodule/agenda/listagenda';	
	var param = {status:status,key:key};
		jQuery.get(url, param, function(data) {
			jQuery("#tableview").html(data);
		});
} 

function agendaM(par,idagenda){

	var url = '<?php echo $this->basePath;?>/cmsmodule/agenda/agenda';	
	var param = {par:par,idagenda:idagenda};
		jQuery.get(url, param, function(data) {
			jQuery("#tableview").html(data);
			jQuery("#formagenda").ajaxForm(maintain_agenda);
		});
}
function insertagenda(){
	jQuery("#formagenda").ajaxForm(maintain_agenda);
}
var maintain_agenda = {
	target:'#tableview',
	beforeSubmit: function() {		
		aobj= document.formagenda;
		astr= "document.formagenda";
		var cekVal="";
		with(aobj){      
			var Proceed = 1;
			while (Proceed == 1)
			{
				/*sdmValidasiData (navigation.js)*/
				if((!title.value)){cekVal = sdmValidasiData(astr,"title","Judul agenda harus diisi....!");return false;break;}
				break;
			}
			
		}
		
		//if (cekVal == false) {return false;}
	
	}, 
	success:function(){
		location.href="#top";
		doCounter(5);
		jQuery("#formagenda").ajaxForm(maintain_agenda);
	},
	url: '<?php echo $this->basePath; ?>/cmsmodule/agenda/maintaindata',
	type: 'post',
	resetForm: false
};



function HapusDataagenda(idagenda,jdl)
{
	var where_to= confirm("Yakin anda akan hapus data agenda :"+jdl);
	 if (where_to== true)
	 {
		url = "<?php echo $this->basePath; ?>/cmsmodule/agenda/hapusdata"
		 
		var opt = {idagenda:idagenda};
		jQuery.get(url,opt,function(data) {
			jQuery("#tableview").html(data);
				location.href="#top";
				doCounter(5);
			});
	 }
}

function setvalueuplpdf(v,n,f) { 

	  if (f!="") {
	    var pass=false;
	    var af=f.split("/");
        var nval=eval("document.forms[0]."+n);
		var ext=v.substring(v.lastIndexOf(".")+1,v.length);
		if ((ext==f)||(ext=='png')||(ext=='gif')){ 
		document.forms[0].a_file.value=v; 
		}
		else{
		  alert ("Hanya untuk file berekstensi '"+f+"',jpg,gif,png ");
		  nval.value="";
		  document.forms[0].a_file.value=""; 
		  return;	  
		}
	  }
}