<? require_once 'Zend/View.php';
   require_once 'share/oa_date.php'; 
   
	$ctrlDate = new oa_date();   
   
   $ctrlFrm = new Zend_View();

$nip = $_REQUEST['nip'];
$_SESSION['nip'] = $nip;

	$jumAlamatList = count($this->alamatList);
   
   for ($j = 0; $j < $jumAlamatList; $j++) {
     $alamat[$j] = array("nip"  			=>(string)$this->alamatList[$j]['nip'],
						  "tglMulai"		=>(string)$this->alamatList[$j]['tglMulai'],
	                      "tglAkhir"     	=>(string)$this->alamatList[$j]['tglAkhir'],
						  "jalan"			=>(string)$this->alamatList[$j]['jalan'],
						  "rt"  			=>(string)$this->alamatList[$j]['rt'],
						  "rw"  			=>(string)$this->alamatList[$j]['rw'],
						  "kel"  			=>(string)$this->alamatList[$j]['kel'],
						  "kec"  			=>(string)$this->alamatList[$j]['kec'],
						  "kota"  			=>(string)$this->alamatList[$j]['kota'],
						  "prop"  			=>(string)$this->alamatList[$j]['prop'],
						  "kodePos"  		=>(string)$this->alamatList[$j]['kodePos'],
						  "telpRumah"  		=>(string)$this->alamatList[$j]['telpRumah'],
						  "keterangan"  	=>(string)$this->alamatList[$j]['keterangan']);	
   } 

	$pesan = $this->pesan;

   $spath = $this->getScriptPaths();
   $this->addScriptPath($spath[0] . 'viewpegawai');
   echo $this->render('viewpegawaijs.phtml'); 
   
?>
<div class="contentdata-modul" id="modul">
	<div class="navlink">Halaman Utama Pegawai</div>
	<h3 class="title">MELIHAT DATA RIWAYAT ALAMAT</h3>
	&nbsp;&nbsp;&nbsp;&nbsp;Menu ini digunakan untuk melihat data riwayat alamat pegawai.
	<div class="spacer"></div>
	<a name="top"></a>	
	<div class="search-panel">
		<fieldset class="panel-form3">	
			<form id="frmAlamat"action="/sdm/viewpegawai/alamat" method="post" name="frmAlamat">
				<?php include "menulink.phtml";?>  
				<?php include "datapokok.phtml";?>  
			</form>
		</fieldset>
	</div> <!--end div Search Panel-->

	<div class="space-line"></div>	
	<fieldset class="fields">
		<div class="title2">Melihat Data Riwayat Alamat</div>
			<? if (!$pesan == null) {
			?>
				<div class="spacer"> </div>
				<fieldset id="message" class="confirm"><? echo $pesan; ?></fieldset>
				<div class="spacer"> </div>	
			<?}?>

		<div class="blank"></div>


<?
	if ($jumAlamatList == 0) {
		echo "<font color=\"red\">Data Riwayat Alamat Tidak Ditemukan</font>";		
?>	
	<table class="tbl" cellspacing="1" cellpadding="2" border="0" align="center">
			<tr>
		    <th width="12%">Tanggal Mulai Tinggal</th>
			<th width="12%">Tanggal Terakhir Tinggal</th>
			<th width="45%">Alamat</th>
			<th width="15%">Telepon</th>
			<th width="16%">Keterangan</th>
			</tr>
	</table>
<?	}	else { ?>
	</center>
	<table class="tbl" cellspacing="1" cellpadding="2" border="0" align="center">
			<tr>
		    <th width="12%">Tanggal Mulai Tinggal</th>
			<th width="12%">Tanggal Terakhir Tinggal</th>
			<th width="45%">Alamat</th>
			<th width="15%">Telepon</th>
			<th width="16%">Keterangan</th>
			</tr>
		<?php foreach ($alamat as $key => $val): 
					   if ($key%2==0) { ?>
				      <tr class="event">
					<? } else if ($key%2==1) { ?>
					  <tr class="event2">
					<? } ?>
					<?
					$jalan = $this->escape($val['jalan']);
					$rt = $this->escape($val['rt']);
					$rw = $this->escape($val['rw ']);
					$kel = $this->escape($val['kel']);
					$kec = $this->escape($val['kec']);
					$kota = $this->escape($val['kota']);
					$prop = $this->escape($val['prop']);
					$kodePos = $this->escape($val['kodePos']);
					if ($rt == null){
						$rt = '-';
					}
					if ($rw == null){
						$rw = '-';
					}
					if ($kel == null){
						$kel = '-';
					}
					if ($kec == null) {
						$kec = '-';
					}
					if ($kota == null){
						$kota = '-';
					}
					if ($prop == null){
						$prop = '-';
					}
					
					//$alamat = $jalan."Rt:".$rt." Rw:".$rw." Kel:".$kel." Kec:".$kec." Kota:".$kota." Prop:".$prop;
					$alamatLengkap = $jalan." ".$kel." ".$kec." ".$kota." ".$prop." ".$kodePos;
					//echo "nama= ".$this->escape($val['hubungan']);	
					$tglAlamat= "Tanggal: ".$ctrlDate->convertTglMachineToHuman($this->escape($val['tglMulai']));
					?>
				<td class="clcenter"><a href="#" onClick="javascript:viewAlamat('<? echo $this->escape($val['nip']); ?>','<?php echo $this->escape($val['tglMulai']);?>','<?php echo $this->escape($val['jalan']);?>');" class="link" title="View"><?php echo $ctrlDate->convertTglMachineToHuman($this->escape($val['tglMulai']));?></a></td>
				<td class="clcenter"><?php echo $ctrlDate->convertTglMachineToHuman($this->escape($val['tglAkhir']));?></td>
				<td>&nbsp; <?php echo $alamatLengkap;?></td>
				<td>&nbsp; <?php echo $this->escape($val['telpRumah']);?></td>
				<td>&nbsp; <?php echo $this->escape($val['keterangan']);?></td>
		  </tr>
	<?php endforeach;?> 		  
		</table>
<? }	?>
		  
 			<dl>
				<dt>&nbsp;</dt>
				<dd class="dot2">&nbsp;</dd> 
				<dd class="col-right">
				<?php echo $ctrlFrm->formHidden('nipH', $nip, null)."&nbsp;";?>
				</dd>			
				<div class="back" onClick="javascript:kembaliSer();" title="Kembali"> <input type="button" value="Kembali" id="kembaliSehat"></div>
			</dl>
	
			</div>
 	</fieldset>
</div>			

		<?php echo $ctrlFrm->formHidden('nipH', $nip, null)."&nbsp;";?>
 