<? require_once 'Zend/View.php';
   require_once 'share/oa_date.php'; 
   
	$ctrlDate = new oa_date();   
   
   $ctrlFrm = new Zend_View();
   $thnskrg = date("Y");


	//$jenjang = $_REQUEST['jenjang'];
	$nip = $_REQUEST['nip'];
	//echo "test".$test;

   $spath = $this->getScriptPaths();
   $this->addScriptPath($spath[0] . 'viewpegawai');
   echo $this->render('viewpegawaijs.phtml'); 


?>
<div class="contentdata-modul" id="modul">
	<div class="navlink">Halaman Utama Pegawai</div>
	<h3 class="title">MELIHAT DATA PENGHARGAAN</h3>
	&nbsp;&nbsp;&nbsp;&nbsp;Menu ini digunakan untuk melihat data penghargaan yang pernah
 diperoleh pegawai.
	<div class="spacer"></div>
	<a name="top"></a>	
	<div class="search-panel">
		<fieldset class="panel-form3">
				<?php include "menulink.phtml";?>  
				<?php include "datapokok.phtml";?>  
		</fieldset>
	</div> <!--end div Search Panel-->

	<div class="space-line">
		<div class="title2">Data Penghargaan</div>
		<fieldset  class="panel-form">	
			<form id="frmVHargaView" action="<?php echo $this->basePath; ?>/sdm/viewpegawai/penghargaanview" method="post" name="frmVHargaView">
				<dl>
					<dt>Nama Penghargaan</dt>
					<dd class="dot2">:</dd> 
					<dd class="col-right">
					<?php 
						$nmHarga = $this->escape($this->nmHarga);
						echo $nmHarga; 
					?>
					</dd>
				</dl>
				<dl>
					<dt>Tahun</dt>
					<dd class="dot2">:</dd> 
					<dd class="col-right">
					<?php 
						$tahun = $this->escape($this->tahun);
						echo $tahun;
					?>
					</dd>
				</dl>
				<dl>
					<dt>Pemberi Penghargaan</dt>
					<dd class="dot2">:</dd> 
					<dd class="col-right">
					<?php 
						$lembaga = $this->escape($this->lembaga);
						echo $lembaga;
					?>
					</dd>
				</dl>
				<dl>
					<dt>Nomor Surat Penghargaan</dt>
					<dd class="dot2">:</dd> 
					<dd class="col-right">
					<?php 
						$noSurat = $this->escape($this->noSurat);
						echo $noSurat;
					?>
					</dd>
				</dl>
				<dl>
					<dt>Tanggal Surat Penghargaan</dt>
					<dd class="dot2">:</dd> 
					<dd class="col-right">
					<?php 
						$tglSurat = $this->escape($this->tglSurat);
						echo $ctrlDate->convertTglMachineToHuman($tglSurat);
					?>
					</dd>
				</dl>
				<dl>
					<dt>Keterangan</dt>
					<dd class="dot2">:</dd> 
					<dd class="col-right">
					<?php 
						$keterangan = $this->escape($this->keterangan);
						echo $keterangan;
					?>
					</dd>
				</dl>
 			<dl>
				<?php 
				  echo $ctrlFrm->formHidden('nipH', $nip, null)."&nbsp;";
				?>
				<dt>&nbsp;</dt>
				<dd class="dot2">&nbsp;</dd> 
				<dd class="col-right">&nbsp;</dd>			
				<div class="back" onClick="javascript:kembaliHargaView('<? echo $this->escape($this->nip); ?>');" title="Kembali"><input type="button" value="Kembali" id="kembaliHargaView"></div>
			</dl>
		  	</form>
		  	<div class="space-line"></div>
		  	<div><a href="#top" class="top" title="Kembali ke atas">Kembali ke atas</a></div>	  	
	         
		</fieldset>
	</div>
</div>		
	
<!--			<div class="back2">
			  <a href="#" onClick="javascript:kembaliHargaView('<? echo $this->escape($this->nip); ?>');" class="back" title="Kembali">Kembali</a>
			</div>
-->