<?
require_once 'Zend/View.php';
require_once 'share/format_date.php'; 
require_once 'share/format_page.php';
require_once "share/share_message.php";
require_once "share/oa_dec_cur_conv.php";

$ctrlFrm = new Zend_View();
$pesan = new share_message();
$halaman = new format_page();
$dec_cur = new oa_dec_cur_conv();
$format_date = new format_date();

$currentPage = $this->currentPage;
$numToDisplay = $this->numToDisplay;
?>

<div class="navlink">
<a href="#" onclick="open_url_to_home('<?php echo $this->basePath; ?>/home/index/depan','<?php echo $this->basePath; ?>/home/index/main');">Halaman Utama</a>
>> Data Kelurahan
</div>

<div id="dialog-browse">  
</div>

<div class="panel">
	<div class="inner">
		<span class="corners-top"><span></span></span>
		
		
		<? if(strtolower($this->jenisForm) == 'insert') {$namaForm = 'frmtambahkejadian'; $nama='tambah';}
			else if (strtolower($this->jenisForm) == 'update') {$namaForm = 'frmubahkejadian'; $nama='ubah'; }
			else {$namaForm = 'frmhapuskejadian';  $nama='hapus';}
		?>
		
		<h2 class="title">FORM <?php echo strtoupper($nama)?> KEJADIAN <strong><?php echo  strtoupper($this->detailKejadian['kelurahan']); ?></strong> </h2>
		
	    <div class="spacer"></div> 
		<form method="post" name="<? echo $namaForm;?>" id="<? echo $namaForm;?>" class="validasi" enctype="multipart/form-data">
<?
	$status = $this->hasil;
	$proses = $this->proses;
	$keterangan = $this->keterangan;
	$pesan->show_message($proses, $this->kd_kel, "$status" ); 
?>
	<table width="100%" border="0" cellpadding="0" cellspacing="1" class="std">
	
	<input name="idx_kejadian" id="idx_kejadian" type="hidden" value="<?echo $this->detailKejadian['idx_kejadian'];?>" />
	<input name="kategoriCari" id="kategoriCari" type="hidden" value="<?echo $this->kategoriCari;?>" />
	<input name="carii" id="carii" type="hidden" value="<?echo $this->carii;?>" />
				
		<?php if($this->kd_kel !=00) {?>			
		<input name="kd_kel" id="kd_kel" type="hidden" value="<?echo $this->kd_kel?>" />
		<input name="kelurahan" id="kelurahan" type="hidden" value="<?echo $this->detailKejadian['kelurahan'] ;?>" readonly />
		<?php }else {?>
			<tr>
				    <td align="right" width="100">* Kelurahan :</td>
					<td>	
				<select name="kd_kel" id="kd_kel">
				<?php 
				foreach($this->kelurahanList as $data): ?>
					<?php if($this->kd_kel== $this->escape($data->kd_kel)){ ?> 
						<option value="<?php echo $this->escape($data->kd_kel); ?>" selected><?php echo $this->escape($data->kelurahan); ?> </option>
				<?php }else{?>
				<option value="<?php echo $this->escape($data->kd_kel); ?>"> <?php echo $this->escape($data->kelurahan); ?> </option>
				 <?php }

				 endforeach; 
				}?>
			</select>
				</td>
			</tr>

			<tr>
				<td align="right" width="100">* Hari Kejadian:</td>
				<td>	
					<? 
						$hariAttrib = array("size" => 50,"maxlength" => 50,"required"=>"required");
						echo $ctrlFrm->formText("hari", $this->detailKejadian['hari'], $hariAttrib);
					?>
				</td>
			</tr>
			
			<tr>
				<td align="right" width="100">* Tanggal Kejadian :</td>
				<td>	
					<? 
						$tanggalAttrib = array("size" => 50,"maxlength" => 50,"required"=>"required");
						echo $ctrlFrm->formText("tanggal", $this->detailKejadian['tanggal'], $tanggalAttrib);
					?>
			</td>
			</tr>

			<tr>
				<td align="right" width="100">* Uraian :</td>
				<td>
					<textarea id="uraian" name="uraian" required><?php echo $this->detailKejadian['uraian']; ?></textarea>
					
				</td>
			</tr>
			
			<tr>
				<td align="right" width="100">* Waktu :</td>
				<td>	
					<input name="waktu" id="waktu" type="text" value="<?echo $this->detailKejadian['waktu'] ;?>"  placeholder="masukan jam kejadian. ex: 12:30" required />
			</td>
			</tr>
			
			<tr>
				<td align="right" width="100">* Lokasi :</td>
				<td>	
						<? 
						$lokasiAttrib = array("size" => 50,"maxlength" => 50,"required"=>"required");
						echo $ctrlFrm->formText("lokasi", $this->detailKejadian['lokasi'], $lokasiAttrib);
						?>
				</td>
			</tr>				
			
			</tr>

			<tr>
				<td align="right" width="100">* Kerugian :</td>
				<td>	
					<? 
					$kerugianAttrib = array("size" => 50,"maxlength" => 50,"required"=>"required");
					echo $ctrlFrm->formText("kerugian", $this->detailKejadian['kerugian'], $kerugianAttrib);
					?>
			</td>
			</tr>
			
			<tr>
				<td align="right" width="100">* Nominal :</td>
				<td>	
					<? 	
						// hapus titik dari database
						$nominal = explode('.',$this->detailKejadian['nominal']);
						
						//fungsi ternary, jika variabel tidak kosong, kasih format ribuan, jika kosong isi dengan 0
						$nominal = (!empty($nominal[0])) ? number_format($nominal[0],0,',','.') : 0;
						
						$nominalAttrib = array("size" => 50,"maxlength" => 50,"required"=>"required","onkeydown"=>"javascript:return numbersonly(this, event)","onkeyup"=>"javascript:tandaPemisahTitik(this)");
						echo $ctrlFrm->formText("nominal", $nominal, $nominalAttrib);
					?>
			</td>
			</tr>
			<tr>
				<td align="right" width="100">* Tanggal Laporan :</td>
				<td>	
					<? 
						$tanggal_laporanAttrib = array("size" => 50,"maxlength" => 50,"required"=>"required");
						if(strtolower($this->jenisForm) == 'insert'){
							echo $ctrlFrm->formText("tanggal_laporan", date('Y-m-d'), $tanggal_laporanAttrib);
						}else{
							echo $ctrlFrm->formText("tanggal_laporan", $this->detailKejadian['tanggal_laporan'], $tanggal_laporanAttrib);
						
						}
					?>
			</td>
			<tr>
				<td align="right" width="100">* Pelapor :</td>
				<td>	
					<? 
						$pelaporAttrib = array("size" => 50,"maxlength" => 50,"required"=>"required");
						echo $ctrlFrm->formText("pelapor", $this->detailKejadian['pelapor'], $pelaporAttrib);
					?>
			</td>
			</tr>

			<tr>
				<td align="right" width="100">* Keterangan :</td>
				<td>	
					<textarea id="keterangan" name="keterangan"><?php echo $this->detailKejadian['keterangan']; ?></textarea>
			</td>
			</tr>

			<tr>
				<td align="right" width="100">* Lampiran :</td>					
				</td>	
				<?php if (strtolower($this->jenisForm) == 'update') { ?>
					<td> 
					<input type="file" name="lampiran" id="lampiran" onChange="setvalueuplfile(this.value,'lampiran','doc')" required /> 
					 <div class="fakefile">
						<input type="hidden" size="41" name="a_file" id="a_file" value="<? $this->detailKejadian['file_lampiran']?>"/>
					</div>
					
						<div id='wrap-1'>
							<input type="button" class='buttontest' value="delete">
						<a href="<?php echo $this->detailKejadian['file_lampiran']; ?>">
						 <img src="<?php echo $this->detailKejadian['file_lampiran']; ?>" border="0" width="900" height="300" alt="image1" target="nowa_strona" class="logotest">
						</a>

						</div>	
					</td>
					
				<?php } ?>
				<?php if (strtolower($this->jenisForm) == 'insert') { ?>
				 <td>
					<input type="file" name="lampiran" id="lampiran" onChange="setvalueuplfile(this.value,'lampiran','doc')" required />
				 </td>
				 <div class="fakefile">
					<input type="hidden" size="41" name="a_file" id="a_file" value="<? $this->detailKejadian['file_lampiran']?>"/>
				</div>
					<?php } ?>
			</tr>
			<tr>  
				<td>&nbsp;</td>
				<td width="500px;">&nbsp;</td>
				<td>
					
						<input type="button" value="Batal" onclick="kejadianlist()"> 
						<input type="reset" value="Ulangi"> 
						<input type="submit" value="Simpan">
				</td>
			</tr>
			<tr>
				<td>* Harus Diisi</td>
				<td></td>
			</tr>
	</table>
</form>
	</div>
</div>

<script>
	$(document).ready(function() {
	$(".validasi").validate();

});

 	$(function() {
		$("#tanggal").datepicker({
			dateFormat: 'yy-mm-dd',
			changeMonth: true,
			changeYear: true
		});
		
		$("#tanggal_laporan").datepicker({
			dateFormat: 'yy-mm-dd',
			changeMonth: true,
			changeYear: true
		});
		 
	});
	
	
	$(document).ready(function () {
    $('.buttontest').click(function () {
        $(this).parent().find('img.logotest').hide('slow');
    });
});
</script>

<style>
	img.logotest {
    width: 75%;
    height: 75%;
    display: block;
}
.buttontest {
}
</style>



