<?
require_once 'Zend/View.php';
require_once 'share/format_date.php'; 
require_once 'share/format_page.php';
require_once "share/share_message.php";
require_once "share/oa_dec_cur_conv.php";

$ctrlFrm = new Zend_View();
$pesan = new share_message();
$halaman = new format_page();
$dec_cur = new oa_dec_cur_conv();
$format_date = new format_date();

$currentPage = $this->currentPage;
$numToDisplay = $this->numToDisplay;
?>
<div class="navlink">
<a href="#" onclick="open_url_to_home('<?php echo $this->basePath; ?>/home/index/depan','<?php echo $this->basePath; ?>/home/index/main');">Halaman Utama</a>
>> Data Kelurahan
</div>

<div id="dialog-browse">  
</div>

<div class="panel">
	<div class="inner">
		<span class="corners-top"><span></span></span>
		
		
		<? if(strtolower($this->jenisForm) == 'insert') {$namaForm = 'frmtambahkejadian'; $nama='tambah';}
			else if (strtolower($this->jenisForm) == 'update') {$namaForm = 'frmubahkejadian'; $nama='ubah'; }
			else {$namaForm = 'frmhapusKejadian';  $nama='hapus';}
		?>
		
		<h2 class="title">FORM <?php echo strtoupper($nama)?> DATA KELURAHAN <strong><?php echo  strtoupper($this->detailKejadian['kelurahan']); ?></strong> </h2>
		
	    <div class="spacer"></div> 
		<form method="post" name="<? echo $namaForm;?>" id="<? echo $namaForm;?>" class="validasi">
<?
	$status = $this->hasil;
	$proses = $this->proses;
	$keterangan = $this->keterangan;
	$pesan->show_message($proses, $this->kd_kel, "$status" ); 
?>
			<table width="100%" border="0" cellpadding="0" cellspacing="1" class="std">
<input name="kd_kel" id="kd_kel" type="hidden" value="<?echo $this->detailKejadian['kd_kel'];?>" />
<input name="kategoriCari" id="kategoriCari" type="hidden" value="<?echo $this->kategoriCari;?>" />
	<input name="carii" id="carii" type="hidden" value="<?echo $this->carii;?>" />
				
				
				<tr>
				    <td align="right" width="180">* Hari :</td>
					<td>	
						<? 
							$hariAttrib = array("size" => 50,"maxlength" => 50,"required"=>"required");
							echo $ctrlFrm->formText("hari", $this->detailKejadian['hari'], $hariAttrib);
						?>
				</td>
				</tr>

				
				
				<tr>
				    <td align="right" width="180">* Tanggal :</td>
					<td>	
						<? 
							$tanggalAttrib = array("size" => 50,"maxlength" => 50,"required"=>"required");
							echo $ctrlFrm->formText("tanggal", $this->detailKejadian['tanggal'], $tanggalAttrib);
						?>
				</td>
				</tr>

				<tr>
				    <td align="right" width="180">* Uraian :</td>
					<td>
						<? 
							$uraianAttrib = array("size" => 50,"maxlength" => 50,"required"=>"required");
							echo $ctrlFrm->formArea("uraian",trim($this->detailKejadian['uraian']), $uraianAttrib);
						?>
					</td>
				</tr>

				<tr>
				    <td align="right" width="180">* Waktu :</td>
					<td>	
						<? 
						$waktuAttrib = array("size" => 50,"maxlength" => 50,"required"=>"required");
						echo $ctrlFrm->formText("waktu", $this->detailKejadian['waktu'], $waktuAttrib);
						?>
				</td>
				</tr>
				
				
				
				<tr>
				    <td align="right" width="180">* Lokasi :</td>
					<td>	
							<? 
							$lokasiAttrib = array("size" => 50,"maxlength" => 50,"required"=>"required");
							echo $ctrlFrm->formText("lokasi", $this->detailKejadian['lokasi'], $lokasiAttrib);
							?>
				</td>
				</tr>
				
				
				</td>
				</tr>

				<tr>
				    <td align="right" width="180">* Kerugian :</td>
					<td>	
						<? 
						$kerugianAttrib = array("size" => 50,"maxlength" => 50,"required"=>"required");
						echo $ctrlFrm->formText("kerugian", $this->detailKejadian['kerugian'], $kerugianAttrib);
						?>
				</td>
				</tr>
				
				<tr>
				    <td align="right" width="180">* Nominal :</td>
					<td>	
						<? 
							$nominalAttrib = array("size" => 50,"maxlength" => 50,"required"=>"required");
							echo $ctrlFrm->formText("nominal", $this->detailKejadian['nominal'], $nominalAttrib);
						?>
				</td>
				</tr>
				
				<tr>
				    <td align="right" width="180">* Pelapor :</td>
					<td>	
						<? 
							$pelaporAttrib = array("size" => 50,"maxlength" => 50,"required"=>"required");
							echo $ctrlFrm->formText("pelapor", $this->detailKejadian['pelapor'], $pelaporAttrib);
						?>
				</td>
				</tr>

				<tr>
				    <td align="right" width="180">* Keterangan :</td>
					<td>	
						<? 
							$keteranganAttrib = array("size" => 50,"maxlength" => 50,"required"=>"required");
							echo $ctrlFrm->formText("keterangan", $this->detailKejadian['keterangan'], $keteranganAttrib);
						?>
				</td>
				</tr>

				<tr>
				    <td align="right" width="180">* Lampiran :</td>
					<td>	
						<? 
							$lampiranAttrib = array("size" => 50,"maxlength" => 50,"required"=>"required");
							echo $ctrlFrm->formText("lampiran", $this->detailKejadian['lampiran'], $lampiranAttrib);
						?>
				</td>
				</tr>
				
			
	<tr>  
		<td>&nbsp;</td>
		<td width="500px;">&nbsp;</td>
		<td>
			
				<input type="button" value="Batal" onclick="kejadianlist()"> 
				<input type="reset" value="Ulangi"> 
				<input type="submit" value="Simpan">
		</td>
	</tr>
	<tr>
		<td>* Harus Diisi</td>
		<td></td>
	</tr>
</table>
</form>
	</div>
</div>

<script>
	$(document).ready(function() {
	$(".validasi").validate();
});
</script>

<script>



function showDialog(val,jum) {      
    $( "#dialog-browse" ).dialog({
      autoOpen: false,
      height: 380,
      width: 640,
      modal: true,
      resizable:false,
      title: "Data"
    });
    if(val =='dosen'){dosenlist(jum);}  
    if(val =='prodi'){prodilist();}  
    return false;
  }

</script>

