function caripendaftaran()
{
	$("#frmcaripendaftaran").ajaxForm(frmcaripendaftaran_opt);
}
var frmcaripendaftaran_opt = {
		target : '#tableview',
		url: '<?php echo $this->basePath; ?>/kelurahan/pendaftaran/pendaftaranlist',
		type: 'post', 
		resetForm: false
};
function pendaftaranlist()
{
	kategoriCari = document.getElementById('kategoriCari').value;
	kd_kel = document.getElementById('kd_kel').value;
	carii = document.getElementById('carii').value;
	var param = {kategoriCari:kategoriCari,carii:carii,kd_kel:kd_kel};
	var url = '<?php echo $this->basePath; ?>/kelurahan/pendaftaran/pendaftaranlist';
	jQuery.get(url, param, function(data) {
		$("div#tableview").html(data);
	});
}

function pendaftaranForm(jenisForm,kd_kel)
{
	kategoriCari = document.getElementById('kategoriCari').value;
	carii = document.getElementById('carii').value;
	var url = '<?php echo $this->basePath; ?>/kelurahan/pendaftaran/pendaftarandata';
	var param = { jenisForm:jenisForm, kd_kel:kd_kel,kategoriCari:kategoriCari,carii:carii};
	jQuery.get(url, param, function(data) {
		jQuery("div#tableview").html(data);
		jQuery("#frmtambahpendaftaran").ajaxForm(tambahPendaftaran_opt);
		jQuery("#frmubahpendaftaran").ajaxForm(ubahPendaftaran_opt);
	});
}

var tambahPendaftaran_opt = {
	target : '#tableview',
	url: '<?php echo $this->basePath; ?>/kelurahan/pendaftaran/pendaftaran',
	beforeSubmit : function() {
		
		if (document.getElementById('kode_wilayah').value == ''){
			alert('Kode Wilayah harus Diisi');
			return false;
		}

		if (document.getElementById('tahun_pembentukan').value == '-'){
			alert('Tahun Pembentukan harus Dipilih');
			return false;
		}

		
		
		
	answer = confirm('Apakah data anda masukan sudah benar?.\n\'OK\' Jika benar, \'Cancel\' jika tidak.' );

	//alert(answer);
	if(answer !=0) { 
		return true;
	}
	else{
		return false;
	}
		
	},
	success: function(){
	doCount(5);
	
	},
	type: 'post', 
	resetForm: false
};

var ubahPendaftaran_opt = {
	target : '#tableview',
	url: '<?php echo $this->basePath; ?>/kelurahan/pendaftaran/pendaftaranupdate',
	beforeSubmit : function() {
		if (document.getElementById('kode_wilayah').value == ''){
			alert('Kode Wilayah harus Diisi');
			return false;
		}

		if (document.getElementById('tahun_pembentukan').value == '-'){
			alert('Tahun Pembentukan harus Dipilih');
			return false;
		}
		answer = confirm('Apakah data anda masukan sudah benar?.\n\'OK\' Jika benar, \'Cancel\' jika tidak.' );
	if(answer !=0) { 
		return true;
	}
	else{
		return false;
	}

	},
	success: function(){
	doCount(5);
	jQuery("#frmubahpendaftaran").ajaxForm(ubahPendaftaran_opt);
	},
	type: 'post', 
	resetForm: false
};


function pendaftaranHapus(param1, param2, n_nama)
{ 
	if(ConfirmDelete(param1,n_nama))
	{	
		handler = '<?php echo $this->basePath; ?>/kelurahan/pendaftaran/pendaftaranhapus';
		var opt = {id : param2};
		jQuery.get(handler,opt,function(data) {
				$("#tableview").html(data);
				doCount(5);
			 });
	}
}

function BukaWindows(){
	var w = 0; 
	var h = 0;
	w = screen.availWidth;
	h = screen.availHeight;
	var popW = 800, popH = 600;
	var leftc = (w-popW)/2;
	var topc = (h-popH)/2;
	var selectWindow = window.open(url,'Selection', 'left=' + leftc + ',top=' + topc + ', width='+popW+',height='+popH+',resizable=0,scrollbars=yes');
}

function CariPengadaan()
{
	document.getElementById('n_pengadaan').readOnly = true;
	id_pengadaan = document.getElementById('id_pengadaan').value;

	url = "<?php echo $this->basePath; ?>/adm/pendaftaran/n_namapengadaan?id_pengadaan="+id_pengadaan;
	BukaWindows();
}

function cetak(id)
{
	var url = '<?php echo $this->basePath; ?>/kelurahan/pendaftaran/cetakkartupdf?&id='+id;
	swin = window.open(url,'win','scrollbars,width=600,height=400,top=80,left=140,status=yes,toolbar=no,menubar=yes,location=no');
	swin.focus();
}



function tambahKepada()
{
	alert(kd_kel);
	var url = '<?php echo $this->basePath; ?>/kelurahan/rekamkelurahan/rekamkelurahancetak?&kd_kel='+kd_kel'&bulan='+bulan'&tahun='+$tahun;
	swin = window.open(url,'win','scrollbars,width=600,height=400,top=80,left=140,status=yes,toolbar=no,menubar=yes,location=no');
	swin.focus();

}

function deleteRow(tableID, r) {
	var i=r.parentNode.parentNode.rowIndex;
	document.getElementById(tableID).deleteRow(i);
	var table = document.getElementById(tableID); 
	var rowCount = table.rows.length;  
	var idRow = rowCount*1;
	document.getElementById("jumlahItem").value = idRow;
	
}
function deleteRow2(param,id_item,no_item)
{ 
	if(ConfirmDelete(param, no_item))
	{	
		handler = '<?php echo $this->basePath; ?>/kelurahan/pendaftaran/pendaftaranhapus';
		//var opt = {id_item:id_item,tahun:tahun,cabang:cabang,kategoriCari:kategoriCari,carii:carii};
		jQuery.get(handler,function(data) {
				$("#tableview").html(data);
				doCount(5);
			 });
	}
}

function getKab(){
	var url = '<?php echo $this->basePath; ?>/kelurahan/pendaftaran/get-kab';
	var propinsi = document.getElementById('c_propinsi').value;
	var param = {propinsi:propinsi};	
	$.getJSON(url,param,function(data){
		$('#kota').find('option').remove().end();
		
		$('#kota').attr('disabled',false).end();
		$('.someElement').attr('disabled', '');
		$('#kota').append($('<option>').text("--Pilih--").attr('value', "-"));
		$.each(data, function(i, value) {
				$('#kota').append($('<option>').text(value.n_kab).attr('value', value.id_kab));
		  });
	});
}



function dosenlist(jum) {
  var url        = '<?php echo $this->basePath; ?>/kelurahan/pendaftaran/dosenlist';
  var param      = {jum:jum};
  jQuery.get(url,param,function(data) {   
    $("#dialog-browse").html(data);
    $("#dialog-browse").dialog("open");
  }); 
}

function cariDosen(jum)  {
  $("#frmCariDosen").ajaxForm(frmCariDosen_opt);
}

var frmCariDosen_opt = {
    target : '#dialog-browse',
    url: '<?php echo $this->basePath; ?>/kelurahan/pendaftaran/dosenlist',
    type: 'get', 
    resetForm: false
};

function closeDialogDosen(id_pegawai,nama,jum) {  
  $("#dialog-browse").dialog("close");
  $("#id_pegawai_"+jum).val(id_pegawai);
  $("#n_nama_"+jum).val(nama);
}




function prodilist() {
    var url        = '<?php echo $this->basePath; ?>/kelurahan/pendaftaran/prodilist';
    jQuery.get(url,function(data) {   
    $("#dialog-browse").html(data);
    $("#dialog-browse").dialog("open");
  }); 
}

function cariProdi()  {
  $("#frmCariProdi").ajaxForm(frmCariProdi_opt);
}

var frmCariProdi_opt = {
    target : '#dialog-browse',
    url: '<?php echo $this->basePath; ?>/kelurahan/pendaftaran/prodilist',
    type: 'get', 
    resetForm: false
};

function closeDialogProdi(c_prodi,n_prodi) {  
  $("#dialog-browse").dialog("close");
  $("#c_prodi").val(c_prodi);
  $("#n_prodi").val(n_prodi);
}


function umumproses()
{
	$("#frmubahpendaftaran").ajaxForm(frmubahpendaftaran_opt);
}
var frmubahpendaftaran_opt = {
		target : '#tableview',
		url: '<?php echo $this->basePath; ?>/kelurahan/pendaftaran/pendaftaranupdate',
		beforeSubmit : function() {

		if (document.getElementById('n_nik').value == ''){
			alert('NIK harus Diisi');
			return false;
		}
		if (document.getElementById('n_nama').value == ''){
			alert('Nama harus Diisi');
			return false;
		}
		if (document.getElementById('n_nip').value == ''){
			alert('NPM/NIP harus Diisi');
			return false;
		}
		if (document.getElementById('n_cp').value == ''){
			alert('Kontak Person harus Diisi');
			return false;
		}

		if (document.getElementById('n_hp').value == ''){
			alert('HP harus Diisi');
			return false;
		}

		if (document.getElementById('n_email').value == ''){
			alert('Email harus Diisi');
			return false;
		}
	answer = confirm('\n\   Saya menyetujui dan mematuhi peraturan yang dikeluarkan oleh Komite Etik Fakultas Kedokteran UNPAD. \n\n\   Dan saya menyatakan bahwa data yang saya masukan adalah benar, \n\n\   jika terbukti bahwa data yang saya masukan tidak benar maka saya bersedia ditutut\n\n\   secara hukum berdasarkan peraturan perundangan yang berlaku.\n\n   \'OK\' Jika setuju, \'Cancel\' Jika tidak setuju.');
		if(answer !=0) { 
			return true;
		}
		else{
			return false;
		}
		},
		type: 'post', 
		success: function(){doCount(5);},
		resetForm: false
};



