<?
require_once 'Zend/View.php';
require_once 'share/format_date.php'; 
require_once 'share/format_page.php';
require_once "share/share_message.php";
require_once "share/oa_dec_cur_conv.php";

$ctrlFrm = new Zend_View();
$pesan = new share_message();
$halaman = new format_page();
$dec_cur = new oa_dec_cur_conv();
$format_date = new format_date();


$currentPage = $this->currentPage;
$numToDisplay = $this->numToDisplay;

?>
<div class="navlink">
<a href="#" onclick="open_url_to_home('<?php echo $this->basePath; ?>/home/index/depan','<?php echo $this->basePath; ?>/home/index/main');">Halaman Utama</a>
>>  Data Rekam Pasien
</div>
<div class="panel">
	<div class="inner">
		<span class="corners-top"><span></span></span>
		<h2 class="title">Data Kelurahan <? echo $this->detailPasien['n_nama'];?> , Kode Kelurahan <? echo $this->kode_pasien;?></h2>
			<form method="post" id="frmcarirekampasien" name="frmcarirekampasien">
		<input name="kode_pasien" id="kode_pasien" type="hidden" value="<?echo $this->kode_pasien;?>" />

				<table width="100%" border="0" cellpadding="0" cellspacing="1" class="std">
				</table>
<div class="add" title="Tambah Data" onClick="rekampasienForm('insert','');"></div>			
				Filter :
				<?
				$kategoriCari = array("n_nama" => "Nama", "t_badan" => "Alamat");
	echo $ctrlFrm->formSelect('kategoriCari', $this->kategoriCari, null, $kategoriCari);						
				?>
<input type="text" name="carii" id="carii" align="center" value ="<? echo $this->carii;?>">
				<?
			         $atribSubmit = array("onclick"=>"javascript:carirekampasien();");
			         echo $ctrlFrm->formSubmit('cari', 'Search', $atribSubmit)."&nbsp;";
				?>
	</form>
<fieldset class="fields"> 
<? 
$status = $this->hasil;
$proses = $this->proses;
$pesan->show_message($proses, $k_rekampasien, "$status" ); 
?>
<table id="sorter" class="sortable" cellspacing="1" cellpadding="2" border="0" align="center">
				<th >id</th>
				<th >Noreg</th>
				<th >tanggal</th> 
				<th >berat</th> 
				<th >tinggi</th>
				<th >tekanan</th>
				<th >denyut</th> 
				<th >frequensi</th> 
				<th >suhu</th> 
				
				
				<th colspan="2" class="nosort">FUNGSI</th>
				
				<?
				if (count($this->rekampasienList) == 0){ 
				?>
					<tr class="event2"><td colspan="5"><font color="red">Data Tidak Ditemukan</font></td></tr>
				<?} else {
						
						
						foreach ($this->rekampasienList as $key => $val): 
						if ($key%2==0) { ?>
							<tr class="event">
						<? } else if ($key%2==1) { ?>
							<tr class="event2">
						<? }
						$c_id	= $this->escape($val['c_id']);						
						$c_noreg	= $this->escape($val['c_noreg']); 
						$t_waktu	= $this->escape($val['t_waktu']); 
						$t_berat	= $this->escape($val['t_berat']);
						$t_tinggi	= $this->escape($val['t_tinggi']);
						$t_tekanan	= $this->escape($val['t_tekanan']);
						$t_denyut	= $this->escape($val['t_denyut']);
						$t_frequensi	= $this->escape($val['t_frequensi']);
						$t_suhu	= $this->escape($val['t_suhu']);
						
						
						$noUrut = (($currentPage -1)* $numToDisplay) + $key +1;
						echo $ctrlFrm->formHidden('id', $id, null);
						
						?>
						<td align="center"><? echo $c_id;?></td>
						<td align="center"><? echo $c_noreg;?></td>
						<td align="center"><? echo $t_waktu;?></td>
						<td class="clleft"><? echo $t_berat;?></td>
						<td class="clleft"><? echo $t_tinggi;?></td>
						<td class="clleft"><? echo $t_tekanan;?></td>
						<td class="clleft"><? echo $t_denyut;?></td>
						<td class="clleft"><? echo $t_frequensi;?></td>
						<td class="clleft"><? echo $t_suhu;?></td>
						


<td><div onClick="rekampasienForm('update','<? echo $c_id;?>');" class="edit" title="Ubah Data"></div></td>
<td><div onClick="rekampasienHapus('Data','<? echo $c_id;?>');" class="delete" title="Hapus Data"></div>
						</td>
						
					
						</tr>
					<?
					endforeach;
				}
				?>
			</table>

			<?	
			$totalData = $this->totRekampasienList;
			$modul = $this->basePath."/kelurahan/rekampasien/rekampasienlist";
			$param1 = $this->cabang;$param2 = $this->tahun;$param3 = $this->bulan;$param4 = $this->jenis;$param5 = $this->status;
			echo $halaman->showPage($totalData, $numToDisplay, $currentPage, 'tableview', $modul, $param1, $param2, $param3, $param4);		
			
			?>
		</fieldset>		 
		
		<span class="corners-bottom"><span></span></span>
	</div>
</div>
<script type="text/javascript">
var sorter=new table.sorter("sorter");
sorter.init("sorter",0);
</script>