<? 
require_once 'Zend/View.php';
require_once 'share/format_date.php'; 
require_once 'share/format_page.php';
require_once "share/share_message.php";
require_once "share/oa_dec_cur_conv.php";

$dec_cur = new oa_dec_cur_conv();
$tanggal = new format_date();
$mm= date('m');								
$mm = $mm*1;		
$namaBulanArr = array('1' =>'Januari', 'Pebuari', 'Maret', 'April',  'Mei', 'Juni',  'Juli', 'Agustus', 'September', 'Oktober', 'Nopember', 'Desember');
$bln_srt = $namaBulanArr[$mm];		
$curDate=date("d")."-".$bln_srt."-".date("Y");
		
$servernya = $_SERVER['SERVER_NAME'];								
//$logo = "http://".$servernya."/images/logo.gif";

$html="";
$html = $html.'

<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
<style type="text/css">
</style></head>

<body>
<table width="340" border="0">
  <tr>
    <td align="center" size=18 style=bold>DATA REKAP PENERIMAAN PASIEN TANGGAL '.$tanggal->convertTglMachineToHuman($this->d_medrec).'</td>
  </tr>
</table>


<table width="340" border="0">
  <tr>
    <td>&nbsp;</td>
  </tr>
</table>
</table><table width="340" border="0">
   <tr>
	<td width="50">HARI/TANGGAL</td>
	<td width="5">:</td>
	<td width="285">'.strToUpper($this->detailAjuan['hari'].', '.$tanggal->convertTglMachineToHuman($this->d_medrec)).'</td>
  </tr>
  <tr>
	<td>&nbsp;</td>
	<td>&nbsp;</td>
	<td>&nbsp;</td>
  </tr>
</table>
<BR><BR>
<table width="340" border="1">
  <tr bgcolor=#CCCCCC>
    <td width="10" align="center" size=12>NO</td>
    <td width="30" align="center" size=12>NAMA</td>
    <td width="170" align="center" size=12>Alasan Kedatangan</td>
    <td width="40" align="center" size=12>Tindakan</td>
    <td width="70" align="center" size=12>KETERANGAN</td>
  </tr>
  ';
if (count($this->detailAnalisispasienList) == 0){ 
$html = $html.'<tr ><td colspan="5"><font color="red">Data tidak Ada</font></td></tr>';
} else {
						
					foreach ($this->detailAnalisispasienList as $key => $val): 
					$id		= $this->escape($val['id']); 
					$n_nama		= $this->escape($val['n_nama']); 
					$n_klasifikasi	= $this->escape($val['n_klasifikasi']);
					$n_tindakan	= $this->escape($val['n_tindakan']); 
					$c_alergi	= $this->escape($val['c_alergi']);
					$c_rematik	= $this->escape($val['c_rematik']); 

					$n_alergi ='';
					if($c_alergi =='N'){$n_alergi ='Normal';}
					if($c_alergi =='T'){$n_alergi ='Tidak Normal';}
					$n_rematik ='';
					if($c_rematik =='N'){$n_rematik ='Normal';}
					if($c_rematik =='T'){$n_rematik ='Tidak Normal';}
						
					$noUrut = (($currentPage -1)* $numToDisplay) + $key +1;
				
   $html = $html.'
   <tr>
    <td align=center size=12>&nbsp;'.$noUrut.'</td>
    <td align=center size=12>&nbsp;'.$n_nama.'</td>
    <td align=left size=12>&nbsp;'.$n_klasifikasi.'</td>
    <td align=center size=12>&nbsp;'.$n_tindakan.'</td>
    <td align=left size=12>&nbsp;'.$n_alergi.'</td>
  </tr>';
endforeach;
}
$html = $html.'
</table>
<br />
<table width="340" border="0">
  <tr>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
  </tr>

  <tr>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td align="left">Mengetahui : <BR>Atasan Langsung </td>
    <td>&nbsp;</td>
    <td align="center"><BR>Yang Melaksanakan, </td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
  </tr>

  <tr>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td width="42%" align="left">('.strToUpper(trim($this->detailAjuan['n_peg_atasan'])).')</td>
    <td width="13%">&nbsp;</td>
    <td width="45%" align="center">('.trim(strToUpper($this->detailAjuan['n_peg'])).')</td>
  </tr>
</table>
</body>
</html>';  

//print $html;
define('FPDF_FONTPATH','pdftable/font/');
require('pdftable/lib/pdftable.inc.php');
$p = new PDFTable('L', 'mm', 'Legal');
$p->AddPage();
//$p->Image($logo,20,10,30);
$p->setfont('times','',12);
$p->htmltable($html);
$p->output('','I');


?>

