<? 
require_once 'Zend/View.php';
require_once 'share/format_date.php'; 

$tanggal = new format_date();
$mm= date('m');								
$mm = $mm*1;		
$namaBulanArr = array('1' =>'Januari', 'Pebuari', 'Maret', 'April',  'Mei', 'Juni',  'Juli', 'Agustus', 'September', 'Oktober', 'Nopember', 'Desember');
$bln_srt = $namaBulanArr[$mm];		
$curDate=date("d")."-".$bln_srt."-".date("Y");
		
$servernya = $_SERVER['SERVER_NAME'];								
//$logo = "http://".$servernya."/images/logo.gif";

$html="";
$html = $html.'

<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
<style type="text/css">
</style></head>

<body>
<table width="150" border="0">
  <tr>
    <td align="left" size=18 style=bold width="40">No. Kartu</td>
    <td align="center" size=18 style=bold width="10">:</td>
    <td align="left" size=18 style=bold width="100">'.$this->detailPasien['kode_pasien'].'</td>
  </tr>
  <tr>
    <td align="left" size=18 style=bold>Nama</td>
    <td align="center" size=18 style=bold>:</td>
    <td align="left" size=18 style=bold>'.$this->detailPasien['n_nama'].'</td>
  </tr>
  <tr>
    <td align="left" size=18 style=bold>Umur</td>
    <td align="center" size=18 style=bold>:</td>
    <td align="left" size=18 style=bold>'.$this->detailPasien['n_umur'].'</td>
  </tr>
  <tr>
    <td align="left" size=18 style=bold>Alamat</td>
    <td align="center" size=18 style=bold>:</td>
    <td align="left" size=18 style=bold>'.$this->detailPasien['n_alamat'].'</td>
  </tr>
  <tr>
    <td align="left" size=18 style=bold>Telepon/HP</td>
    <td align="center" size=18 style=bold>:</td>
    <td align="left" size=18 style=bold>'.$this->detailPasien['n_phone'].'/'.$this->detailPasien['n_hp'].'</td>
  </tr>
  <tr>
    <td align="left" size=18 style=bold>Pekerjaan</td>
    <td align="center" size=18 style=bold>:</td>
    <td align="left" size=18 style=bold>'.$this->detailPasien['n_pekerjaan'].'</td>
  </tr>
   <tr>
    <td align="left" size=18 style=bold></td>
    <td align="center" size=18 style=bold></td>
    <td align="left" size=18 style=bold></td>
  </tr>
</table>

<table width="340" border="0">
  <tr>
    <td align="center" size=18 style=bold >DAFTAR MEDICAL RECORD PASIEN</td>
  </tr>
   <tr>
    <td align="left" size=18 style=bold></td>
  </tr>
</table>


<BR><BR>
<table width="340" border="1">
  <tr bgcolor=#CCCCCC>
    <td width="10" align="center" size=12>No</td>
    <td width="30" align="center" size=12>Tanggal</td>
    <td width="100" align="center" size=12>Alasan Kedatangan</td>
    <td width="100" align="center" size=12>Tindakan</td>
    <td width="40" align="center" size=12>Lab. Rematik</td>
    <td width="40" align="center" size=12>Lab. Alergi</td>
  </tr>
  ';
if (count($this->medrecList) == 0){ 
$html = $html.'<tr ><td colspan="5"><font color="red">Data tidak Ada</font></td></tr>';
} else {
						
					foreach ($this->medrecList as $key => $val): 
					$id		= $this->escape($val['id']); 
					$n_nama		= $this->escape($val['n_nama']); 
					$d_medrec	= $this->escape($val['d_medrec']); 
					$n_klasifikasi	= $this->escape($val['n_klasifikasi']);
					$n_tindakan	= $this->escape($val['n_tindakan']); 
					$c_alergi	= $this->escape($val['c_alergi']);
					$c_rematik	= $this->escape($val['c_rematik']); 

					$n_alergi ='';
					if($c_alergi =='N'){$n_alergi ='Normal';}
					if($c_alergi =='T'){$n_alergi ='Tidak Normal';}
					$n_rematik ='';
					if($c_rematik =='N'){$n_rematik ='Normal';}
					if($c_rematik =='T'){$n_rematik ='Tidak Normal';}
						
					$noUrut = (($currentPage -1)* $numToDisplay) + $key +1;
				
   $html = $html.'
   <tr>
    <td align=center size=12>&nbsp;'.$noUrut.'</td>
    <td align=center size=12>&nbsp;'.$tanggal->convertTglMachineToHuman($d_medrec).'</td>
    <td align=left size=12>&nbsp;'.$n_klasifikasi.'</td>
    <td align=center size=12>&nbsp;'.$n_tindakan.'</td>
    <td align=center size=12>&nbsp;'.$n_alergi.'</td>
    <td align=center size=12>&nbsp;'.$n_rematik.'</td>
  </tr>';
endforeach;
}
$html = $html.'
</table>
<br />

</body>
</html>';  

//print $html;
define('FPDF_FONTPATH','pdftable/font/');
require('pdftable/lib/pdftable.inc.php');
$p = new PDFTable('L', 'mm', 'Legal');
$p->AddPage();
//$p->Image($logo,20,10,30);
$p->setfont('times','',12);
$p->htmltable($html);
$p->output('','I');


?>

