<?
require_once 'Zend/View.php';
require_once 'share/format_date.php'; 
require_once 'share/format_page.php';
require_once "share/share_message.php";
require_once "share/oa_dec_cur_conv.php";

$ctrlFrm = new Zend_View();
$pesan = new share_message();
$halaman = new format_page();
$dec_cur = new oa_dec_cur_conv();

$currentPage = $this->currentPage;
$numToDisplay = $this->numToDisplay;

?>
<div class="navlink">
<a href="#" onclick="open_url_to_home('<?php echo $this->basePath; ?>/home/index/depan','<?php echo $this->basePath; ?>/home/index/main');">Halaman Utama</a>
>>  Data Pengguna
</div>
<div class="panel">
	<div class="inner">
		<span class="corners-top"><span></span></span>
		<h2 class="title">DATA PENGGUNA</h2>
			<form method="post" id="frmcaripengguna" name="frmcaripengguna">
				<table width="100%" border="0" cellpadding="0" cellspacing="1" class="std">
				</table>
<div class="add" title="Tambah Data" onClick="penggunaForm('insert','');"></div>			
				Filter :
				<?
				$kategoriCari = array("username" => "Nama Pengguna");
	echo $ctrlFrm->formSelect('kategoriCari', $this->kategoriCari, null, $kategoriCari);						
				?>
<input type="text" name="carii" id="carii" align="center" value ="<? echo $this->carii;?>">
				<?
			         $atribSubmit = array("onclick"=>"javascript:caripengguna();");
			         echo $ctrlFrm->formSubmit('cari', 'Search', $atribSubmit)."&nbsp;";
				?>
	</form>
<fieldset class="fields"> 
<? 
$status = $this->hasil;
$proses = $this->proses;
$pesan->show_message($proses, $k_pengguna, "$status" ); 
?>
<table id="sorter" class="sortable" cellspacing="1" cellpadding="2" border="0" align="center">
				<th >No</th>
				<th >Username</th> 
				<th >Nama</th> 
				<th >Group</th> 
				<th colspan="3" class="nosort">FUNGSI</th>
				
				<?
				if (count($this->penggunaList) == 0){ 
				?>
					<tr class="event2"><td colspan="5"><font color="red">Data Tidak Ditemukan</font></td></tr>
				<?} else {
						
						
						foreach ($this->penggunaList as $key => $val): 
						if ($key%2==0) { ?>
							<tr class="event">
						<? } else if ($key%2==1) { ?>
							<tr class="event2">
						<? } 
						$userid		= $this->escape($val['userid']); 
						$username		= $this->escape($val['username']);
						$c_group	= $this->escape($val['c_group']);
						$n_group	= $this->escape($val['n_group']);
						$nama	= $this->escape($val['nama']);
					
						$noUrut = (($currentPage -1)* $numToDisplay) + $key +1;
						echo $ctrlFrm->formHidden('id', $id, null);
						
						?>
<td align="center"><? echo $noUrut;?></td>
<td class="clleft"><? echo $username;?></td>
<td class="clleft"><? echo $nama;?></td>
<td class="clleft"><? echo $n_group;?></td>

<td><div onClick="penggunaForm('update','<? echo $userid;?>');" class="edit" title="Ubah Data"></div></td>
<td><div onClick="penggunaHapus('Data','<? echo $userid;?>','<? echo $username;?>');" class="delete" title="Hapus Data"></div></td>


						
					
						</tr>
					<?
					endforeach;
				}
				?>
			</table>

			<?	
			$totalData = $this->totPenggunaList;
			$modul = $this->basePath."/pasien/pengguna/penggunalist";
			$param1 = $this->cabang;$param2 = $this->tahun;$param3 = $this->bulan;$param4 = $this->jenis;$param5 = $this->status;
			echo $halaman->showPage($totalData, $numToDisplay, $currentPage, 'tableview', $modul, $param1, $param2, $param3, $param4);		
			
			?>
		</fieldset>		 
		
		<span class="corners-bottom"><span></span></span>
	</div>
</div>
<script type="text/javascript">
var sorter=new table.sorter("sorter");
sorter.init("sorter",0);
</script>