<?php 
require_once 'Zend/View.php';
$ctrlFrm = new Zend_View();
$pesancek=$this->pesancek;
$cstatus=$this->status;


if ($cstatus!='') {
	if ($cstatus==1) $status1='checked';
	else $status0='checked';
} else $status1='checked';

if ($pesancek=='gagal'){$confirm ='confirmfail';}
else {$confirm ='confirm';}


?>
 <script type="text/javascript" src="<?echo $this->baseUrl;?>/content/init.js"></script>


		   <div class="navlink">
				<a  href="<? echo $this->basePath; ?>cms">Halaman Utama</a> 
				<strong> &#8250; </strong> <a href="#" onclick="open_url_to_div('<?php echo $this->basePath; ?>/cmsmodule/kontakkami/listkontakkami','<?php echo $this->basePath; ?>/cmsmodule/pegawai/pegawaijs');">Kelola Data kontakkami</a>
				<strong> &#8250; </strong><?=$this->jdl;?> Data kontak kami
			</div>
			<br>
<div id="top"></div>
<div id="confirm" class="<?=$confirm?>" style="display: none">
	<h3><?echo $pesan = $this->pesan;?></h3>				
</div>

	
<form id="formkontakkami" method="post" name="formkontakkami" action="">
<input type="hidden" value="<?=$this->idkontakkami?>" name="idkontakkami"> 
<input type="hidden" value="<?=$this->par?>" name="action"> 
<h2 class="title"><?=$this->jdl;?> Data Kontak Kami</h2>

		<div class="spacer"></div> 

<table  width="100%">
 <tr>
   <td width="20%">Status Kontak Kami</td>
   <td width="1%">:</td>
   <td width="79%">
   	<label for="post_status_publish" class="selectit"><input id="post_status_publish" class="radio" name="status" type="radio" value="1" <?=$status1?> /> Diterbitkan</label>
    <label for="post_status_kontakkami" class="selectit"><input id="post_status_kontakkami" class="radio" name="status" type="radio" value="0"  <?=$status0?> /> Tidak Diterbitkan</label>

   </td>
 </tr>
 <tr>
   <td width="20%">Judul kontak kami <span class="highlight">*</span></td>
   <td width="1%">:</td>
   <td width="79%"><input type="text" name="title" size="30" tabindex="1" value="<?=$this->jdlkontakkami?>" id="title"/></td>
 </tr>
 <tr>
   <td width="20%">Isi kontak kami</td>
   <td width="1%">:</td>
   <td width="79%"><textarea id="content" name="content" style="height:300px"><?=$this->detilkontakkami?></textarea></td>
 </tr>
</table>
ket :&nbsp;(<span class="highlight">*</span>)&nbsp;harus diisi
		<p class="submit">
		<span id="autosave"></span>

		<input name="cancel" type="button" id="publish" tabindex="5" accesskey="p" value="Batal" onClick="open_url_to_div('<?php echo $this->basePath; ?>/cmsmodule/kontakkami/listkontakkami','<?php echo $this->basePath; ?>/cmsmodule/kontakkami/kontakkamijs');"/>
		<input type="submit" name="submit" value="<?=$this->pars;?>" onClick="insertkontakkami()" style="font-weight: bold;" />


	
</form>	
